# Generated automatically from Makefile.in by configure.
# KDE tags expanded automatically by am_edit - $Revision$
# Makefile.in generated automatically by automake 1.4a from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

SHELL = /bin/sh

srcdir = .
top_srcdir = ../..
prefix = /home/devel/local/kde
exec_prefix = ${prefix}

bindir = $(exec_prefix)/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/koffice
pkglibdir = $(libdir)/koffice
pkgincludedir = $(includedir)/koffice

top_builddir = ../..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = install -c -p -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_FLAG =
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux-gnu
build_triplet = i686-pc-linux-gnu
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_alias = @target_alias@
target_triplet = @target@
AMTAR = gtar
AMTARFLAGS = o
AS = @AS@
CC = gcc
CPP = gcc -E
CXX = g++
CXXCPP = @CXXCPP@
DLLTOOL = @DLLTOOL@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = /usr/bin/msgfmt
IDL = /usr/local/bin/idl
KATABASE_DIR = katabase
KATABASE_LIBS = -lpq++
KDE_EXTRA_RPATH = 
KDE_INCLUDES = -I/home/devel/local/kde/include
KDE_LDFLAGS = -L/home/devel/local/kde/lib
KDE_RPATH = -rpath $(kde_libraries) -rpath $(qt_libraries) -rpath $(x_libraries)
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
KOFFICECORE_INCLUDES = -I$(top_srcdir)/lib/kofficecore -I$(top_builddir)/lib/kofficecore
KOFFICEUI_INCLUDES = -I$(top_srcdir)/lib/kofficeui -I$(top_builddir)/lib/kofficeui
KOFFICE_INCLUDES = -I$(top_srcdir)/lib $(KOFFICEUI_INCLUDES) $(KOFFICECORE_INCLUDES) $(KOML_INCLUDES) $(KSTORE_INCLUDES)
KOFFICE_LIBS = $(LIB_KOFFICEUI) $(LIB_KOFFICECORE) $(LIB_KSTORE) $(LIB_KOML) $(LIB_KDEUTIL)
KOML_INCLUDES = -I$(top_srcdir)/lib/koml -I$(top_builddir)/lib/koml
KSTORE_INCLUDES = -I$(top_srcdir)/lib/store -I$(top_builddir)/lib/store
LD = /usr/bin/ld
LIBCOMPAT = 
LIBCRYPT = -lcrypt
LIBDL = -ldl
LIBJPEG = -ljpeg6b
LIBMICO = -lmico2.2.7 -lcrypt  -ldl
LIBOBJS = @LIBOBJS@
LIBPNG = -lpng -lz -lm
LIBPTHREAD = @LIBPTHREAD@
LIBPYTHON = @LIBPYTHON@
LIBQIMGIO = 
LIBSOCKET = 
LIBTIFF = -ltiff -ljpeg6b -lz
LIBTOOL = $(SHELL) $(top_builddir)/libtool --silent
LIBUCB = 
LIBZ = -lz
LIB_KAB = -lkab
LIB_KDECORE = -lkdecore
LIB_KDEUI = -lkdeui
LIB_KFILE = -lkfile
LIB_KFM = 
LIB_KFORMULA = -lformula
LIB_KHTML = -lkhtml
LIB_KIMGIO = -lkimgio
LIB_KIO = -lkio
LIB_KOFFICECORE = $(top_builddir)/lib/kofficecore/libkofficecore.la
LIB_KOFFICEUI = $(top_builddir)/lib/kofficeui/libkofficeui.la
LIB_KOML = $(top_builddir)/lib/koml/libkoml.la
LIB_KSTORE = $(top_builddir)/lib/store/libkstore.la
LIB_MEDIATOOL = -lmediatool
LIB_QT = -lqt $(LIBPNG) -lXext $(LIB_X11) $(X_PRE_LIBS)
LIB_SMB = -lsmb
LIB_X11 = -lX11 $(LIBSOCKET)
LN_S = ln -s
MAKEINFO = makeinfo
MICO_INCLUDES = -I/usr/local/include
MICO_LDFLAGS = -L/usr/local/lib
MOC = /home/devel-qt/qt/bin/moc
MSGFMT = /usr/bin/msgfmt
NM = /usr/bin/nm -B
OBJDUMP = @OBJDUMP@
PACKAGE = koffice
PAMINC = @PAMINC@
PAMLIBPATHS = @PAMLIBPATHS@
PAMLIBS = @PAMLIBS@
PGSQLINC = -I/usr/include/pgsql
PGSQLLIB = -L/usr/lib
PYTHONINC = @PYTHONINC@
PYTHONLIB = @PYTHONLIB@
QT_INCLUDES = -I/home/devel-qt/qt/include
QT_LDFLAGS = -L/home/devel-qt/qt/lib
RANLIB = ranlib
TOPSUBDIRS = @TOPSUBDIRS@
USER_INCLUDES = 
USER_LDFLAGS = 
USE_NLS = yes
VERSION = 0.1
XGETTEXT = /usr/bin/xgettext
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS = 
X_INCLUDES = -I/usr/X11R6/include
X_LDFLAGS = -L/usr/X11R6/lib
X_PRE_LIBS =  -lSM -lICE
all_includes = -I/home/devel/local/kde/include -I/home/devel-qt/qt/include  -I/usr/X11R6/include
all_libraries = -L/home/devel/local/kde/lib -L/home/devel-qt/qt/lib  -L/usr/X11R6/lib
idldir = $(includedir)/idl
interfacedir = $(top_srcdir)/lib/interfaces
kde_appsdir = $(prefix)/share/applnk
kde_bindir = $(exec_prefix)/bin
kde_cgidir = $(exec_prefix)/cgi-bin
kde_confdir = $(prefix)/share/config
kde_datadir = $(prefix)/share/apps
kde_htmldir = $(prefix)/share/doc/HTML
kde_icondir = $(prefix)/share/icons
kde_includes = /home/devel/local/kde/include
kde_libraries = /home/devel/local/kde/lib
kde_locale = $(prefix)/share/locale
kde_mimedir = $(prefix)/share/mimelnk
kde_minidir = $(prefix)/share/icons/mini
kde_servicesdir = $(prefix)/share/services
kde_servicetypesdir = $(prefix)/share/servicetypes
kde_sounddir = $(prefix)/share/sounds
kde_toolbardir = $(prefix)/share/toolbar
kde_wallpaperdir = $(prefix)/share/wallpapers
micodir = /usr/local
qt_includes = /home/devel-qt/qt/include
qt_libraries = /home/devel-qt/qt/lib
x_includes = /usr/X11R6/include
x_libraries = /usr/X11R6/lib


INCLUDES = $(MICO_INCLUDES) $(KOFFICE_INCLUDES) $(all_includes)
LDFLAGS = $(all_libraries) $(MICO_LDFLAGS) $(KDE_RPATH)
LDADD = $(LIB_KOFFICEUI) $(LIB_KIMGIO) -lqimgio -ljpeg

#SUBDIRS = icons images

bin_PROGRAMS = canvas testFastPixmap

canvas_SOURCES = brush.cc canvas.cc channel.cc layer.cc layerlist.cc misc.cc numSlider.cc main.cc

testFastPixmap_SOURCES = testFastPixmap.cc

noinst_HEADERS = brush.h canvas.h channel.h layer.h layerlist.h misc.h numSlider.h

#>- METASOURCES = canvas.moc layer.moc numSlider.moc
mkinstalldirs = $(SHELL) $(top_srcdir)/admin/mkinstalldirs
CONFIG_HEADER = ../../config.h
CONFIG_CLEAN_FILES = 
PROGRAMS =  $(bin_PROGRAMS)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I../..
CPPFLAGS = 
LIBS = 
am_canvas_OBJECTS =  brush.o canvas.o channel.o layer.o layerlist.o \
misc.o numSlider.o main.o
#>- canvas_OBJECTS =  $(am_canvas_OBJECTS)
#>+ 4
canvas_OBJECTS = brush.o canvas.o channel.o layer.o layerlist.o \
misc.o numSlider.o main.o
#canvas_OBJECTS = canvas.all_cc.o 
canvas_final_OBJECTS = canvas.all_cc.o 
canvas_LDADD = $(LDADD)
canvas_DEPENDENCIES = 
canvas_LDFLAGS = 
am_testFastPixmap_OBJECTS =  testFastPixmap.o
#>- testFastPixmap_OBJECTS =  $(am_testFastPixmap_OBJECTS)
#>+ 1
testFastPixmap_OBJECTS = testFastPixmap.o
testFastPixmap_LDADD = $(LDADD)
testFastPixmap_DEPENDENCIES = 
testFastPixmap_LDFLAGS = 
CXXFLAGS = -O2
CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
DIST_SOURCES =  $(canvas_SOURCES) $(testFastPixmap_SOURCES)
HEADERS =  $(noinst_HEADERS)

DIST_COMMON =  $(noinst_HEADERS) COPYING Makefile.am Makefile.in TODO


DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

GZIP_ENV = --best
#>- DEP_FILES =  .deps/brush.P .deps/canvas.P .deps/channel.P .deps/layer.P \
#>- .deps/layerlist.P .deps/main.P .deps/misc.P .deps/numSlider.P \
#>- .deps/testFastPixmap.P

#>+ 5
DEP_FILES =  .deps/canvas.all_cc.P \
  .deps/brush.P .deps/canvas.P .deps/channel.P .deps/layer.P \
.deps/layerlist.P .deps/main.P .deps/misc.P .deps/numSlider.P \
.deps/testFastPixmap.P
SOURCES = $(canvas_SOURCES) $(testFastPixmap_SOURCES)
OBJECTS = $(am_canvas_OBJECTS) $(am_testFastPixmap_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .c .cc .lo .o
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/$(altdir)configure.in $(ACLOCAL_M4) 
#>- 	cd $(top_srcdir) && $(AUTOMAKE) --gnu kimageshop/canvas/Makefile
#>+ 2
	cd $(top_srcdir) && $(AUTOMAKE) --gnu kimageshop/canvas/Makefile
	cd $(top_srcdir) && perl admin/am_edit kimageshop/canvas/Makefile.in

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-binPROGRAMS:

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

distclean-binPROGRAMS:

maintainer-clean-binPROGRAMS:

install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  if test -f $$p; then \
	    f="`echo $$p|sed -e 's/$(EXEEXT)$$//' -e '$(transform)' -e 's/$$/$(EXEEXT)/'`"; \
	    echo " $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $(INSTALL_STRIP_FLAG) $$p $(DESTDIR)$(bindir)/$$f"; \
	    $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $(INSTALL_STRIP_FLAG) $$p $(DESTDIR)$(bindir)/$$f; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f="`echo $$p|sed -e 's/$(EXEEXT)$$//' -e '$(transform)' -e 's/$$/$(EXEEXT)/'`"; \
	  echo " rm -f $(DESTDIR)$(bindir)/$$f"; \
	  rm -f $(DESTDIR)$(bindir)/$$f; \
	done

mostlyclean-compile:
	-rm -f *.o core *.core

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:
brush.o:
canvas.o:
channel.o:
layer.o:
layerlist.o:
misc.o:
numSlider.o:
main.o:

canvas: $(canvas_OBJECTS) $(canvas_DEPENDENCIES)
	@rm -f canvas
	$(CXXLINK) $(canvas_LDFLAGS) $(canvas_OBJECTS) $(canvas_LDADD) $(LIBS)
testFastPixmap.o:

testFastPixmap: $(testFastPixmap_OBJECTS) $(testFastPixmap_DEPENDENCIES)
	@rm -f testFastPixmap
	$(CXXLINK) $(testFastPixmap_LDFLAGS) $(testFastPixmap_OBJECTS) $(testFastPixmap_LDADD) $(LIBS)
.cc.o:
	$(CXXCOMPILE) -c -o $@ $<
.cc.lo:
	$(LTCXXCOMPILE) -c -o $@ $<

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = kimageshop/canvas

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu kimageshop/canvas/Makefile
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done

DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)

-include $(DEP_FILES)

mostlyclean-depend:

clean-depend:

distclean-depend:
	-rm -rf .deps

maintainer-clean-depend:

%.o: %.cc
	@echo '$(CXXCOMPILE) -c $<'; \
	$(CXXCOMPILE) -Wp,-MD,.deps/$(*D)/$(*F).pp -c $<
	@-cp .deps/$(*D)/$(*F).pp .deps/$(*D)/$(*F).P; \
	tr ' ' '\012' < .deps/$(*D)/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*D)/$(*F).P; \
	rm .deps/$(*D)/$(*F).pp

%.lo: %.cc
	@echo '$(LTCXXCOMPILE) -c $<'; \
	$(LTCXXCOMPILE) -Wp,-MD,.deps/$(*D)/$(*F).pp -c $<
	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
	  < .deps/$(*D)/$(*F).pp > .deps/$(*D)/$(*F).P; \
	tr ' ' '\012' < .deps/$(*D)/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*D)/$(*F).P; \
	rm -f .deps/$(*D)/$(*F).pp
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-binPROGRAMS
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-binPROGRAMS
uninstall: uninstall-am
all-am: Makefile $(PROGRAMS) $(HEADERS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_STRIP_FLAG=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(bindir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-binPROGRAMS mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags mostlyclean-depend \
		mostlyclean-generic

mostlyclean: mostlyclean-am

#>- clean-am:  clean-binPROGRAMS clean-compile clean-libtool clean-tags \
#>- 		clean-depend clean-generic mostlyclean-am
#>+ 2
clean-am: clean-metasources clean-final   clean-binPROGRAMS clean-compile clean-libtool clean-tags \
		clean-depend clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-binPROGRAMS distclean-compile distclean-libtool \
		distclean-tags distclean-depend distclean-generic \
		clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-binPROGRAMS \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-depend \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-binPROGRAMS distclean-binPROGRAMS clean-binPROGRAMS \
maintainer-clean-binPROGRAMS uninstall-binPROGRAMS install-binPROGRAMS \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool tags mostlyclean-tags \
distclean-tags clean-tags maintainer-clean-tags distdir \
mostlyclean-depend distclean-depend clean-depend \
maintainer-clean-depend info-am info dvi-am dvi check check-am \
installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all install-strip installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

#>+ 4
$(srcdir)/numSlider.cc: numSlider.moc
numSlider.moc: $(srcdir)/numSlider.h
	$(MOC) $(srcdir)/numSlider.h -o numSlider.moc

#>+ 4
$(srcdir)/canvas.cc: canvas.moc
canvas.moc: $(srcdir)/canvas.h
	$(MOC) $(srcdir)/canvas.h -o canvas.moc

#>+ 4
$(srcdir)/layer.cc: layer.moc
layer.moc: $(srcdir)/layer.h
	$(MOC) $(srcdir)/layer.h -o layer.moc

#>+ 3
clean-metasources:
	-rm -f  numSlider.moc canvas.moc layer.moc

#>+ 5
force-reedit:
		cd $(top_srcdir) && $(AUTOMAKE) --gnu kimageshop/canvas/Makefile
	cd $(top_srcdir) && perl admin/am_edit kimageshop/canvas/Makefile.in


#>+ 11
canvas.all_cc.cc: $(srcdir)/Makefile.in $(srcdir)/brush.cc $(srcdir)/canvas.cc $(srcdir)/channel.cc $(srcdir)/layer.cc $(srcdir)/layerlist.cc $(srcdir)/misc.cc $(srcdir)/numSlider.cc $(srcdir)/main.cc   numSlider.moc canvas.moc layer.moc 
	@echo 'creating canvas.all_cc.cc ...'; \
	rm -f canvas.all_cc.files canvas.all_cc.final; \
	echo "#define KDE_USE_FINAL 1" >> canvas.all_cc.final; \
	for file in brush.cc canvas.cc channel.cc layer.cc layerlist.cc misc.cc numSlider.cc main.cc ; do \
	  echo "#include \"$$file\"" >> canvas.all_cc.files; \
	  test ! -f $(srcdir)/$$file || egrep '^#pragma +implementation' $(srcdir)/$$file >> canvas.all_cc.final; \
	done; \
	cat canvas.all_cc.final canvas.all_cc.files  > canvas.all_cc.cc; \
	rm -f canvas.all_cc.final canvas.all_cc.files

#>+ 3
clean-final:
	-rm -f canvas.all_cc.cc

#>+ 2
final:
	$(MAKE) canvas_OBJECTS="$(canvas_final_OBJECTS)" all-am
#>+ 3
cvs-clean:
	$(MAKE) -f $(top_srcdir)/admin/Makefile.common cvs-clean
