#ifndef KIllustrator_idl_
#define KIllustrator_idl_

#include <parts.idl>

module KIllustrator {
  interface Shell : OPParts::PartShell {
    oneway void fileNew ();
    oneway void fileOpen ();
    oneway void fileClose ();
    oneway void fileQuit ();
    oneway void fileSave ();	
    oneway void fileSaveAs ();
    oneway void filePrint ();

    oneway void editCut ();
    oneway void editCopy ();
    oneway void editPaste ();

    oneway void setZoomFactor (in string size);

    oneway void helpAbout();
  };

  interface View : OPParts::View {
    oneway void editUndo ();
    oneway void editRedo ();
    oneway void editCut ();
    oneway void editCopy ();
    oneway void editPaste ();
    oneway void editSelectAll ();
    oneway void editDelete ();
    oneway void editInsertOject ();
    oneway void editProperties ();

    oneway void transformPosition ();
    oneway void transformDimension ();
    oneway void transformRotation ();
    oneway void transformMirror ();

    oneway void arrangeAlign ();
    oneway void arrangeToFront ();
    oneway void arrangeToBack ();
    oneway void arrangeOneForward ();
    oneway void arrangeOneBack ();
    oneway void arrangeGroup ();
    oneway void arrangeUngroup ();

    oneway void editLayers ();

    oneway void toggleRuler ();
    oneway void toggleGrid ();

    oneway void setupGrid ();
    oneway void alignToGrid ();

    oneway void configureTool (in long id);
    oneway void activateTool (in long id);

    oneway void setPenColor (in long id);
    oneway void setFillColor (in long id);
  };
  
  interface Document : OPParts::Document {
  };
  
  interface Factory : OPParts::Factory {
  };
};

#endif
