#ifndef KIllustrator_idl_
#define KIllustrator_idl_

#include <openparts.idl>
#include <koffice.idl>
#include <openparts_ui.idl>
 
module KIllustrator {
  interface View : KOffice::View {
    slot void editUndo ();
    slot void editRedo ();
    slot void editCut ();
    slot void editCopy ();
    slot void editPaste ();
    slot void editSelectAll ();
    slot void editDelete ();
    slot void editInsertOject ();
    slot void editProperties ();

    slot void viewOutline ();
    slot void viewNormal ();

    slot void transformPosition ();
    slot void transformDimension ();
    slot void transformRotation ();
    slot void transformMirror ();

    slot void arrangeAlign ();
    slot void arrangeToFront ();
    slot void arrangeToBack ();
    slot void arrangeOneForward ();
    slot void arrangeOneBack ();
    slot void arrangeGroup ();
    slot void arrangeUngroup ();

    slot void editLayers ();
    slot void setupPage ();

    slot void toggleRuler ();
    slot void toggleGrid ();

    slot void setupGrid ();
    slot void alignToGrid ();

    slot void toolSelection ();
    slot void toolEditPoint ();
    slot void toolFreehandLine ();
    slot void toolPolyline ();
    slot void toolBezier ();
    slot void toolRectangle ();
    slot void toolPolygon ();
    slot void toolEllipse ();
    slot void toolText ();
    slot void toolZoom ();

    slot void toolMovePoint ();
    slot void toolInsertPoint ();
    slot void toolRemovePoint ();

    slot void configPolygonTool ();
    slot void configEllipseTool ();
	
    slot void setPenColor (in long id);
    slot void setFillColor (in long id);

    slot void zoomSizeSelected (in string size);
  };
  
  interface Document : KOffice::Document, KOffice::Print {
  };

  interface DocumentFactory : KOffice::DocumentFactory
  {
  };
};

#endif
