all:
	@echo "This file is to make it easier for you to create all you need"
	cat acinclude.m4.in libtool.m4.in > acinclude.m4
	aclocal
	autoheader
# use --include-deps, if you want to release the stuff. Don't use it for
# yourself
	automake
	autoconf
	touch stamp-h.in

