# Generated automatically from Makefile.in by configure.
# KDE tags expanded automatically by am_edit
# Makefile.in generated automatically by automake 1.4a from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

SHELL = /bin/sh

srcdir = .
top_srcdir = ../..
prefix = /home/devel/local/kde
exec_prefix = ${prefix}

bindir = $(exec_prefix)/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/koffice
pkglibdir = $(libdir)/koffice
pkgincludedir = $(includedir)/koffice

top_builddir = ../..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_FLAG =
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux-gnu
build_triplet = i686-pc-linux-gnu
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_alias = @target_alias@
target_triplet = @target@
AMTAR = gtar
AMTARFLAGS = o
AS = @AS@
CC = gcc
CPP = gcc -E
CXX = g++
CXXCPP = @CXXCPP@
DLLTOOL = @DLLTOOL@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = /usr/bin/msgfmt
IDL = /usr/local/bin/idl
KDE_EXTRA_RPATH = 
KDE_INCLUDES = -I/home/devel/local/kde/include
KDE_LDFLAGS = -L/home/devel/local/kde/lib
KDE_RPATH = -rpath $(kde_libraries) -rpath $(qt_libraries) -rpath $(x_libraries)
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
KOFFICECORE_INCLUDES = -I$(top_srcdir)/lib/kofficecore -I$(top_builddir)/lib/kofficecore
KOFFICEUI_INCLUDES = -I$(top_srcdir)/lib/kofficeui -I$(top_builddir)/lib/kofficeui
KOFFICE_INCLUDES = -I$(top_srcdir)/lib $(KOFFICEUI_INCLUDES) $(KOFFICECORE_INCLUDES) $(KOML_INCLUDES) $(KSTORE_INCLUDES)
KOFFICE_LIBS = $(LIB_KOFFICEUI) $(LIB_KOFFICECORE) $(LIB_KSTORE) $(LIB_KOML) $(LIB_KDEUTIL)
KOML_INCLUDES = -I$(top_srcdir)/lib/koml -I$(top_builddir)/lib/koml
KSTORE_INCLUDES = -I$(top_srcdir)/lib/store -I$(top_builddir)/lib/store
LD = /usr/bin/ld
LIBCOMPAT = 
LIBCRYPT = -lcrypt
LIBDL = -ldl
LIBJPEG = -ljpeg6b
LIBMICO = -lmico2.2.7 -lcrypt  -ldl
LIBOBJS = @LIBOBJS@
LIBPNG = -lpng -lz -lm
LIBPTHREAD = @LIBPTHREAD@
LIBPYTHON = @LIBPYTHON@
LIBQIMGIO = 
LIBSOCKET = 
LIBTIFF = -ltiff -ljpeg6b -lz
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBUCB = 
LIBZ = -lz
LIB_KAB = -lkab
LIB_KDECORE = -lkdecore
LIB_KDEUI = -lkdeui
LIB_KFILE = -lkfile
LIB_KFM = 
LIB_KFORMULA = -lformula
LIB_KHTML = -lkhtml
LIB_KIMGIO = -lkimgio
LIB_KIO = -lkio
LIB_KOFFICECORE = $(top_builddir)/lib/kofficecore/libkofficecore.la
LIB_KOFFICEUI = $(top_builddir)/lib/kofficeui/libkofficeui.la
LIB_KOML = $(top_builddir)/lib/koml/libkoml.la
LIB_KSTORE = $(top_builddir)/lib/store/libkstore.la
LIB_MEDIATOOL = -lmediatool
LIB_QT = -lqt $(LIBPNG) -lXext $(LIB_X11) -lICE -lSM
LIB_SMB = -lsmb
LIB_X11 = -lX11 $(LIBSOCKET)
LN_S = ln -s
MAKEINFO = makeinfo
MICO_INCLUDES = -I/usr/local/include
MICO_LDFLAGS = -L/usr/local/lib
MOC = /home/devel-qt/qt/bin/moc
MSGFMT = /usr/bin/msgfmt
NM = /usr/bin/nm -B
OBJDUMP = @OBJDUMP@
PACKAGE = koffice
PAMINC = @PAMINC@
PAMLIBPATHS = @PAMLIBPATHS@
PAMLIBS = @PAMLIBS@
PYTHONINC = @PYTHONINC@
PYTHONLIB = @PYTHONLIB@
QT_INCLUDES = -I/home/devel-qt/qt/include
QT_LDFLAGS = -L/home/devel-qt/qt/lib
RANLIB = ranlib
TOPSUBDIRS = @TOPSUBDIRS@
USER_INCLUDES = 
USER_LDFLAGS = 
USE_NLS = yes
VERSION = 0.1
XGETTEXT = /usr/bin/xgettext
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS = 
X_INCLUDES = -I/usr/X11R6/include
X_LDFLAGS = -L/usr/X11R6/lib
all_includes = -I/home/devel/local/kde/include -I/home/devel-qt/qt/include  -I/usr/X11R6/include
all_libraries = -L/home/devel/local/kde/lib -L/home/devel-qt/qt/lib  -L/usr/X11R6/lib
idldir = $(includedir)/idl
interfacedir = $(top_srcdir)/lib/interfaces
kde_appsdir = $(prefix)/share/applnk
kde_bindir = $(exec_prefix)/bin
kde_cgidir = $(exec_prefix)/cgi-bin
kde_confdir = $(prefix)/share/config
kde_datadir = $(prefix)/share/apps
kde_htmldir = $(prefix)/share/doc/HTML
kde_icondir = $(prefix)/share/icons
kde_includes = /home/devel/local/kde/include
kde_libraries = /home/devel/local/kde/lib
kde_locale = $(prefix)/share/locale
kde_mimedir = $(prefix)/share/mimelnk
kde_minidir = $(prefix)/share/icons/mini
kde_partsdir = $(exec_prefix)/parts
kde_servicesdir = $(prefix)/share/services
kde_servicetypesdir = $(prefix)/share/servicetypes
kde_sounddir = $(prefix)/share/sounds
kde_toolbardir = $(prefix)/share/toolbar
kde_wallpaperdir = $(prefix)/share/wallpapers
micodir = /usr/local
qt_includes = /home/devel-qt/qt/include
qt_libraries = /home/devel-qt/qt/lib
x_includes = /usr/X11R6/include
x_libraries = /usr/X11R6/lib


INCLUDES = $(MICO_INCLUDES) $(KOFFICE_INCLUDES) $(all_includes) -I$(idldir)
LDFLAGS = $(all_libraries) $(MICO_LDFLAGS) $(KDE_RPATH)
LDADD = $(LIB_KOFFICEUI) $(LIB_KIMGIO)

####### Files

bin_PROGRAMS = kformviewer

kformviewer_SOURCES = \
 kformviewer.idl \
 kformviewer_main.cc \
 kformviewer_shell.cc \
 kformviewer_doc.cc \
 kformviewer_view.cc


noinst_HEADERS = \
 kformviewer.h \
 kformviewer_main.h \
 kformviewer_shell.h \
 kformviewer_doc.h \
 kformviewer_view.h


#>- METASOURCES = \
#>-  kformviewer_main.moc \
#>-  kformviewer_shell.moc \
#>-  kformviewer_doc.moc \
#>-  kformviewer_view.moc


idl_DATA = kformviewer.idl

kdelnk_DATA = kformviewer.desktop
kdelnkdir = $(kde_appsdir)/KOffice

####### Implicit rules

####### Build rules

IDL_FLAGS = --query-server-for-narrow --relative-paths -I$(top_srcdir)/lib/kofficecore -I$(top_srcdir)/lib/store -I$(interfacedir) -I$(idldir)
mkinstalldirs = $(SHELL) $(top_srcdir)/admin/mkinstalldirs
CONFIG_HEADER = ../../config.h
CONFIG_CLEAN_FILES = 
PROGRAMS =  $(bin_PROGRAMS)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I../..
CPPFLAGS = 
LIBS = 
am_kformviewer_OBJECTS =  kformviewer_main.o kformviewer_shell.o \
kformviewer_doc.o kformviewer_view.o
#>- kformviewer_OBJECTS =  $(am_kformviewer_OBJECTS)
#>+ 4
kformviewer_OBJECTS = kformviewer_main.o kformviewer_shell.o \
kformviewer_doc.o kformviewer_view.o kformviewer.o
#kformviewer_OBJECTS = kformviewer.all_cc.o 
kformviewer_final_OBJECTS = kformviewer.all_cc.o 
kformviewer_LDADD = $(LDADD)
kformviewer_DEPENDENCIES = 
kformviewer_LDFLAGS = 
CXXFLAGS = -O2
CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
DIST_SOURCES =  $(kformviewer_SOURCES)
DATA =  $(idl_DATA) $(kdelnk_DATA)

HEADERS =  $(noinst_HEADERS)

DIST_COMMON =  $(idl_DATA) $(kdelnk_DATA) $(noinst_HEADERS) Makefile.am \
Makefile.in


DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

GZIP_ENV = --best
#>- DEP_FILES =  .deps/kformviewer_doc.P .deps/kformviewer_main.P \
#>- .deps/kformviewer_shell.P .deps/kformviewer_view.P

#>+ 4
DEP_FILES =  .deps/kformviewer.all_cc.P \
  .deps/kformviewer_doc.P .deps/kformviewer_main.P \
.deps/kformviewer_shell.P .deps/kformviewer_view.P
SOURCES = $(kformviewer_SOURCES)
OBJECTS = $(am_kformviewer_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .c .cc .lo .o
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/$(altdir)configure.in $(ACLOCAL_M4) 
#>- 	cd $(top_srcdir) && $(AUTOMAKE) --gnu katabase/kformviewer/Makefile
#>+ 2
	cd $(top_srcdir) && $(AUTOMAKE) --gnu katabase/kformviewer/Makefile
	cd $(top_srcdir) && perl admin/am_edit katabase/kformviewer/Makefile.in

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-binPROGRAMS:

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

distclean-binPROGRAMS:

maintainer-clean-binPROGRAMS:

install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  if test -f $$p; then \
	    f="`echo $$p|sed -e 's/$(EXEEXT)$$//' -e '$(transform)' -e 's/$$/$(EXEEXT)/'`"; \
	    echo " $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $(INSTALL_STRIP_FLAG) $$p $(DESTDIR)$(bindir)/$$f"; \
	    $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $(INSTALL_STRIP_FLAG) $$p $(DESTDIR)$(bindir)/$$f; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f="`echo $$p|sed -e 's/$(EXEEXT)$$//' -e '$(transform)' -e 's/$$/$(EXEEXT)/'`"; \
	  echo " rm -f $(DESTDIR)$(bindir)/$$f"; \
	  rm -f $(DESTDIR)$(bindir)/$$f; \
	done

mostlyclean-compile:
	-rm -f *.o core *.core

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:
kformviewer_main.o:
kformviewer_shell.o:
kformviewer_doc.o:
kformviewer_view.o:

#>- kformviewer: $(kformviewer_OBJECTS) $(kformviewer_DEPENDENCIES)
#>+ 2
kformviewer: kformviewer.h $(kformviewer_OBJECTS) $(kformviewer_DEPENDENCIES)

	@rm -f kformviewer
	$(CXXLINK) $(kformviewer_LDFLAGS) $(kformviewer_OBJECTS) $(kformviewer_LDADD) $(LIBS)
.cc.o:
	$(CXXCOMPILE) -c -o $@ $<
.cc.lo:
	$(LTCXXCOMPILE) -c -o $@ $<

install-idlDATA: $(idl_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(idldir)
	@list='$(idl_DATA)'; for p in $$list; do \
	  if test -f "$$p"; then d= ; else d="$(srcdir)/"; fi; \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " $(INSTALL_DATA) $$d$$p $(DESTDIR)$(idldir)/$$f"; \
	  $(INSTALL_DATA) $$d$$p $(DESTDIR)$(idldir)/$$f; \
	done

uninstall-idlDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(idl_DATA)'; for p in $$list; do \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " rm -f $(DESTDIR)$(idldir)/$$f"; \
	  rm -f $(DESTDIR)$(idldir)/$$f; \
	done

install-kdelnkDATA: $(kdelnk_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(kdelnkdir)
	@list='$(kdelnk_DATA)'; for p in $$list; do \
	  if test -f "$$p"; then d= ; else d="$(srcdir)/"; fi; \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " $(INSTALL_DATA) $$d$$p $(DESTDIR)$(kdelnkdir)/$$f"; \
	  $(INSTALL_DATA) $$d$$p $(DESTDIR)$(kdelnkdir)/$$f; \
	done

uninstall-kdelnkDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(kdelnk_DATA)'; for p in $$list; do \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " rm -f $(DESTDIR)$(kdelnkdir)/$$f"; \
	  rm -f $(DESTDIR)$(kdelnkdir)/$$f; \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = katabase/kformviewer

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu katabase/kformviewer/Makefile
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done

DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)

-include $(DEP_FILES)

mostlyclean-depend:

clean-depend:

distclean-depend:
	-rm -rf .deps

maintainer-clean-depend:

%.o: %.cc
	@echo '$(CXXCOMPILE) -c $<'; \
	$(CXXCOMPILE) -Wp,-MD,.deps/$(*D)/$(*F).pp -c $<
	@-cp .deps/$(*D)/$(*F).pp .deps/$(*D)/$(*F).P; \
	tr ' ' '\012' < .deps/$(*D)/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*D)/$(*F).P; \
	rm .deps/$(*D)/$(*F).pp

%.lo: %.cc
	@echo '$(LTCXXCOMPILE) -c $<'; \
	$(LTCXXCOMPILE) -Wp,-MD,.deps/$(*D)/$(*F).pp -c $<
	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
	  < .deps/$(*D)/$(*F).pp > .deps/$(*D)/$(*F).P; \
	tr ' ' '\012' < .deps/$(*D)/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*D)/$(*F).P; \
	rm -f .deps/$(*D)/$(*F).pp
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-binPROGRAMS
install-exec: install-exec-am

install-data-am: install-idlDATA install-kdelnkDATA
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-binPROGRAMS uninstall-idlDATA \
		uninstall-kdelnkDATA
uninstall: uninstall-am
all-am: Makefile $(PROGRAMS) $(DATA) $(HEADERS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_STRIP_FLAG=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(bindir) $(DESTDIR)$(idldir) \
		$(DESTDIR)$(kdelnkdir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-binPROGRAMS mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags mostlyclean-depend \
		mostlyclean-generic

mostlyclean: mostlyclean-am

#>- clean-am:  clean-binPROGRAMS clean-compile clean-libtool clean-tags \
#>- 		clean-depend clean-generic mostlyclean-am
#>+ 2
clean-am: clean-metasources clean-idl clean-final   clean-binPROGRAMS clean-compile clean-libtool clean-tags \
		clean-depend clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-binPROGRAMS distclean-compile distclean-libtool \
		distclean-tags distclean-depend distclean-generic \
		clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-binPROGRAMS \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-depend \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-binPROGRAMS distclean-binPROGRAMS clean-binPROGRAMS \
maintainer-clean-binPROGRAMS uninstall-binPROGRAMS install-binPROGRAMS \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool uninstall-idlDATA \
install-idlDATA uninstall-kdelnkDATA install-kdelnkDATA tags \
mostlyclean-tags distclean-tags clean-tags maintainer-clean-tags \
distdir mostlyclean-depend distclean-depend clean-depend \
maintainer-clean-depend info-am info dvi-am dvi check check-am \
installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all install-strip installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


messages:
	(XGETTEXT) -C -ki18n -x $(includedir)/kde.pot *.cc && mv messages.po ../po/kformviewer.pot

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

#>+ 4
$(srcdir)/kformviewer_shell.cc: kformviewer_shell.moc
kformviewer_shell.moc: $(srcdir)/kformviewer_shell.h
	$(MOC) $(srcdir)/kformviewer_shell.h -o kformviewer_shell.moc

#>+ 4
$(srcdir)/kformviewer_view.cc: kformviewer_view.moc
kformviewer_view.moc: $(srcdir)/kformviewer_view.h
	$(MOC) $(srcdir)/kformviewer_view.h -o kformviewer_view.moc

#>+ 4
$(srcdir)/kformviewer_main.cc: kformviewer_main.moc
kformviewer_main.moc: $(srcdir)/kformviewer_main.h
	$(MOC) $(srcdir)/kformviewer_main.h -o kformviewer_main.moc

#>+ 4
$(srcdir)/kformviewer_doc.cc: kformviewer_doc.moc
kformviewer_doc.moc: $(srcdir)/kformviewer_doc.h
	$(MOC) $(srcdir)/kformviewer_doc.h -o kformviewer_doc.moc

#>+ 3
clean-metasources:
	-rm -f  kformviewer_shell.moc kformviewer_view.moc kformviewer_main.moc kformviewer_doc.moc

#>+ 4
kformviewer.h: $(srcdir)/kformviewer.idl $(micodir)/include/CORBA.h
	$(IDL) $(IDL_FLAGS) --c++-suffix cc $(srcdir)/kformviewer.idl
kformviewer.cc: kformviewer.h

#>+ 3
clean-idl:
	-rm -f kformviewer.cc kformviewer.h 

#>+ 5
force-reedit:
		cd $(top_srcdir) && $(AUTOMAKE) --gnu katabase/kformviewer/Makefile
	cd $(top_srcdir) && perl admin/am_edit katabase/kformviewer/Makefile.in


#>+ 11
kformviewer.all_cc.cc: $(srcdir)/Makefile.in $(srcdir)/kformviewer_main.cc $(srcdir)/kformviewer_shell.cc $(srcdir)/kformviewer_doc.cc $(srcdir)/kformviewer_view.cc $(srcdir)/kformviewer.cc  kformviewer_shell.moc kformviewer_view.moc kformviewer_main.moc kformviewer_doc.moc
	@echo 'creating kformviewer.all_cc.cc ...'; \
	rm -f kformviewer.all_cc.files kformviewer.all_cc.final; \
	echo "#define KDE_USE_FINAL 1" >> kformviewer.all_cc.final; \
	for file in kformviewer_main.cc kformviewer_shell.cc kformviewer_doc.cc kformviewer_view.cc kformviewer.cc ; do \
	  echo "#include \"$$file\"" >> kformviewer.all_cc.files; \
	  test ! -f $(srcdir)/$$file || egrep '^#pragma +implementation' $(srcdir)/$$file >> kformviewer.all_cc.final; \
	done; \
	cat kformviewer.all_cc.final kformviewer.all_cc.files  > kformviewer.all_cc.cc; \
	rm -f kformviewer.all_cc.final kformviewer.all_cc.files

#>+ 3
clean-final:
	-rm -f kformviewer.all_cc.cc

#>+ 2
final:
	$(MAKE) kformviewer_OBJECTS="$(kformviewer_final_OBJECTS)" all-am
#>+ 3
cvs-clean:
	$(MAKE) -f $(top_srcdir)/admin/Makefile.common cvs-clean
