# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/karchive': '@latest'
    'frameworks/kcodecs': '@latest'
    'frameworks/kcompletion': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kcrash': '@latest'
    'frameworks/kdbusaddons': '@latest'
    'frameworks/kdoctools': '@latest'
    'frameworks/kguiaddons': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kiconthemes': '@latest'
    'frameworks/kinit': '@latest'
    'frameworks/kitemviews': '@latest'
    'frameworks/kjobwidgets': '@latest'
    'frameworks/kcmutils': '@latest'
    'frameworks/kio': '@latest'
    'frameworks/knotifications': '@latest'
    'frameworks/knotifyconfig': '@latest'
    'frameworks/kparts': '@latest'
    'frameworks/sonnet': '@latest'
    'frameworks/ktextwidgets': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'frameworks/kxmlgui': '@latest'
    'frameworks/threadweaver': '@latest'
    'graphics/kdiagram': '@latest'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'plasma/plasma-activities': '@latest'
