/*
 *  kimageshop.idl - part of KImageShop
 *
 *  Copyright (c) 1999 Matthias Elter  <me@kde.org>
 *                1999 Michael Koch    <mkoch@kde.org>
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef __kimageshop_idl__
#define __kimageshop_idl__

#include <openparts.idl>
#include <koffice.idl>
#include <openparts_ui.idl>

module KImageShop
{
	struct MouseEvent_
	{
		long posX;
		long posY;
		long globalPosX;
		long globalPosY;
		boolean leftButton;
		boolean rightButton;
		boolean midButton;
		boolean shiftButton;
		boolean controlButton;
		boolean altButton;
	};
  	typedef MouseEvent_ MouseEvent;

	interface Tool
	{
		void optionsDialog();
		string toolName();

		void mousePress(in MouseEvent e); 
		void mouseMove(in MouseEvent e);
		void mouseRelease(in MouseEvent e);
	};

	interface View : KOffice::View
	{
		slot void slotActivateMoveTool();
		slot void slotActivateZoomTool();
		slot void slotActivateBrushTool();

                // edit menu
                slot void slotEditUndo();
                slot void slotEditUndo2();
                slot void slotEditUndo3();
                slot void slotEditUndo4();
                slot void slotEditUndo5();
                slot void slotEditUndo6();
                slot void slotEditUndo7();
                slot void slotEditUndo8();
                slot void slotEditUndo9();
                slot void slotEditUndo10();
                slot void slotEditRedo();
                slot void slotEditRedo2();
                slot void slotEditRedo3();
                slot void slotEditRedo4();
                slot void slotEditRedo5();
                slot void slotEditRedo6();
                slot void slotEditRedo7();
                slot void slotEditRedo8();
                slot void slotEditRedo9();
                slot void slotEditRedo10();

		slot void slotEditCopy();
		slot void slotEditCut();
		slot void slotEditPaste();

                // View menu
                slot void viewLayerDialog();
		slot void viewColorDialog();
                slot void viewPreferences();
	};

	interface Document : KOffice::Document, KOffice::Print
	{
	};
    
	interface DocumentFactory : KOffice::DocumentFactory
	{
	};
};

#endif

