/*
 *  kimageshop.idl - part of KImageShop
 *
 *  Copyright (c) 1999 Matthias Elter  <me@kde.org>
 *                1999 Michael Koch    <koch@kde.org>
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef __kimageshop_idl__
#define __kimageshop_idl__

#include <openparts.idl>
#include <koffice.idl>
#include <openparts_ui.idl>

module KImageShop
{
	struct MouseEvent_
	{
		long posX;
		long posY;
		long globalPosX;
		long globalPosY;
		boolean leftButton;
		boolean rightButton;
		boolean midButton;
		boolean shiftButton;
		boolean controlButton;
		boolean altButton;
	};
  	typedef MouseEvent_ MouseEvent;

	interface Tool
	{
		void optionsDialog();
		string toolName();

		void mousePress(in MouseEvent e); 
		void mouseMove(in MouseEvent e);
		void mouseRelease(in MouseEvent e);
	};

	interface View : KOffice::View
	{
		// tools toolbar
		slot void slotActivateMoveTool();
		slot void slotActivateZoomTool();
		slot void slotActivateBrushTool();
	
		slot void activatedUndoMenu( in long _id );
		slot void activatedRedoMenu( in long _id );

		// edit menu
		slot void slotEditUndo();
		slot void slotEditRedo();

		slot void slotEditCopy();
		slot void slotEditCut();
		slot void slotEditPaste();

		// View menu
		slot void slotLayerDialog();
		slot void slotColorDialog();
		slot void slotBrushDialog();
		slot void slotGradientDialog();
		slot void slotGradientEditorDialog();
		slot void slotPreferences();
	};

	interface Document : KOffice::Document, KOffice::Print
	{
	};
    
	interface DocumentFactory : KOffice::DocumentFactory
	{
	};
};

#endif

