# Generated automatically from Makefile.in by config.pl.
# KDE tags expanded automatically by am_edit - $Revision$ 
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ../..
VPATH = .
prefix = /home/kalle/kde-installation
exec_prefix = ${prefix}
#>- 
bindir = ${exec_prefix}/bin
#>+ 3
DEPDIR = .deps

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/koffice
pkglibdir = $(libdir)/koffice
pkgincludedir = $(includedir)/koffice

top_builddir = ../..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/ginstall -c -p
INSTALL_PROGRAM = ${INSTALL} $(INSTALL_STRIP_FLAG) $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux-gnu
build_triplet = i686-pc-linux-gnu
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_alias = i686-pc-linux-gnu
target_triplet = i686-pc-linux-gnu
ARTSCCONFIG = /home/kalle/kde-installation/bin/artsc-config
AS = @AS@
AUTODIRS = 
CC = gcc
CONF_FILES =  $(top_srcdir)/./admin/configure.in.min $(top_srcdir)/configure.in.in $(top_srcdir)/./example/configure.in.in $(top_srcdir)/./graphite/configure.in.in $(top_srcdir)/./kformula/configure.in.in $(top_srcdir)/./kimageshop/configure.in.in $(top_srcdir)/./kivio/configure.in.in $(top_srcdir)/./kspread/plugins/calculator/configure.in.in $(top_srcdir)/./lib/configure.in.in $(top_srcdir)/./lib/kformula/configure.in.in $(top_srcdir)/./plugins/configure.in.in
CPP = gcc -E
CXX = g++
CXXCPP = g++ -E
DCOPIDL = /home/kalle/kde-installation/bin/dcopidl
DCOPIDL2CPP = /home/kalle/kde-installation/bin/dcopidl2cpp
DCOP_DEPENDENCIES = $(DCOPIDL)
DLLTOOL = @DLLTOOL@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
EXEEXT = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = /usr/bin/msgfmt
IDL = @IDL@
IDL_DEPENDENCIES = @IDL_DEPENDENCIES@
JAR = @JAR@
JAVAC = @JAVAC@
JAVAH = @JAVAH@
JVMLIBS = @JVMLIBS@
KDECONFIG = /home/kalle/kde-installation/bin/kde-config
KDE_CXXFLAGS = 
KDE_EXTRA_RPATH = 
KDE_INCLUDES = -I/home/kalle/kde-installation/include
KDE_LDFLAGS = -L/home/kalle/kde-installation/lib
KDE_PLUGIN = -avoid-version -module -no-undefined $(KDE_RPATH)
KDE_RPATH = -R $(kde_libraries) -R $(qt_libraries) -R $(x_libraries)
KDE_USE_CLOSURE_FALSE = #
KDE_USE_CLOSURE_TRUE = 
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
KOFFICECORE_INCLUDES = -I$(top_srcdir)/lib/kofficecore -I$(top_builddir)/lib/kofficecore
KOFFICEUI_INCLUDES = -I$(top_srcdir)/lib/kofficeui -I$(top_builddir)/lib/kofficeui
KOFFICE_INCLUDES = $(KOFFICEUI_INCLUDES) $(KOFFICECORE_INCLUDES) $(KSTORE_INCLUDES) $(KWMF_INCLUDES)
KOFFICE_LIBS = $(LIB_KOFFICEUI) $(LIB_KOFFICECORE) $(LIB_KSTORE)
KSTORE_INCLUDES = -I$(top_srcdir)/lib/store -I$(top_builddir)/lib/store
KWMF_INCLUDES = -I$(top_srcdir)/lib/kwmf -I$(top_builddir)/lib/kwmf
LIBCOMPAT = 
LIBCRYPT = -lcrypt
LIBDL = -ldl
LIBJPEG = -ljpeg
LIBMICO = @LIBMICO@
LIBOBJS = @LIBOBJS@
LIBPNG = -lpng -lz -lm
LIBPTHREAD = -lpthread
LIBPYTHON = -lpython1.5 -lm -ldl 
LIBQIMGIO = @LIBQIMGIO@
LIBSM = -lSM -lICE
LIBSOCKET = 
LIBTIFF = -ltiff -ljpeg -lz
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBUCB = 
LIBXINERAMA = 
LIBZ = -lz
LIB_KAB = -lkab
LIB_KDECORE = -lkdecore
LIB_KDEPRINT = -lkdeprint
LIB_KDEUI = -lkdeui
LIB_KFILE = -lkfile
LIB_KFM = 
LIB_KFORMULA = -lkformula
LIB_KHTML = -lkhtml
LIB_KIMGIO = -lkimgio
LIB_KIO = -lkio
LIB_KOFFICECORE = $(top_builddir)/lib/kofficecore/libkofficecore.la
LIB_KOFFICEUI = $(top_builddir)/lib/kofficeui/libkofficeui.la
LIB_KPARTS = -lkparts
LIB_KSPELL = -lkspell
LIB_KSTORE = $(top_builddir)/lib/store/libkstore.la
LIB_KSYCOCA = -lksycoca
LIB_KWMF = $(top_builddir)/lib/kwmf/libkwmf.la
LIB_KWRITE = -lkwrite
LIB_QT = -lqt $(LIBPNG) $(LIBJPEG) -lXext $(LIB_X11) $(LIBSM)
LIB_SMB = -lsmb
LIB_X11 = -lX11 $(LIBSOCKET)
LN_S = ln -s
MAKEINFO = makeinfo
MCOPIDL = /home/kalle/kde-installation/bin/mcopidl
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = /home/kalle/qt-2.2.4/bin/moc
MSGFMT = /usr/bin/msgfmt
NOOPT_CXXFLAGS =  -fno-exceptions -fno-check-new
NOREPO = -fno-repo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = koffice
PAMINC = @PAMINC@
PAMLIBPATHS = @PAMLIBPATHS@
PAMLIBS = @PAMLIBS@
PYTHONINC = -I/usr/local/include/python1.5
PYTHONLIB = -L/usr/local/lib/python1.5/config
PYTHONMODDIR = /usr/local/lib/python1.5
QT_INCLUDES = -I/home/kalle/qt-2.2.4/include
QT_LDFLAGS = -L/home/kalle/qt-2.2.4/lib
RANLIB = ranlib
REPO = -frepo
SCANDIR = scan
STRIP = strip
TOPSUBDIRS =  doc kchart kformula killustrator kimageshop kivio koshell kpresenter kspread kugar kword pics plugins servicetypes templates tools
UIC = /home/kalle/qt-2.2.4/bin/uic
USER_INCLUDES = 
USER_LDFLAGS = 
USE_EXCEPTIONS = -fexceptions
USE_RTTI = -frtti
USE_THREADS = @USE_THREADS@
VERSION = 1.1-beta1
XGETTEXT = /usr/bin/xgettext
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS = 
X_INCLUDES = -I/usr/X11R6/include
X_LDFLAGS = -L/usr/X11R6/lib
X_PRE_LIBS = 
all_includes = -I/home/kalle/kde-installation/include -I/home/kalle/qt-2.2.4/include -I/usr/X11R6/include 
all_libraries = -L/usr/X11R6/lib -L/home/kalle/qt-2.2.4/lib -L/home/kalle/kde-installation/lib 
idldir = @idldir@
interfacedir = $(top_srcdir)/lib/interfaces
jni_includes = @jni_includes@
kde_appsdir = ${prefix}/share/applnk
kde_bindir = ${exec_prefix}/bin
kde_confdir = ${prefix}/share/config
kde_datadir = ${prefix}/share/apps
kde_htmldir = ${prefix}/share/doc/HTML
kde_icondir = ${prefix}/share/icons
kde_includes = /home/kalle/kde-installation/include
kde_libraries = /home/kalle/kde-installation/lib
kde_libs_htmldir = /home/kalle/kde-installation/share/doc/HTML
kde_libs_prefix = /home/kalle/kde-installation
kde_locale = ${prefix}/share/locale
kde_mimedir = ${prefix}/share/mimelnk
kde_moduledir = ${exec_prefix}/lib/kde2
kde_servicesdir = ${prefix}/share/services
kde_servicetypesdir = ${prefix}/share/servicetypes
kde_sounddir = ${prefix}/share/sounds
kde_templatesdir = ${prefix}/share/templates
kde_wallpaperdir = ${prefix}/share/wallpapers
micodir = @micodir@
qt_includes = /home/kalle/qt-2.2.4/include
qt_libraries = /home/kalle/qt-2.2.4/lib
x_includes = /usr/X11R6/include
x_libraries = /usr/X11R6/lib

lib_LIBRARIES = libkdchart.a

libkdchart_a_SOURCES = KDChartAreaPainter.cpp				KDChartAxesPainter.cpp				KDChartAxisParams.cpp				KDChartBarPainter.cpp				KDChart.cpp						KDChartHiLoPainter.cpp				KDChartLinesPainter.cpp				KDChartPainter.cpp					KDChartParams.cpp					KDChartPiePainter.cpp				KDChartRingPainter.cpp				KDChartTextPiece.cpp				KDChartWidget.cpp


noinst_HEADERS = KDChartAreaPainter.h				KDChartAxesPainter.h				KDChartBarPainter.h					KDChartHiLoPainter.h				KDChartLinesPainter.h				KDChartPiePainter.h					KDChartRingPainter.h				KDChartTextPiece.h				KDChartAxisParams.h				KDChartData.h					KDChartDataRegion.h				KDChart.h					KDChartNotEnoughSpaceException.h				KDChartPainter.h				KDChartParams.h					KDChartTable.h					KDChartUnknownTypeException.h				KDChartWidget.h


#>- METASOURCES = AUTO

INCLUDES = -I../include $(all_includes)
mkinstalldirs = $(SHELL) $(top_srcdir)/admin/mkinstalldirs
CONFIG_HEADER = ../../config.h
CONFIG_CLEAN_FILES = 
LIBRARIES =  $(lib_LIBRARIES)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I../..
CPPFLAGS = 
LDFLAGS = 
LIBS = 
libkdchart_a_LIBADD = 
#>- libkdchart_a_OBJECTS =  KDChartAreaPainter.$(OBJEXT) \
#>- KDChartAxesPainter.$(OBJEXT) KDChartAxisParams.$(OBJEXT) \
#>- KDChartBarPainter.$(OBJEXT) KDChart.$(OBJEXT) \
#>- KDChartHiLoPainter.$(OBJEXT) KDChartLinesPainter.$(OBJEXT) \
#>- KDChartPainter.$(OBJEXT) KDChartParams.$(OBJEXT) \
#>- KDChartPiePainter.$(OBJEXT) KDChartRingPainter.$(OBJEXT) \
#>- KDChartTextPiece.$(OBJEXT) KDChartWidget.$(OBJEXT)
#>+ 12
libkdchart_a_final_OBJECTS = libkdchart_a.all_cpp.o 
libkdchart_a_nofinal_OBJECTS = KDChartAreaPainter.$(OBJEXT) \
KDChartAxesPainter.$(OBJEXT) KDChartAxisParams.$(OBJEXT) \
KDChartBarPainter.$(OBJEXT) KDChart.$(OBJEXT) \
KDChartHiLoPainter.$(OBJEXT) KDChartLinesPainter.$(OBJEXT) \
KDChartPainter.$(OBJEXT) KDChartParams.$(OBJEXT) \
KDChartPiePainter.$(OBJEXT) KDChartRingPainter.$(OBJEXT) \
KDChartTextPiece.$(OBJEXT) KDChartWidget.$(OBJEXT)\
KDChartAxisParams.moc.o KDChartParams.moc.o KDChartWidget.moc.o  \
libkdchart_a_meta_unload.o 
libkdchart_a_OBJECTS = $(libkdchart_a_nofinal_OBJECTS)
#libkdchart_a_OBJECTS = $(libkdchart_a_final_OBJECTS)
AR = ar
CXXFLAGS = -O2 -fno-exceptions -fno-check-new -DQT_CLEAN_NAMESPACE -DQT_NO_COMPAT -DQT_NO_ASCII_CAST
#>- CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 1
CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
#>- LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 1
LTCXXCOMPILE = $(LIBTOOL) --mode=compile --tag=CXX $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
CXXLD = $(CXX)
#>- CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(LDFLAGS) -o $@
#>+ 1
CXXLINK = $(LIBTOOL) --mode=link --tag=CXX $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS) $(LDFLAGS) -o $@
HEADERS =  $(noinst_HEADERS)

DIST_COMMON =  Makefile.am Makefile.in


#>- DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)
#>+ 4
KDE_DIST=libkdchart_a_meta_unload.cpp KDChartData.cpp libkdchart.a 

DISTFILES= $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST) $(KDE_DIST)


TAR = tar
GZIP_ENV = --best
#>- DEP_FILES =  .deps/KDChart.P .deps/KDChartAreaPainter.P \
#>- .deps/KDChartAxesPainter.P .deps/KDChartAxisParams.P \
#>- .deps/KDChartBarPainter.P .deps/KDChartHiLoPainter.P \
#>- .deps/KDChartLinesPainter.P .deps/KDChartPainter.P \
#>- .deps/KDChartParams.P .deps/KDChartPiePainter.P \
#>- .deps/KDChartRingPainter.P .deps/KDChartTextPiece.P \
#>- .deps/KDChartWidget.P
#>+ 16
#DEP_FILES =  $(DEPDIR)/KDChartAxisParams.moc.P $(DEPDIR)/KDChartParams.moc.P $(DEPDIR)/KDChartWidget.moc.P $(DEPDIR)/libkdchart_a_meta_unload.P  $(DEPDIR)/libkdchart_a.all_cpp.P \
	  .deps/KDChart.P .deps/KDChartAreaPainter.P \
.deps/KDChartAxesPainter.P .deps/KDChartAxisParams.P \
.deps/KDChartBarPainter.P .deps/KDChartHiLoPainter.P \
.deps/KDChartLinesPainter.P .deps/KDChartPainter.P \
.deps/KDChartParams.P .deps/KDChartPiePainter.P \
.deps/KDChartRingPainter.P .deps/KDChartTextPiece.P \
.deps/KDChartWidget.P
DEP_FILES =  $(DEPDIR)/KDChartAxisParams.moc.P $(DEPDIR)/KDChartParams.moc.P $(DEPDIR)/KDChartWidget.moc.P $(DEPDIR)/libkdchart_a_meta_unload.P   .deps/KDChart.P .deps/KDChartAreaPainter.P \
.deps/KDChartAxesPainter.P .deps/KDChartAxisParams.P \
.deps/KDChartBarPainter.P .deps/KDChartHiLoPainter.P \
.deps/KDChartLinesPainter.P .deps/KDChartPainter.P \
.deps/KDChartParams.P .deps/KDChartPiePainter.P \
.deps/KDChartRingPainter.P .deps/KDChartTextPiece.P \
.deps/KDChartWidget.P

SOURCES = $(libkdchart_a_SOURCES)
OBJECTS = $(libkdchart_a_OBJECTS)

#>- all: all-redirect
#>+ 1
all: docs-am  all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .cpp .lo .o .obj .s
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
#>- 	cd $(top_srcdir) && $(AUTOMAKE) --gnu kchart/kdchart/Makefile
#>+ 2
	cd $(top_srcdir) && $(AUTOMAKE) --gnu kchart/kdchart/Makefile
	cd $(top_srcdir) && perl admin/am_edit kchart/kdchart/Makefile.in

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-libLIBRARIES:

clean-libLIBRARIES:
	-test -z "$(lib_LIBRARIES)" || rm -f $(lib_LIBRARIES)

distclean-libLIBRARIES:

maintainer-clean-libLIBRARIES:

install-libLIBRARIES: $(lib_LIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libdir)
	@list='$(lib_LIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(libdir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done
	@$(POST_INSTALL)
	@list='$(lib_LIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(RANLIB) $(DESTDIR)$(libdir)/$$p"; \
	    $(RANLIB) $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done

uninstall-libLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(lib_LIBRARIES)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(libdir)/$$p; \
	done

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libkdchart.a: $(libkdchart_a_OBJECTS) $(libkdchart_a_DEPENDENCIES)
	-rm -f libkdchart.a
	$(AR) cru libkdchart.a $(libkdchart_a_OBJECTS) $(libkdchart_a_LIBADD)
	$(RANLIB) libkdchart.a
.cpp.o:
	$(CXXCOMPILE) -c $<
.cpp.obj:
	$(CXXCOMPILE) -c `cygpath -w $<`
.cpp.lo:
	$(LTCXXCOMPILE) -c $<

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = kchart/kdchart

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu kchart/kdchart/Makefile
#>- 	@for file in $(DISTFILES); do \
#>- 	  d=$(srcdir); \
#>- 	  if test -d $$d/$$file; then \
#>- 	    cp -pr $$/$$file $(distdir)/$$file; \
#>- 	  else \
#>- 	    test -f $(distdir)/$$file \
#>- 	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
#>- 	    || cp -p $$d/$$file $(distdir)/$$file || :; \
#>- 	  fi; \
#>- 	done
#>+ 10
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done

DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)

-include $(DEP_FILES)

mostlyclean-depend:

clean-depend:

distclean-depend:
	-rm -rf .deps

maintainer-clean-depend:

%.o: %.c
	@echo '$(COMPILE) -c $<'; \
	$(COMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-cp .deps/$(*F).pp .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm .deps/$(*F).pp

%.lo: %.c
	@echo '$(LTCOMPILE) -c $<'; \
	$(LTCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
	  < .deps/$(*F).pp > .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm -f .deps/$(*F).pp

%.o: %.cpp
	@echo '$(CXXCOMPILE) -c $<'; \
	$(CXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-cp .deps/$(*F).pp .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm .deps/$(*F).pp

%.lo: %.cpp
	@echo '$(LTCXXCOMPILE) -c $<'; \
	$(LTCXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
	  < .deps/$(*F).pp > .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm -f .deps/$(*F).pp
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-libLIBRARIES
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-libLIBRARIES
uninstall: uninstall-am
all-am: Makefile $(LIBRARIES) $(HEADERS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(libdir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-libLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags mostlyclean-depend \
		mostlyclean-generic

mostlyclean: mostlyclean-am

#>- clean-am:  clean-libLIBRARIES clean-compile clean-libtool clean-tags \
#>- 		clean-depend clean-generic mostlyclean-am
#>+ 2
clean-am: clean-metasources clean-moc-classes clean-final   clean-libLIBRARIES clean-compile clean-libtool clean-tags \
		clean-depend clean-generic mostlyclean-am

#>- clean: clean-am
#>+ 1
clean: kde-rpo-clean  clean-am

distclean-am:  distclean-libLIBRARIES distclean-compile \
		distclean-libtool distclean-tags distclean-depend \
		distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-libLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-depend \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-libLIBRARIES distclean-libLIBRARIES \
clean-libLIBRARIES maintainer-clean-libLIBRARIES uninstall-libLIBRARIES \
install-libLIBRARIES mostlyclean-compile distclean-compile \
clean-compile maintainer-clean-compile mostlyclean-libtool \
distclean-libtool clean-libtool maintainer-clean-libtool tags \
mostlyclean-tags distclean-tags clean-tags maintainer-clean-tags \
distdir mostlyclean-depend distclean-depend clean-depend \
maintainer-clean-depend info-am info dvi-am dvi check check-am \
installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

#>+ 3
KDChartAxisParams.moc.cpp: $(srcdir)/KDChartAxisParams.h
	$(MOC) $(srcdir)/KDChartAxisParams.h -o KDChartAxisParams.moc.cpp

#>+ 3
KDChartParams.moc.cpp: $(srcdir)/KDChartParams.h
	$(MOC) $(srcdir)/KDChartParams.h -o KDChartParams.moc.cpp

#>+ 3
KDChartWidget.moc.cpp: $(srcdir)/KDChartWidget.h
	$(MOC) $(srcdir)/KDChartWidget.h -o KDChartWidget.moc.cpp

#>+ 3
clean-metasources:
	-rm -f  KDChartAxisParams.moc.cpp KDChartParams.moc.cpp KDChartWidget.moc.cpp

#>+ 2
docs-am:

#>+ 5
force-reedit:
		cd $(top_srcdir) && $(AUTOMAKE) --gnu kchart/kdchart/Makefile
	cd $(top_srcdir) && perl admin/am_edit kchart/kdchart/Makefile.in


#>+ 10
libkdchart_a_meta_unload.cpp:  KDChartAxisParams.moc.cpp KDChartParams.moc.cpp KDChartWidget.moc.cpp
	@echo 'creating libkdchart_a_meta_unload.cpp'
	@-rm -f libkdchart_a_meta_unload.cpp
	@echo 'static const char * _metalist_libkdchart_a[] = {' > libkdchart_a_meta_unload.cpp
	@cat  KDChartAxisParams.moc.cpp KDChartParams.moc.cpp KDChartWidget.moc.cpp | grep 'char.*className' | sed -e 's/.*[^A-Za-z0-9_:]\([A-Za-z0-9_:]*\)::className.*$$/\"\1\",/' | sort | uniq >> libkdchart_a_meta_unload.cpp
	@echo '0};' >> libkdchart_a_meta_unload.cpp
	@echo '#include <kunload.h>' >> libkdchart_a_meta_unload.cpp
	@echo '_UNLOAD(libkdchart_a)' >> libkdchart_a_meta_unload.cpp


#>+ 3
clean-moc-classes:
	-rm -f  libkdchart_a_meta_unload.cpp

#>+ 11
libkdchart_a.all_cpp.cpp: $(srcdir)/Makefile.in $(srcdir)/KDChartAreaPainter.cpp $(srcdir)/KDChartAxesPainter.cpp $(srcdir)/KDChartAxisParams.cpp $(srcdir)/KDChartBarPainter.cpp $(srcdir)/KDChart.cpp $(srcdir)/KDChartHiLoPainter.cpp $(srcdir)/KDChartLinesPainter.cpp $(srcdir)/KDChartPainter.cpp $(srcdir)/KDChartParams.cpp $(srcdir)/KDChartPiePainter.cpp $(srcdir)/KDChartRingPainter.cpp $(srcdir)/KDChartTextPiece.cpp $(srcdir)/KDChartWidget.cpp $(srcdir)/libkdchart_a_meta_unload.cpp  KDChartAxisParams.moc.cpp KDChartParams.moc.cpp KDChartWidget.moc.cpp
	@echo 'creating libkdchart_a.all_cpp.cpp ...'; \
	rm -f libkdchart_a.all_cpp.files libkdchart_a.all_cpp.final; \
	echo "#define KDE_USE_FINAL 1" >> libkdchart_a.all_cpp.final; \
	for file in KDChartAreaPainter.cpp KDChartAxesPainter.cpp KDChartAxisParams.cpp KDChartBarPainter.cpp KDChart.cpp KDChartHiLoPainter.cpp KDChartLinesPainter.cpp KDChartPainter.cpp KDChartParams.cpp KDChartPiePainter.cpp KDChartRingPainter.cpp KDChartTextPiece.cpp KDChartWidget.cpp libkdchart_a_meta_unload.cpp  KDChartAxisParams.moc.cpp KDChartParams.moc.cpp KDChartWidget.moc.cpp; do \
	  echo "#include \"$$file\"" >> libkdchart_a.all_cpp.files; \
	  test ! -f $(srcdir)/$$file || egrep '^#pragma +implementation' $(srcdir)/$$file >> libkdchart_a.all_cpp.final; \
	done; \
	cat libkdchart_a.all_cpp.final libkdchart_a.all_cpp.files  > libkdchart_a.all_cpp.cpp; \
	rm -f libkdchart_a.all_cpp.final libkdchart_a.all_cpp.files

#>+ 3
clean-final:
	-rm -f libkdchart_a.all_cpp.cpp

#>+ 2
final:
	$(MAKE) libkdchart_a_OBJECTS="$(libkdchart_a_final_OBJECTS)" all-am
#>+ 2
no-final:
	$(MAKE) libkdchart_a_OBJECTS="$(libkdchart_a_nofinal_OBJECTS)" all-am
#>+ 3
cvs-clean:
	$(MAKE) -f $(top_srcdir)/admin/Makefile.common cvs-clean

#>+ 3
kde-rpo-clean:
	-rm -f *.rpo
