#!/bin/sh

ird -ORBIIOPAddr inet:localhost:12345 &
ird_pid=$!
 
trap "kill $ird_pid" 0 

sleep 1
idl -ORBIfaceRepoAddr inet:localhost:12345 --feed-ir --feed-included-defs --no-codegen-c++ $1
ksidl2 -ORBIfaceRepoAddr inet:localhost:12345        
