#!/bin/bash

# sqltest_int - fast parser testing using sqlite database (interactive)
# Type sqltest_int for usage info.

[ $# -lt 1 ] && echo "Usage: $0 <sqlite-database-name> [-v] [other_options]" && \
 echo " -v    Verbose mode" && exit 1

dir=`dirname $0`
dbname=$1
shift

while true ; do
    echo -e "\n== Enter SQL Statement:"
    read
    if [ -z "$REPLY" ] ; then break; fi

    $dir/sqltest "$dbname" "$REPLY" $*
done
