#ifndef __img_idl__
#define __img_idl__

#include <parts.idl>

module KImage
{
	interface ImageView : OPParts::View
	{
		slot void toggleFitToWindow();
		slot void newView();
		slot void insertImage();
		slot void exportImage();
		slot void importImage();
	};

	interface ImageDocument : OPParts::Document
	{
		boolean import( in string filename );
		boolean export( in string filename, in string format );
	};

	interface Factory : OPParts::Factory
	{
	};
};

#endif