# Generated automatically from Makefile.in by configure.

INCDIR  =	-I$(QTDIR)/include -I$(KDEDIR)/include -I$(KDEDIR)/idl
CXXFLAGS =	$(INCDIR) -g -fexceptions -O0
LDFLAGS =       -L$(KDEDIR)/lib -L/usr/X11/lib -L/home/weis/qt-1.31/lib -lqt -lkdeui -lkdecore -lkfile -lkfm -lmico2.0.5 -lX11 -lXext -ldl -lkom -lop
CXX     =       g++
MOC     =       /usr/bin/moc

####### Files

SOURCES =	img_main.cc img_doc.cc img_view.cc img.cc img_shell.cc
HEADERS =	img_main.h img_doc.h img_view.h img.h img_shell.h
OBJECTS =	img_main.o img_doc.o img_view.o img.o img_shell.o
SRCMETA =	img_main.moc img_view.moc img_doc.moc img_shell.moc
TARGET	=	img
IDL	=	img.idl
IDLH	=	img.h

####### Install

INSTALL = install -m 0755 -s
INSTALL_SHELL = install -m 0755
INSTALL_DATA = install -m 0644
INSTALL_DIR = install -d -m 0755
INSTALL_DIR_PRIVATE = install -d -m 0700

####### Implicit rules

.SUFFIXES: .cc

.cc.o:
	$(CXX) -c $(CXXFLAGS) -DSTDC_HEADERS -DHAVE_UNISTD_H $(INCDIR) $<

%.moc: %.h
	$(MOC) $< -o $@      

####### Build rules

all: $(TARGET)

$(TARGET): $(SRCMETA) $(OBJECTS)
	$(CXX) $(OBJECTS) -o $(TARGET) $(LDFLAGS)

depend:
	@makedepend $(INCDIR) $(SOURCES) 2> /dev/null

showfiles:
	@echo $(SOURCES) $(HEADERS) Makefile

clean:
	-rm -f *.o *.bak *~ *% #*
	-rm -f $(SRCMETA) $(TARGET)

idl: img.idl
	idl --query-server-for-narrow -I$(KDEDIR)/idl img.idl

install:
	$(INSTALL_DIR) $(KDEDIR)/share/apps/koffice
	$(INSTALL_DIR) $(KDEDIR)/share/apps/koffice/partlnk
	$(INSTALL_DATA) kimage_part.kdelnk $(KDEDIR)/share/apps/koffice/partlnk/kimage.kdelnk
	$(INSTALL_DIR) $(KDEDIR)/idl
	$(INSTALL_DATA) img.idl $(KDEDIR)/idl/kimage.idl

####### Meta objects

# DO NOT DELETE THIS LINE -- make depend depends on it.

img_main.o: img_main.h /usr/local/kde/include/op_app.h
img_main.o: /usr/lib/qt/include/qapp.h /usr/lib/qt/include/qwidget.h
img_main.o: /usr/lib/qt/include/qwindefs.h /usr/lib/qt/include/qobjdefs.h
img_main.o: /usr/lib/qt/include/qglobal.h /usr/lib/qt/include/qobject.h
img_main.o: /usr/lib/qt/include/qstring.h /usr/lib/qt/include/qarray.h
img_main.o: /usr/lib/qt/include/qgarray.h /usr/lib/qt/include/qshared.h
img_main.o: /usr/lib/qt/include/qgeneric.h /usr/include/string.h
img_main.o: /usr/include/features.h /usr/include/sys/cdefs.h
img_main.o: /usr/include/gnu/stubs.h
img_main.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/stddef.h
img_main.o: /usr/lib/qt/include/qevent.h /usr/lib/qt/include/qrect.h
img_main.o: /usr/lib/qt/include/qsize.h /usr/lib/qt/include/qpoint.h
img_main.o: /usr/lib/qt/include/qpaintd.h /usr/lib/qt/include/qpalette.h
img_main.o: /usr/lib/qt/include/qcolor.h /usr/lib/qt/include/qcursor.h
img_main.o: /usr/lib/qt/include/qfont.h /usr/lib/qt/include/qfontmet.h
img_main.o: /usr/lib/qt/include/qfontinf.h /usr/local/kde/include/kom.h
img_main.o: /usr/local/kde/include/kom_app.h /usr/lib/qt/include/qsocknot.h
img_main.o: /usr/lib/qt/include/qtimer.h /usr/lib/qt/include/qlist.h
img_main.o: /usr/lib/qt/include/qglist.h /usr/lib/qt/include/qcollect.h
img_main.o: /usr/lib/qt/include/qintdict.h /usr/lib/qt/include/qgdict.h
img_main.o: /usr/local/kde/include/kapp.h /usr/local/kde/include/kconfig.h
img_main.o: /usr/local/kde/include/kconfigbase.h
img_main.o: /usr/lib/qt/include/qstrlist.h /usr/lib/qt/include/qdstream.h
img_main.o: /usr/lib/qt/include/qiodev.h /usr/local/kde/include/kconfigdata.h
img_main.o: /usr/lib/qt/include/qdict.h /usr/lib/qt/include/qtstream.h
img_main.o: /usr/include/stdio.h /usr/include/libio.h
img_main.o: /usr/include/_G_config.h /usr/include/gnu/types.h
img_main.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/stdarg.h
img_main.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/va-alpha.h
img_main.o: /usr/include/stdio_lim.h /usr/lib/qt/include/qfile.h
img_main.o: /usr/local/kde/include/kdebug.h /usr/local/kde/include/klocale.h
img_main.o: /usr/local/kde/include/drag.h /usr/lib/qt/include/qpixmap.h
img_main.o: /usr/include/X11/X.h /usr/lib/qt/include/qpopmenu.h
img_main.o: /usr/lib/qt/include/qtablevw.h /usr/lib/qt/include/qframe.h
img_main.o: /usr/lib/qt/include/qmenudta.h
img_main.o: /usr/local/kde/include/topwidget_impl.h
img_main.o: /usr/local/kde/include/controls.h /opt/kde/idl/kom.h
img_main.o: /usr/local/kde/include/component_impl.h
img_main.o: /usr/local/kde/include/base_impl.h
img_main.o: /usr/local/kde/include/kom_var.h
img_main.o: /usr/local/kde/include/control_frame.h
img_main.o: /usr/local/kde/include/control_impl.h
img_main.o: /usr/local/kde/include/kwm.h /usr/include/X11/Xlib.h
img_main.o: /usr/include/sys/types.h /usr/include/time.h
img_main.o: /usr/include/endian.h /usr/include/bytesex.h
img_main.o: /usr/include/sys/select.h /usr/include/selectbits.h
img_main.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
img_main.o: /usr/local/kde/include/part_impl.h /usr/local/kde/include/parts.h
img_main.o: /usr/local/kde/include/kmenubar.h /usr/lib/qt/include/qmenubar.h
img_main.o: /usr/local/kde/include/ktoolbar.h /usr/lib/qt/include/qbutton.h
img_main.o: /usr/local/kde/include/kcombo.h /usr/lib/qt/include/qcombo.h
img_main.o: /usr/local/kde/include/klined.h /usr/lib/qt/include/qlined.h
img_main.o: /usr/local/kde/include/part_shell_impl.h
img_main.o: /usr/local/kde/include/ktopwidget.h /usr/include/stdlib.h
img_main.o: /usr/include/alloca.h /usr/local/kde/include/kstatusbar.h
img_main.o: /usr/lib/qt/include/qlabel.h
img_main.o: /usr/local/kde/include/toolbar_impl.h
img_main.o: /usr/lib/qt/include/qpushbt.h /usr/local/kde/include/menu_impl.h
img_main.o: img_doc.h /usr/local/kde/include/document_impl.h
img_main.o: /usr/local/kde/include/view_impl.h img_view.h
img_main.o: /usr/local/kde/include/part_frame_impl.h img.h
img_main.o: /opt/kde/idl/controls.h /opt/kde/idl/parts.h
img_main.o: /usr/lib/qt/include/qimage.h img_shell.h
img_main.o: /usr/local/kde/include/default_shell_impl.h
img_main.o: /usr/local/kde/include/default_shell.h
img_main.o: /usr/local/kde/include/factory_impl.h
img_doc.o: img_doc.h /usr/local/kde/include/document_impl.h
img_doc.o: /usr/local/kde/include/parts.h /opt/kde/idl/kom.h
img_doc.o: /usr/local/kde/include/controls.h
img_doc.o: /usr/local/kde/include/component_impl.h
img_doc.o: /usr/local/kde/include/kom.h /usr/local/kde/include/base_impl.h
img_doc.o: /usr/lib/qt/include/qstring.h /usr/lib/qt/include/qarray.h
img_doc.o: /usr/lib/qt/include/qgarray.h /usr/lib/qt/include/qshared.h
img_doc.o: /usr/lib/qt/include/qglobal.h /usr/lib/qt/include/qgeneric.h
img_doc.o: /usr/include/string.h /usr/include/features.h
img_doc.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
img_doc.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/stddef.h
img_doc.o: /usr/lib/qt/include/qlist.h /usr/lib/qt/include/qglist.h
img_doc.o: /usr/lib/qt/include/qcollect.h /usr/lib/qt/include/qdict.h
img_doc.o: /usr/lib/qt/include/qgdict.h /usr/local/kde/include/kom_var.h
img_doc.o: /usr/local/kde/include/view_impl.h
img_doc.o: /usr/local/kde/include/part_impl.h
img_doc.o: /usr/local/kde/include/control_impl.h img_view.h
img_doc.o: /usr/local/kde/include/part_frame_impl.h
img_doc.o: /usr/local/kde/include/control_frame.h
img_doc.o: /usr/lib/qt/include/qwidget.h /usr/lib/qt/include/qwindefs.h
img_doc.o: /usr/lib/qt/include/qobjdefs.h /usr/lib/qt/include/qobject.h
img_doc.o: /usr/lib/qt/include/qevent.h /usr/lib/qt/include/qrect.h
img_doc.o: /usr/lib/qt/include/qsize.h /usr/lib/qt/include/qpoint.h
img_doc.o: /usr/lib/qt/include/qpaintd.h /usr/lib/qt/include/qpalette.h
img_doc.o: /usr/lib/qt/include/qcolor.h /usr/lib/qt/include/qcursor.h
img_doc.o: /usr/lib/qt/include/qfont.h /usr/lib/qt/include/qfontmet.h
img_doc.o: /usr/lib/qt/include/qfontinf.h /usr/local/kde/include/kwm.h
img_doc.o: /usr/lib/qt/include/qapp.h /usr/lib/qt/include/qpixmap.h
img_doc.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
img_doc.o: /usr/include/gnu/types.h /usr/include/time.h /usr/include/endian.h
img_doc.o: /usr/include/bytesex.h /usr/include/sys/select.h
img_doc.o: /usr/include/selectbits.h /usr/include/X11/X.h
img_doc.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
img_doc.o: /usr/local/kde/include/kapp.h /usr/local/kde/include/kconfig.h
img_doc.o: /usr/local/kde/include/kconfigbase.h
img_doc.o: /usr/lib/qt/include/qstrlist.h /usr/lib/qt/include/qdstream.h
img_doc.o: /usr/lib/qt/include/qiodev.h /usr/local/kde/include/kconfigdata.h
img_doc.o: /usr/lib/qt/include/qtstream.h /usr/include/stdio.h
img_doc.o: /usr/include/libio.h /usr/include/_G_config.h
img_doc.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/stdarg.h
img_doc.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/va-alpha.h
img_doc.o: /usr/include/stdio_lim.h /usr/lib/qt/include/qfile.h
img_doc.o: /usr/local/kde/include/kdebug.h /usr/local/kde/include/klocale.h
img_doc.o: /usr/lib/qt/include/qintdict.h /usr/local/kde/include/drag.h
img_doc.o: /usr/lib/qt/include/qpopmenu.h /usr/lib/qt/include/qtablevw.h
img_doc.o: /usr/lib/qt/include/qframe.h /usr/lib/qt/include/qmenudta.h
img_doc.o: /usr/local/kde/include/menu_impl.h
img_doc.o: /usr/local/kde/include/kmenubar.h /usr/lib/qt/include/qmenubar.h
img_doc.o: /usr/local/kde/include/ktopwidget.h /usr/include/stdlib.h
img_doc.o: /usr/include/alloca.h /usr/local/kde/include/ktoolbar.h
img_doc.o: /usr/lib/qt/include/qbutton.h /usr/local/kde/include/kcombo.h
img_doc.o: /usr/lib/qt/include/qcombo.h /usr/local/kde/include/klined.h
img_doc.o: /usr/lib/qt/include/qlined.h /usr/local/kde/include/kstatusbar.h
img_doc.o: /usr/lib/qt/include/qlabel.h /usr/local/kde/include/toolbar_impl.h
img_doc.o: /usr/lib/qt/include/qpushbt.h img.h /opt/kde/idl/controls.h
img_doc.o: /opt/kde/idl/parts.h /usr/lib/qt/include/qimage.h
img_view.o: /usr/local/kde/include/kfiledialog.h
img_view.o: /usr/lib/qt/include/qdialog.h /usr/lib/qt/include/qwidget.h
img_view.o: /usr/lib/qt/include/qwindefs.h /usr/lib/qt/include/qobjdefs.h
img_view.o: /usr/lib/qt/include/qglobal.h /usr/lib/qt/include/qobject.h
img_view.o: /usr/lib/qt/include/qstring.h /usr/lib/qt/include/qarray.h
img_view.o: /usr/lib/qt/include/qgarray.h /usr/lib/qt/include/qshared.h
img_view.o: /usr/lib/qt/include/qgeneric.h /usr/include/string.h
img_view.o: /usr/include/features.h /usr/include/sys/cdefs.h
img_view.o: /usr/include/gnu/stubs.h
img_view.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/stddef.h
img_view.o: /usr/lib/qt/include/qevent.h /usr/lib/qt/include/qrect.h
img_view.o: /usr/lib/qt/include/qsize.h /usr/lib/qt/include/qpoint.h
img_view.o: /usr/lib/qt/include/qpaintd.h /usr/lib/qt/include/qpalette.h
img_view.o: /usr/lib/qt/include/qcolor.h /usr/lib/qt/include/qcursor.h
img_view.o: /usr/lib/qt/include/qfont.h /usr/lib/qt/include/qfontmet.h
img_view.o: /usr/lib/qt/include/qfontinf.h /usr/lib/qt/include/qstack.h
img_view.o: /usr/lib/qt/include/qglist.h /usr/lib/qt/include/qcollect.h
img_view.o: /usr/lib/qt/include/qstrlist.h /usr/lib/qt/include/qlist.h
img_view.o: /usr/lib/qt/include/qdstream.h /usr/lib/qt/include/qiodev.h
img_view.o: /usr/lib/qt/include/qpixmap.h /usr/local/kde/include/kfileinfo.h
img_view.o: /usr/lib/qt/include/qdatetm.h /usr/include/time.h
img_view.o: /usr/include/gnu/types.h img_view.h
img_view.o: /usr/local/kde/include/view_impl.h /usr/local/kde/include/parts.h
img_view.o: /opt/kde/idl/kom.h /usr/local/kde/include/controls.h
img_view.o: /usr/local/kde/include/part_impl.h
img_view.o: /usr/local/kde/include/control_impl.h
img_view.o: /usr/local/kde/include/component_impl.h
img_view.o: /usr/local/kde/include/kom.h /usr/local/kde/include/base_impl.h
img_view.o: /usr/lib/qt/include/qdict.h /usr/lib/qt/include/qgdict.h
img_view.o: /usr/local/kde/include/kom_var.h
img_view.o: /usr/local/kde/include/document_impl.h
img_view.o: /usr/local/kde/include/part_frame_impl.h
img_view.o: /usr/local/kde/include/control_frame.h
img_view.o: /usr/local/kde/include/kwm.h /usr/lib/qt/include/qapp.h
img_view.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
img_view.o: /usr/include/endian.h /usr/include/bytesex.h
img_view.o: /usr/include/sys/select.h /usr/include/selectbits.h
img_view.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
img_view.o: /usr/include/X11/Xosdefs.h /usr/local/kde/include/kapp.h
img_view.o: /usr/local/kde/include/kconfig.h
img_view.o: /usr/local/kde/include/kconfigbase.h
img_view.o: /usr/local/kde/include/kconfigdata.h
img_view.o: /usr/lib/qt/include/qtstream.h /usr/include/stdio.h
img_view.o: /usr/include/libio.h /usr/include/_G_config.h
img_view.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/stdarg.h
img_view.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/va-alpha.h
img_view.o: /usr/include/stdio_lim.h /usr/lib/qt/include/qfile.h
img_view.o: /usr/local/kde/include/kdebug.h /usr/local/kde/include/klocale.h
img_view.o: /usr/lib/qt/include/qintdict.h /usr/local/kde/include/drag.h
img_view.o: /usr/lib/qt/include/qpopmenu.h /usr/lib/qt/include/qtablevw.h
img_view.o: /usr/lib/qt/include/qframe.h /usr/lib/qt/include/qmenudta.h
img_view.o: /usr/local/kde/include/menu_impl.h
img_view.o: /usr/local/kde/include/kmenubar.h /usr/lib/qt/include/qmenubar.h
img_view.o: /usr/local/kde/include/ktopwidget.h /usr/include/stdlib.h
img_view.o: /usr/include/alloca.h /usr/local/kde/include/ktoolbar.h
img_view.o: /usr/lib/qt/include/qbutton.h /usr/local/kde/include/kcombo.h
img_view.o: /usr/lib/qt/include/qcombo.h /usr/local/kde/include/klined.h
img_view.o: /usr/lib/qt/include/qlined.h /usr/local/kde/include/kstatusbar.h
img_view.o: /usr/lib/qt/include/qlabel.h
img_view.o: /usr/local/kde/include/toolbar_impl.h
img_view.o: /usr/lib/qt/include/qpushbt.h img.h /opt/kde/idl/controls.h
img_view.o: /opt/kde/idl/parts.h img_doc.h /usr/lib/qt/include/qimage.h
img_view.o: img_main.h /usr/local/kde/include/op_app.h
img_view.o: /usr/local/kde/include/kom_app.h /usr/lib/qt/include/qsocknot.h
img_view.o: /usr/lib/qt/include/qtimer.h
img_view.o: /usr/local/kde/include/topwidget_impl.h
img_view.o: /usr/local/kde/include/part_shell_impl.h img_shell.h
img_view.o: /usr/local/kde/include/default_shell_impl.h
img_view.o: /usr/local/kde/include/default_shell.h
img_view.o: /usr/local/kde/include/utils.h /usr/lib/qt/include/qpainter.h
img_view.o: /usr/lib/qt/include/qregion.h /usr/lib/qt/include/qpen.h
img_view.o: /usr/lib/qt/include/qbrush.h /usr/lib/qt/include/qpntarry.h
img_view.o: /usr/lib/qt/include/qwmatrix.h /usr/lib/qt/include/qmsgbox.h
img_view.o: /usr/lib/qt/include/qkeycode.h
img.o: img.h /opt/kde/idl/kom.h /opt/kde/idl/controls.h /opt/kde/idl/parts.h
img_shell.o: img_shell.h img.h /opt/kde/idl/kom.h /opt/kde/idl/controls.h
img_shell.o: /opt/kde/idl/parts.h img_doc.h
img_shell.o: /usr/local/kde/include/document_impl.h
img_shell.o: /usr/local/kde/include/parts.h /usr/local/kde/include/controls.h
img_shell.o: /usr/local/kde/include/component_impl.h
img_shell.o: /usr/local/kde/include/kom.h /usr/local/kde/include/base_impl.h
img_shell.o: /usr/lib/qt/include/qstring.h /usr/lib/qt/include/qarray.h
img_shell.o: /usr/lib/qt/include/qgarray.h /usr/lib/qt/include/qshared.h
img_shell.o: /usr/lib/qt/include/qglobal.h /usr/lib/qt/include/qgeneric.h
img_shell.o: /usr/include/string.h /usr/include/features.h
img_shell.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
img_shell.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/stddef.h
img_shell.o: /usr/lib/qt/include/qlist.h /usr/lib/qt/include/qglist.h
img_shell.o: /usr/lib/qt/include/qcollect.h /usr/lib/qt/include/qdict.h
img_shell.o: /usr/lib/qt/include/qgdict.h /usr/local/kde/include/kom_var.h
img_shell.o: /usr/local/kde/include/view_impl.h
img_shell.o: /usr/local/kde/include/part_impl.h
img_shell.o: /usr/local/kde/include/control_impl.h img_view.h
img_shell.o: /usr/local/kde/include/part_frame_impl.h
img_shell.o: /usr/local/kde/include/control_frame.h
img_shell.o: /usr/lib/qt/include/qwidget.h /usr/lib/qt/include/qwindefs.h
img_shell.o: /usr/lib/qt/include/qobjdefs.h /usr/lib/qt/include/qobject.h
img_shell.o: /usr/lib/qt/include/qevent.h /usr/lib/qt/include/qrect.h
img_shell.o: /usr/lib/qt/include/qsize.h /usr/lib/qt/include/qpoint.h
img_shell.o: /usr/lib/qt/include/qpaintd.h /usr/lib/qt/include/qpalette.h
img_shell.o: /usr/lib/qt/include/qcolor.h /usr/lib/qt/include/qcursor.h
img_shell.o: /usr/lib/qt/include/qfont.h /usr/lib/qt/include/qfontmet.h
img_shell.o: /usr/lib/qt/include/qfontinf.h /usr/local/kde/include/kwm.h
img_shell.o: /usr/lib/qt/include/qapp.h /usr/lib/qt/include/qpixmap.h
img_shell.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
img_shell.o: /usr/include/gnu/types.h /usr/include/time.h
img_shell.o: /usr/include/endian.h /usr/include/bytesex.h
img_shell.o: /usr/include/sys/select.h /usr/include/selectbits.h
img_shell.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
img_shell.o: /usr/include/X11/Xosdefs.h /usr/local/kde/include/kapp.h
img_shell.o: /usr/local/kde/include/kconfig.h
img_shell.o: /usr/local/kde/include/kconfigbase.h
img_shell.o: /usr/lib/qt/include/qstrlist.h /usr/lib/qt/include/qdstream.h
img_shell.o: /usr/lib/qt/include/qiodev.h
img_shell.o: /usr/local/kde/include/kconfigdata.h
img_shell.o: /usr/lib/qt/include/qtstream.h /usr/include/stdio.h
img_shell.o: /usr/include/libio.h /usr/include/_G_config.h
img_shell.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/stdarg.h
img_shell.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/va-alpha.h
img_shell.o: /usr/include/stdio_lim.h /usr/lib/qt/include/qfile.h
img_shell.o: /usr/local/kde/include/kdebug.h /usr/local/kde/include/klocale.h
img_shell.o: /usr/lib/qt/include/qintdict.h /usr/local/kde/include/drag.h
img_shell.o: /usr/lib/qt/include/qpopmenu.h /usr/lib/qt/include/qtablevw.h
img_shell.o: /usr/lib/qt/include/qframe.h /usr/lib/qt/include/qmenudta.h
img_shell.o: /usr/local/kde/include/menu_impl.h
img_shell.o: /usr/local/kde/include/kmenubar.h /usr/lib/qt/include/qmenubar.h
img_shell.o: /usr/local/kde/include/ktopwidget.h /usr/include/stdlib.h
img_shell.o: /usr/include/alloca.h /usr/local/kde/include/ktoolbar.h
img_shell.o: /usr/lib/qt/include/qbutton.h /usr/local/kde/include/kcombo.h
img_shell.o: /usr/lib/qt/include/qcombo.h /usr/local/kde/include/klined.h
img_shell.o: /usr/lib/qt/include/qlined.h /usr/local/kde/include/kstatusbar.h
img_shell.o: /usr/lib/qt/include/qlabel.h
img_shell.o: /usr/local/kde/include/toolbar_impl.h
img_shell.o: /usr/lib/qt/include/qpushbt.h /usr/lib/qt/include/qimage.h
img_shell.o: /usr/local/kde/include/default_shell_impl.h
img_shell.o: /usr/local/kde/include/default_shell.h
img_shell.o: /usr/local/kde/include/part_shell_impl.h
img_shell.o: /usr/local/kde/include/topwidget_impl.h
