/* This file is part of the KDE project
   Copyright (C) 1999 Werner Trobin <wtrobin@carinthia.com>

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public
   License as published by the Free Software Foundation; either
   version 2 of the License, or (at your option) any later version.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public License
   along with this library; see the file COPYING.LIB.  If not, write to
   the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.
*/

#include <powerpointfilter.h>
#include <powerpointfilter.moc>

const QString PowerPointFilter::part() {
    
    return  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            "<DOC author=\"Reginald Stadlbauer\" email=\"reggie@kde.org\" editor=\"KPresenter\" mime=\"application/x-kpresenter\" url=\"/home/koffice/sorry.kpr\">\n"
            "<PAPER format=\"5\" ptWidth=\"680\" ptHeight=\"510\" mmWidth =\"240\" mmHeight=\"180\" inchWidth =\"9.44882\" inchHeight=\"7.08661\" orientation=\"0\" unit=\"0\">\n"
            "<PAPERBORDERS mmLeft=\"0\" mmTop=\"0\" mmRight=\"0\" mmBottom=\"0\" ptLeft=\"0\" ptTop=\"0\" ptRight=\"0\" ptBottom=\"0\" inchLeft=\"0\" inchTop=\"0\" inchRight=\"0\" inchBottom=\"0\"/>\n"
            "</PAPER>\n"
            "<BACKGROUND rastX=\"10\" rastY=\"10\" bred=\"255\" bgreen=\"255\" bblue=\"255\">\n"
            "<PAGE>\n"
            "<BACKTYPE value=\"0\"/>\n"
            "<BACKVIEW value=\"1\"/>\n"
            "<BACKCOLOR1 red=\"255\" green=\"255\" blue=\"255\"/>\n"
            "<BACKCOLOR2 red=\"255\" green=\"255\" blue=\"255\"/>\n"
            "<BCTYPE value=\"0\"/>\n"
            "<BGRADIENT unbalanced=\"0\" xfactor=\"100\" yfactor=\"100\"/>\n"
            "<PGEFFECT value=\"0\"/>\n"
            "</PAGE>\n"
            "</BACKGROUND>\n"
            "<HEADER show=\"0\">\n"
            "<ORIG x=\"0\" y=\"0\"/>\n"
            "<SIZE width=\"-1\" height=\"-1\"/>\n"
            "<SHADOW distance=\"0\" direction=\"5\" red=\"160\" green=\"160\" blue=\"164\"/>\n"
            "<EFFECTS effect=\"0\" effect2=\"0\"/>\n"
            "<PRESNUM value=\"0\"/>\n"
            "<ANGLE value=\"0\"/>\n"
            "<FILLTYPE value=\"0\"/>\n"
            "<GRADIENT red1=\"255\" green1=\"0\" blue1=\"0\" red2=\"0\" green2=\"255\" blue2=\"0\" type=\"1\" unbalanced=\"0\" xfactor=\"100\" xfactor=\"100\"/>\n"
            "<PEN red=\"0\" green=\"0\" blue=\"0\" width=\"1\" style=\"0\"/>\n"
            "<BRUSH red=\"0\" green=\"0\" blue=\"0\" style=\"0\"/>\n"
            "<DISAPPEAR effect=\"0\" doit=\"0\" num=\"1\"/>\n"
            "<TEXTOBJ objType=\"0\">\n"
            "<ENUMLISTTYPE type=\"1\" before=\"\" after=\".\" start=\"1\" family=\"times\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"0\" green=\"0\" blue=\"0\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"helvetica\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"helvetica\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"helvetica\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"helvetica\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"helvetica\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"helvetica\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"helvetica\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"helvetica\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<PARAGRAPH horzAlign=\"0\" depth=\"0\" lineSpacing=\"0\" distBefore=\"0\" distAfter=\"0\">\n"
            "<LINE>\n"
            "<OBJ>\n"
            "<TYPE value=\"1\"/>\n"
            "<FONT family=\"utopia\" pointSize=\"20\" bold=\"1\" italic=\"0\" underline=\"0\"/>\n"
            "<COLOR red=\"255\" green=\"0\" blue=\"0\"/>\n"
            "<VERTALIGN value=\"1\"/>\n"
            "<TEXT> </TEXT>\n"
            "</OBJ>\n"
            "</LINE>\n"
            "</PARAGRAPH>\n"
            "</TEXTOBJ>\n"
            "</HEADER>\n"
            "<FOOTER show=\"0\">\n"
            "<ORIG x=\"0\" y=\"0\"/>\n"
            "<SIZE width=\"-1\" height=\"-1\"/>\n"
            "<SHADOW distance=\"0\" direction=\"5\" red=\"160\" green=\"160\" blue=\"164\"/>\n"
            "<EFFECTS effect=\"0\" effect2=\"0\"/>\n"
            "<PRESNUM value=\"0\"/>\n"
            "<ANGLE value=\"0\"/>\n"
            "<FILLTYPE value=\"0\"/>\n"
            "<GRADIENT red1=\"255\" green1=\"0\" blue1=\"0\" red2=\"0\" green2=\"255\" blue2=\"0\" type=\"1\" unbalanced=\"0\" xfactor=\"100\" xfactor=\"100\"/>\n"
            "<PEN red=\"0\" green=\"0\" blue=\"0\" width=\"1\" style=\"0\"/>\n"
            "<BRUSH red=\"0\" green=\"0\" blue=\"0\" style=\"0\"/>\n"
            "<DISAPPEAR effect=\"0\" doit=\"0\" num=\"1\"/>\n"
            "<TEXTOBJ objType=\"0\">\n"
            "<ENUMLISTTYPE type=\"1\" before=\"\" after=\".\" start=\"1\" family=\"times\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"0\" green=\"0\" blue=\"0\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"helvetica\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"helvetica\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"helvetica\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"helvetica\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"helvetica\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"helvetica\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"helvetica\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"helvetica\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<PARAGRAPH horzAlign=\"0\" depth=\"0\" lineSpacing=\"0\" distBefore=\"0\" distAfter=\"0\">\n"
            "<LINE>\n"
            "<OBJ>\n"
            "<TYPE value=\"1\"/>\n"
            "<FONT family=\"utopia\" pointSize=\"20\" bold=\"1\" italic=\"0\" underline=\"0\"/>\n"
            "<COLOR red=\"255\" green=\"0\" blue=\"0\"/>\n"
            "<VERTALIGN value=\"1\"/>\n"
            "<TEXT> </TEXT>\n"
            "</OBJ>\n"
            "</LINE>\n"
            "</PARAGRAPH>\n"
            "</TEXTOBJ>\n"
            "</FOOTER>\n"
            "<OBJECTS>\n"
            "<OBJECT type=\"4\">\n"
            "<ORIG x=\"30\" y=\"30\"/>\n"
            "<SIZE width=\"611\" height=\"61\"/>\n"
            "<SHADOW distance=\"0\" direction=\"5\" red=\"160\" green=\"160\" blue=\"164\"/>\n"
            "<EFFECTS effect=\"0\" effect2=\"0\"/>\n"
            "<PRESNUM value=\"0\"/>\n"
            "<ANGLE value=\"0\"/>\n"
            "<FILLTYPE value=\"0\"/>\n"
            "<GRADIENT red1=\"255\" green1=\"0\" blue1=\"0\" red2=\"0\" green2=\"255\" blue2=\"0\" type=\"1\" unbalanced=\"0\" xfactor=\"100\" xfactor=\"100\"/>\n"
            "<PEN red=\"0\" green=\"0\" blue=\"0\" width=\"1\" style=\"0\"/>\n"
            "<BRUSH red=\"0\" green=\"0\" blue=\"0\" style=\"0\"/>\n"
            "<DISAPPEAR effect=\"0\" doit=\"0\" num=\"1\"/>\n"
            "<TEXTOBJ objType=\"0\">\n"
            "<ENUMLISTTYPE type=\"1\" before=\"\" after=\".\" start=\"1\" family=\"times\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"0\" green=\"0\" blue=\"0\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<PARAGRAPH horzAlign=\"1\" depth=\"0\" lineSpacing=\"0\" distBefore=\"0\" distAfter=\"0\">\n"
            "<LINE>\n"
            "<OBJ>\n"
            "<TYPE value=\"0\"/>\n"
            "<FONT family=\"utopia\" pointSize=\"48\" bold=\"1\" italic=\"0\" underline=\"0\"/>\n"
            "<COLOR red=\"0\" green=\"0\" blue=\"0\"/>\n"
            "<VERTALIGN value=\"1\"/>\n"
            "<TEXT>Sorry</TEXT>\n"
            "</OBJ>\n"
            "<OBJ>\n"
            "<TYPE value=\"1\"/>\n"
            "<FONT family=\"utopia\" pointSize=\"48\" bold=\"1\" italic=\"0\" underline=\"0\"/>\n"
            "<COLOR red=\"0\" green=\"0\" blue=\"0\"/>\n"
            "<VERTALIGN value=\"1\"/>\n"
            "<TEXT> </TEXT>\n"
            "</OBJ>\n"
            "<OBJ>\n"
            "<TYPE value=\"0\"/>\n"
            "<FONT family=\"utopia\" pointSize=\"48\" bold=\"1\" italic=\"0\" underline=\"0\"/>\n"
            "<COLOR red=\"0\" green=\"0\" blue=\"0\"/>\n"
            "<VERTALIGN value=\"1\"/>\n"
            "<TEXT>:(</TEXT>\n"
            "</OBJ>\n"
            "<OBJ>\n"
            "<TYPE value=\"1\"/>\n"
            "<FONT family=\"utopia\" pointSize=\"48\" bold=\"1\" italic=\"0\" underline=\"0\"/>\n"
            "<COLOR red=\"0\" green=\"0\" blue=\"0\"/>\n"
            "<VERTALIGN value=\"1\"/>\n"
            "<TEXT> </TEXT>\n"
            "</OBJ>\n"
            "</LINE>\n"
            "</PARAGRAPH>\n"
            "</TEXTOBJ>\n"
            "</OBJECT>\n"
            "<OBJECT type=\"4\">\n"
            "<ORIG x=\"30\" y=\"130\"/>\n"
            "<SIZE width=\"611\" height=\"341\"/>\n"
            "<SHADOW distance=\"0\" direction=\"5\" red=\"160\" green=\"160\" blue=\"164\"/>\n"
            "<EFFECTS effect=\"0\" effect2=\"0\"/>\n"
            "<PRESNUM value=\"0\"/>\n"
            "<ANGLE value=\"0\"/>\n"
            "<FILLTYPE value=\"0\"/>\n"
            "<GRADIENT red1=\"255\" green1=\"0\" blue1=\"0\" red2=\"0\" green2=\"255\" blue2=\"0\" type=\"1\" unbalanced=\"0\" xfactor=\"100\" xfactor=\"100\"/>\n"
            "<PEN red=\"0\" green=\"0\" blue=\"0\" width=\"1\" style=\"0\"/>\n"
            "<BRUSH red=\"0\" green=\"0\" blue=\"0\" style=\"0\"/>\n"
            "<DISAPPEAR effect=\"0\" doit=\"0\" num=\"1\"/>\n"
            "<TEXTOBJ objType=\"2\">\n"
            "<ENUMLISTTYPE type=\"1\" before=\"\" after=\".\" start=\"1\" family=\"times\" pointSize=\"12\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"0\" green=\"0\" blue=\"0\"/>\n"
            "<UNSORTEDLISTTYPE family=\"utopia\" pointSize=\"20\" bold=\"1\" italic=\"0\" underline=\"0\" red=\"0\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<UNSORTEDLISTTYPE family=\"times\" pointSize=\"20\" bold=\"0\" italic=\"0\" underline=\"0\" red=\"255\" green=\"0\" blue=\"0\" chr=\"45\"/>\n"
            "<PARAGRAPH horzAlign=\"0\" depth=\"0\" lineSpacing=\"0\" distBefore=\"0\" distAfter=\"0\">\n"
            "<LINE>\n"
            "<OBJ>\n"
            "<TYPE value=\"1\"/>\n"
            "<FONT family=\"utopia\" pointSize=\"20\" bold=\"1\" italic=\"0\" underline=\"0\"/>\n"
            "<COLOR red=\"0\" green=\"0\" blue=\"0\"/>\n"
            "<VERTALIGN value=\"1\"/>\n"
            "<TEXT> </TEXT>\n"
            "</OBJ>\n"
            "</LINE>\n"
            "</PARAGRAPH>\n"
            "</TEXTOBJ>\n"
            "</OBJECT>\n"
            "</OBJECTS>\n"
            "<INFINITLOOP value=\"0\"/>\n"
            "<MANUALSWITCH value=\"1\"/>\n"
            "<PRESSPEED value=\"1\"/>\n"
            "<PRESSLIDES value=\"137029784\"/>\n"
            "<SELSLIDES>\n"
            "<SLIDE nr=\"0\" show=\"1\"/>\n"
            "</SELSLIDES>\n"
            "<PIXMAPS>\n"
            "</PIXMAPS>\n"
            "<CLIPARTS>\n"
            "</CLIPARTS>\n"
            "</DOC>";    
}
