set( CALLIGRA_SHOULD_BUILD_PRODUCTS
    WORDS
    STAGE 
# plugins
    PLUGIN_ARTISTICTEXTSHAPE
    PLUGIN_DOCKERS
    PLUGIN_TEXTEDITING
    PLUGIN_DEFAULTTOOLS
    PLUGIN_PATHSHAPES
    PLUGIN_VARIABLES
    PLUGIN_CHARTSHAPE
    PLUGIN_PICTURESHAPE
    PLUGIN_TEXTSHAPE
    PLUGIN_PLUGINSHAPE
    PLUGIN_FORMULASHAPE
    PLUGIN_VIDEOSHAPE
    PLUGIN_VECTORSHAPE
    PLUGIN_QTQUICK
)
