.TH KSQLITE2TO3 1 "Tue Apr  5 16:38:35 CEST 2005"
.SH NAME
.B ksqlite2to3
\- A script used to migrate kexi sqlite version 2 databases to version 3

.SH SYNOPSIS
ksqlite2to3 <sqlite2-db-file>
.SH DESCRIPTION
This tool is needed if only if you have generated sqlite2 database for Kexi.
Note this tool is currently Kexi-independent. You can use it with regular
SQLite2 files.

.SH SEE ALSO
http://www.sqlite.org/
http://www.kexi-project.org/

.SH AUTHOR
This manual page was originally written by Igor Genibel 
<igenibel@debian.org>, for the Debian GNU/Linux system (but may be used 
by others).


