######################################################################
# Automatically generated by qmake (1.07a) Sat Aug 27 12:18:37 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .
INCLUDEPATH += /usr/local/kde/4.0/include

HEADERS += TestPointStorage.h
INTERFACES +=
SOURCES += TestPointStorage.cpp

LIBS += -lQtTest

MOC_DIR = build
OBJECTS_DIR = build
UI_DIR = build

DESTDIR = build
