 /*
 * This file has been automatically generated from
 * koffice/kexi/tools/sql_keywords/sql_keywords.sh and
 * koffice/kexi/kexidb/parser/sqlscanner.l
 * and koffice/kexi/tools/sql_keywords/kexi__reserved.
 *
 * Please edit the sql_keywords.sh, not this file!
 */
#include <driver_p.h>

namespace KexiDB {
  const char* DriverPrivate::kexiSQLKeywords[] = {
    "AND",
    "AS",
    "CREATE",
    "FROM",
    "IN",
    "INTEGER",
    "IS",
    "JOIN",
    "LEFT",
    "LIKE",
    "NOT",
    "NULL",
    "ON",
    "OR",
    "RIGHT",
    "SELECT",
    "SIMILAR",
    "TABLE",
    "TO",
    "WHERE",
    "XOR",
    "AFTER",
    "ALL",
    "ASC",
    "BEFORE",
    "BEGIN",
    "BETWEEN",
    "BY",
    "CASCADE",
    "CASE",
    "CHECK",
    "COLLATE",
    "COMMIT",
    "CONSTRAINT",
    "CROSS",
    "DATABASE",
    "DEFAULT",
    "DELETE",
    "DESC",
    "DISTINCT",
    "DROP",
    "END",
    "ELSE",
    "EXPLAIN",
    "FOR",
    "FOREIGN",
    "FULL",
    "GROUP",
    "HAVING",
    "IGNORE",
    "INDEX",
    "INNER",
    "INSERT",
    "INTO",
    "KEY",
    "LIMIT",
    "MATCH",
    "NATURAL",
    "OFFSET",
    "ORDER",
    "OUTER",
    "PRIMARY",
    "REFERENCES",
    "REPLACE",
    "RESTRICT",
    "ROLLBACK",
    "ROW",
    "SET",
    "TEMPORARY",
    "THEN",
    "TRANSACTION",
    "UNION",
    "UNIQUE",
    "UPDATE",
    "USING",
    "VALUES",
    "WHEN",
    0
  };
}
