####### Install

INSTALL = install -m 0755 -s
INSTALL_SHELL = install -m 0755
INSTALL_DATA = install -m 0644
INSTALL_DIR = install -d -m 0755
INSTALL_DIR_PRIVATE = install -d -m 0700

install:
	$(INSTALL_DIR) $(KDEDIR)/share/apps/kspread/scripts
	$(INSTALL_DATA) *.py $(KDEDIR)/share/apps/kspread/scripts
