#ifndef __chart_idl__
#define __chart_idl__

//#include <kom.idl>

module Chart
{

 typedef sequence<double> DoubleSeq;
 typedef sequence<string> StringSeq;

 struct Matrix
 {
	long columns;
	long rows;
	StringSeq columnDescription;
	StringSeq rowDescription;
	DoubleSeq matrix;
 };

 struct Range
 {
	long top;
	long left;
	long bottom;
	long right;
	wstring table;
 };

 interface SimpleChart
 {
	void fill( in Range range, in Matrix matrix );
	void showWizard();
 };

};

#endif

