/* This file is part of the KDE project
   Copyright (C) 2008 Julia Sanchez-Simon <hithwen@gmail.com>
   Copyright (C) 2008 Miguel Angel Aragüez-Rey <fizban87@gmail.com>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Library General Public License for more details.

You should have received a copy of the GNU Library General Public License
along with this program; see the file COPYING.  If not, write to
the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
*/

#include <oracledriver.h>

namespace KexiDB {
  const char* OracleDriver::keywords[] = {
		"ADMIN",
		"CURSOR",
		"FOUND",
		"MOUNT",
		"AFTER",
		"CYCLE",
		"FUNCTION",
		"NEXT",
		"ALLOCATE",
		"DATABASE",
		"GO",
		"NEW",
		"ANALYZE",
		"DATAFILE",
		"GOTO",
		"NOARCHIVELOG",
		"ARCHIVE",
		"DBA",
		"GROUPS",
		"NOCACHE",
		"ARCHIVELOG",
		"DEC",
		"INCLUDING",
		"NOCYCLE",
		"AUTHORIZATION",
		"DECLARE",
		"INDICATOR",
		"NOMAXVALUE",
		"AVG",
		"DISABLE",
		"INITRANS",
		"NOMINVALUE",
		"BACKUP",
		"DISMOUNT",
		"INSTANCE",
		"NONE",
		"BEGIN",
		"DOUBLE",
		"INT",
		"NOORDER",
		"BECOME",
		"DUMP",
		"KEY",
		"NORESETLOGS",
		"BEFORE",
		"EACH",
		"LANGUAGE",
		"NORMAL",
		"BLOCK",
		"ENABLE",
		"LAYER",
		"NOSORT",
		"BODY",
		"END",
		"LINK",
		"NUMERIC",
		"CACHE",
		"ESCAPE",
		"LISTS",
		"OFF",
		"CANCEL",
		"EVENTS",
		"LOGFILE",
		"OLD",
		"CASCADE",
		"EXCEPT",
		"MANAGE",
		"ONLY",
		"CHANGE",
		"EXCEPTIONS",
		"MANUAL",
		"OPEN",
		"CHARACTER",
		"EXEC",
		"MAX",
		"OPTIMAL",
		"CHECKPOINT",
		"EXPLAIN",
		"MAXDATAFILES",
		"OWN",
		"CLOSE",
		"EXECUTE",
		"MAXINSTANCES",
		"PACKAGE",
		"COBOL",
		"EXTENT",
		"MAXLOGFILES",
		"PARALLEL",
		"COMMIT",
		"EXTERNALLY",
		"MAXLOGHISTORY",
		"PCTINCREASE",
		"COMPILE",
		"FETCH",
		"MAXLOGMEMBERS",
		"PCTUSED",
		"CONSTRAINT",
		"FLUSH",
		"MAXTRANS",
		"PLAN",
		"CONSTRAINTS",
		"FREELIST",
		"MAXVALUE",
		"PLI",
		"CONTENTS",
		"FREELISTS",
		"MIN",
		"PRECISION",
		"CONTINUE",
		"FORCE",
		"MINEXTENTS",
		"PRIMARY",
		"CONTROLFILE",
		"FOREIGN",
		"MINVALUE",
		"PRIVATE",
		"COUNT",
		"FORTRAN",
		"MODULE",
		"PROCEDURE",
		"PROFILE",
		"SAVEPOINT",
		"SQLSTATE",
		"TRACING",
		"QUOTA",
		"SCHEMA",
		"STATEMENT_ID",
		"TRANSACTION",
		"READ",
		"SCN",
		"STATISTICS",
		"TRIGGERS",
		"REAL",
		"SECTION",
		"STOP",
		"TRUNCATE",
		"RECOVER",
		"SEGMENT",
		"STORAGE",
		"UNDER",
		"REFERENCES",
		"SEQUENCE",
		"SUM",
		"UNLIMITED",
		"REFERENCING",
		"SHARED",
		"SWITCH",
		"UNTIL",
		"RESETLOGS",
		"SNAPSHOT",
		"SYSTEM",
		"USE",
		"RESTRICTED",
		"SOME",
		"TABLES",
		"USING",
		"REUSE",
		"SORT",
		"TABLESPACE",
		"WHEN",
		"ROLE",
		"SQL",
		"TEMPORARY",
		"WRITE",
		"ROLES",
		"SQLCODE",
		"THREAD",
		"WORK",
		"ROLLBACK",
		"SQLERROR",
		"TIME",
		0
	};
}
