KEXI_OPTIONS =

if compile_kross
  SCRIPTINGDEFINES=-DKEXI_SCRIPTS_SUPPORT
endif

AM_CPPFLAGS=$(SCRIPTINGDEFINES)

KDE_CXXFLAGS = \
$(USE_EXCEPTIONS) $(KEXI_OPTIONS)

KDE_CXXFLAGS += -include $(top_srcdir)/kexi/kexi_global.h

# temporary:
KDE_CXXFLAGS += -DKEXI_NO_AUTOFIELD_WIDGET

# temporary unless cursor works properly in the Designer
KDE_CXXFLAGS += -DKEXI_NO_CURSOR_PROPERTY

VER_INFO = -version-info 1:0:0
