# Generated automatically from Makefile.in by configure.

INCDIR		=	-I$(QTDIR)/include -I$(KDEDIR)/include  -I..
CXXFLAGS	=	$(INCDIR) -g 
LDFLAGS		=	-L$(KDEDIR)/lib -L/usr/X11/lib -L$(QTDIR)/lib -L.. -lkdeui -lkdecore -lX11 -lXext -ldl -lqt -lkofficeui
CXX		=	g++
MOC		=	/usr/bin/moc

####### Files

SOURCES	=	test.cc
HEADERS =	test.h
OBJECTS =	test.o
SRCMETA =	test.moc
TARGET	=	test

####### Implicit rules

.SUFFIXES: .cc

.cc.o:
	$(CXX) -c $(CXXFLAGS) -DSTDC_HEADERS -DHAVE_UNISTD_H $(INCDIR) $<

%.moc: %.h
	$(MOC) $< -o $@      

####### Build rules

all: $(TARGET)

$(TARGET): $(SRCMETA) $(OBJECTS)
	$(CXX) $(OBJECTS) -o $(TARGET) $(LDFLAGS)

depend:
	@makedepend $(INCDIR) $(SOURCES) 2> /dev/null

showfiles:
	@echo $(SOURCES) $(HEADERS) Makefile

clean:
	-rm -f *.o *.bak *~ *% #*
	-rm -f $(SRCMETA) $(TARGET)

####### Meta objects

# DO NOT DELETE THIS LINE -- make depend depends on it.

test.o: test.h ../koAboutDia.h /usr/lib/qt/include/qdialog.h
test.o: /usr/lib/qt/include/qwidget.h /usr/lib/qt/include/qwindefs.h
test.o: /usr/lib/qt/include/qobjdefs.h /usr/lib/qt/include/qglobal.h
test.o: /usr/lib/qt/include/qobject.h /usr/lib/qt/include/qstring.h
test.o: /usr/lib/qt/include/qarray.h /usr/lib/qt/include/qgarray.h
test.o: /usr/lib/qt/include/qshared.h /usr/lib/qt/include/qgeneric.h
test.o: /usr/include/string.h /usr/include/features.h
test.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
test.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/stddef.h
test.o: /usr/lib/qt/include/qevent.h /usr/lib/qt/include/qrect.h
test.o: /usr/lib/qt/include/qsize.h /usr/lib/qt/include/qpoint.h
test.o: /usr/lib/qt/include/qpaintd.h /usr/lib/qt/include/qpalette.h
test.o: /usr/lib/qt/include/qcolor.h /usr/lib/qt/include/qcursor.h
test.o: /usr/lib/qt/include/qfont.h /usr/lib/qt/include/qfontmet.h
test.o: /usr/lib/qt/include/qfontinf.h /usr/lib/qt/include/qlabel.h
test.o: /usr/lib/qt/include/qframe.h /usr/lib/qt/include/qpixmap.h
test.o: /usr/lib/qt/include/qpushbt.h /usr/lib/qt/include/qbutton.h
test.o: /usr/lib/qt/include/qmsgbox.h /usr/lib/qt/include/qlayout.h
test.o: /usr/lib/qt/include/qgmanagr.h /usr/lib/qt/include/qintdict.h
test.o: /usr/lib/qt/include/qgdict.h /usr/lib/qt/include/qcollect.h
test.o: /usr/lib/qt/include/qlist.h /usr/lib/qt/include/qglist.h
test.o: /usr/local/kde/include/kbuttonbox.h /usr/local/kde/include/kapp.h
test.o: /usr/local/kde/include/kconfig.h /usr/local/kde/include/kconfigbase.h
test.o: /usr/lib/qt/include/qstrlist.h /usr/lib/qt/include/qdstream.h
test.o: /usr/lib/qt/include/qiodev.h /usr/local/kde/include/kconfigdata.h
test.o: /usr/lib/qt/include/qdict.h /usr/lib/qt/include/qtstream.h
test.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h
test.o: /usr/include/gnu/types.h
test.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/stdarg.h
test.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/va-alpha.h
test.o: /usr/include/stdio_lim.h /usr/lib/qt/include/qfile.h
test.o: /usr/local/kde/include/kdebug.h /usr/local/kde/include/klocale.h
test.o: /usr/local/kde/include/drag.h /usr/lib/qt/include/qapp.h
test.o: /usr/include/X11/X.h /usr/lib/qt/include/qpopmenu.h
test.o: /usr/lib/qt/include/qtablevw.h /usr/lib/qt/include/qmenudta.h
test.o: ../koPageLayoutDia.h /usr/include/stdlib.h /usr/include/sys/types.h
test.o: /usr/include/time.h /usr/include/endian.h /usr/include/bytesex.h
test.o: /usr/include/sys/select.h /usr/include/selectbits.h
test.o: /usr/include/alloca.h /usr/lib/qt/include/qtabdlg.h
test.o: /usr/lib/qt/include/qcombo.h /usr/lib/qt/include/qgrpbox.h
test.o: /usr/lib/qt/include/qpainter.h /usr/lib/qt/include/qregion.h
test.o: /usr/lib/qt/include/qpen.h /usr/lib/qt/include/qbrush.h
test.o: /usr/lib/qt/include/qpntarry.h /usr/lib/qt/include/qwmatrix.h
test.o: /usr/lib/qt/include/qlined.h /usr/local/kde/include/krestrictedline.h
