####### Install

install:
	mkdir -p $(KDEDIR)/share/apps/kpresenter/autoforms
	cp .autoforms $(KDEDIR)/share/apps/kpresenter/autoforms
	cp -r Arrows Bubbles Connections $(KDEDIR)/share/apps/kpresenter/autoforms
