####### Install

install:
	mkdir -p $(KDEDIR)/share/apps/kpresenter/autoforms
	cp .autoforms $(KDEDIR)/share/apps/kpresenter/autoforms
	cp -r Arrows Connections $(KDEDIR)/share/apps/kpresenter/autoforms
