#ifndef kword_idl
#define kword_idl

#include <openparts.idl>
#include <koffice.idl>
#include <openparts_ui.idl>

module KWord
{
  interface KWordView : KOffice::View
    {
      slot void editUndo();
      slot void editRedo();
      slot void editCut();
      slot void editCopy();
      slot void editPaste();
      slot void editSelectAll();
      slot void editFind();
      slot void editDeleteFrame();
      slot void editReconnectFrame();
      slot void editCustomVars();
      slot void editSerialLetterDataBase();

      slot void newView();
      slot void viewFormattingChars();
      slot void viewFrameBorders();
      slot void viewTableGrid();
      slot void viewHeader();
      slot void viewFooter();
      slot void viewFootNotes();
      slot void viewEndNotes();

      slot void insertPicture();
      slot void insertClipart();
      slot void insertSpecialChar();
      slot void insertFrameBreak();
      slot void insertVariableDateFix();
      slot void insertVariableDateVar();
      slot void insertVariableTimeFix();
      slot void insertVariableTimeVar();
      slot void insertVariablePageNum();
      slot void insertVariableCustom();
      slot void insertVariableSerialLetter();
      slot void insertFootNoteEndNote();
      slot void insertContents();

      slot void formatFont();
      slot void formatColor();
      slot void formatParagraph();
      slot void formatPage();
      slot void formatNumbering();
      slot void formatStyle();
      slot void formatFrameSet();

      slot void extraSpelling();
      slot void extraAutoFormat();
      slot void extraStylist();
      slot void extraOptions();

      slot void toolsEdit();
      slot void toolsEditFrame();
      slot void toolsCreateText();
      slot void toolsCreatePix();
      slot void toolsClipart();
      slot void toolsTable();
      slot void toolsKSpreadTable();
      slot void toolsFormula();
      slot void toolsPart();

      slot void tableInsertRow();
      slot void tableInsertCol();
      slot void tableDeleteRow();
      slot void tableDeleteCol();
      slot void tableJoinCells();
      slot void tableSplitCells();
      slot void tableUngroupTable();
      slot void tableDelete();

      slot void helpContents();
      slot void helpAbout();
      slot void helpAboutKOffice();
      slot void helpAboutKDE();

      slot void textStyleSelected(in wstring size);
      slot void textSizeSelected(in wstring size);
      slot void textFontSelected(in wstring font);
      slot void textBold();
      slot void textItalic();
      slot void textUnderline();
      slot void textColor();
      slot void textAlignLeft();
      slot void textAlignCenter();
      slot void textAlignRight();
      slot void textAlignBlock();
      slot void textLineSpacing(in wstring spc);
      slot void textEnumList();
      slot void textUnsortList();
      slot void textSuperScript();
      slot void textSubScript();
      slot void textBorderLeft();
      slot void textBorderRight();
      slot void textBorderTop();
      slot void textBorderBottom();
      slot void textBorderColor();
      slot void textBorderWidth(in wstring width);
      slot void textBorderStyle(in wstring style);
      slot void frameBorderLeft();
      slot void frameBorderRight();
      slot void frameBorderTop();
      slot void frameBorderBottom();
      slot void frameBorderColor();
      slot void frameBorderWidth(in wstring width);
      slot void frameBorderStyle(in wstring style);
      slot void frameBackColor();

      slot void formulaPower();
      slot void formulaSubscript();
      slot void formulaParentheses();
      slot void formulaAbsValue();
      slot void formulaBrackets();
      slot void formulaFraction();
      slot void formulaRoot();
      slot void formulaIntegral();
      slot void formulaMatrix();
      slot void formulaLeftSuper();
      slot void formulaLeftSub();
    };

  interface KWordDocument : KOffice::Document, KOffice::Print
    {
    };

    interface DocumentFactory : KOffice::DocumentFactory
    {
    };
};

#endif

