#ifndef kword_idl
#define kword_idl

#include <openparts.idl>
#include <koffice.idl>
#include <openparts_ui.idl>

module KWord
{
  interface KWordView : KOffice::View
    {
      slot void editUndo();
      slot void editRedo();
      slot void editCut();
      slot void editCopy();
      slot void editPaste();
      slot void editSelectAll();
      slot void editFind();
      
      slot void newView();
      slot void viewFormattingChars();
      slot void viewFrameBorders();
      slot void viewTableGrid();
      slot void viewHeader();
      slot void viewFooter();
      
      slot void insertPicture();
      slot void insertClipart();
      slot void insertSpecialChar();
      
      slot void formatFont();
      slot void formatColor();
      slot void formatParagraph();
      slot void formatPage();
      slot void formatNumbering();
      slot void formatStyle();
      
      slot void extraSpelling();
      slot void extraStylist();
      slot void extraOptions();
      
      slot void toolsEdit();
      slot void toolsEditFrame();
      slot void toolsCreateText();
      slot void toolsCreatePix();
      slot void toolsClipart();
      slot void toolsTable();
      slot void toolsKSpreadTable();
      slot void toolsFormula();
      slot void toolsPart();

      slot void helpContents();
      slot void helpAbout();
      slot void helpAboutKOffice();
      slot void helpAboutKDE();
      
      slot void textStyleSelected(in string size);
      slot void textSizeSelected(in string size);
      slot void textFontSelected(in string font);
      slot void textBold();
      slot void textItalic();
      slot void textUnderline();
      slot void textColor();
      slot void textAlignLeft();
      slot void textAlignCenter();
      slot void textAlignRight();
      slot void textAlignBlock();
      slot void textEnumList();
      slot void textUnsortList();
      slot void textSuperScript();
      slot void textSubScript();
      slot void textBorderLeft();
      slot void textBorderRight();
      slot void textBorderTop();
      slot void textBorderBottom();
      slot void textBorderColor();
      slot void textBorderWidth(in string width);
      slot void textBorderStyle(in string style);
      slot void frameBorderLeft();
      slot void frameBorderRight();
      slot void frameBorderTop();
      slot void frameBorderBottom();
      slot void frameBorderColor();
      slot void frameBorderWidth(in string width);
      slot void frameBorderStyle(in string style);
    };

  interface KWordDocument : KOffice::Document, KOffice::Print
    {
    };

    interface DocumentFactory : KOffice::DocumentFactory
    {
    };
};

#endif

