.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KCHART 1 "May 9, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
kchart \- a chart drawing program for the KDE Office Suite
.SH SYNOPSIS
.B kchart
[ \fIgeneric-options\fP ]
[ \fB\-\-print\fP ]
[ \fIfile\fP ... ]
.SH DESCRIPTION
\fBKChart\fP is a chart drawing application.
.PP
This application is part of the KDE Office Suite.
.SH OPTIONS
Below are the kchart-specific options.
For a full summary of options, run \fIkchart \-\-help\fP.
.TP
\fB\-\-print\fP
Print the given file(s) and exit.
.SH SEE ALSO
Full user documentation is available through the KDE Help Centre.
You can also enter the URL
\fIhelp:/kchart/\fP
directly into konqueror or you can run
`\fIkhelpcenter help:/kchart/\fP'
from the command-line.
.PP
If the KDE Help Centre is not installed then you can install the package
\fIkoffice-doc-html\fP and read this documentation in HTML format from
\fI/usr/share/doc/kde/HTML/en/kchart/\fP.
.SH AUTHOR
KChart was written by Kalle Dalheimer <kalle@kde.org>, Laurent Montel
<montell@club-internet.fr>, Karl-Heinz Zimmer <khz@kde.org> and
Reginald Stadlbauer <reggie@kde.org>.
.br
This manual page was prepared by Ben Burton <bab@debian.org>
for the Debian GNU/Linux system (but may be used by others).
