usr/bin/kchart
usr/lib/kchart.*
usr/lib/libkdchart.*
usr/lib/kde3/libkchartpart.la
usr/lib/kde3/libkchartpart.so
usr/share/applnk/Office/kchart.desktop
usr/share/apps/kchart
usr/share/doc/kde/HTML/en/kchart/*.bz2
usr/share/doc/kde/HTML/en/kchart/*.docbook
usr/share/doc/kde/HTML/en/kchart/*.png
usr/share/doc/kde/HTML/en/kchart/common
usr/share/icons/crystalsvg/16x16/apps/kchart.png
usr/share/icons/crystalsvg/32x32/apps/kchart.png
usr/share/icons/crystalsvg/48x48/apps/kchart.png
usr/share/services/kchartpart.desktop
../kchart.xpm usr/share/pixmaps
