.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KFORMDESIGNER 1 "June 8, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
kformdesigner \- a form designer for Kexi
.SH SYNOPSIS
.B kformdesigner
[ \fIgeneric-options\fP ]
[ \fIfile\fP ]
.SH DESCRIPTION
\fBKFormDesigner\fP is a form designer for Kexi.
.PP
\fBKexi\fP aims to be an easy to use frontend to various database backends.
Currently only MySQL and CQL++ backends are supported.  It is planned
to support other database systems for better corporate usage in future
versions.  Kexi reports are produced using the Kugar report generator.
.PP
This application is part of the KDE Office Suite.
.SH OPTIONS
For a full summary of options, run \fIkformdesigner \-\-help\fP.
.SH SEE ALSO
.BR kexi (1),
.BR kugar (1).
.SH AUTHOR
Kexi was written by Lucijan Busch <lucijan@kde.org>,
Peter Simonsson <psn@linux.se>, Joseph Wenninger <jowenn@kde.org>,
Seth Kurzenberg <seth@cql.com>, Laurent Montel <montell@club-internet.fr>,
Till Busch <till@bux.at> and Jaroslaw Staniek / OpenOffice Polska
<js@iidea.pl>.
.br
This manual page was prepared by Ben Burton <bab@debian.org>
for the Debian GNU/Linux system (but may be used by others).
