usr/bin/kformula
usr/lib/kde3/libkformulapart.*
usr/lib/kformulamain.*
usr/share/applnk/Office/kformula.desktop
usr/share/apps/kformula
usr/share/doc/kde/HTML/en/kformula/*.bz2
usr/share/doc/kde/HTML/en/kformula/*.docbook
usr/share/doc/kde/HTML/en/kformula/*.png
usr/share/doc/kde/HTML/en/kformula/common
usr/share/icons/crystalsvg/16x16/apps/kformula.png
usr/share/icons/crystalsvg/32x32/apps/kformula.png
usr/share/icons/crystalsvg/48x48/apps/kformula.png
usr/share/services/kformulapart.desktop
../kformula.xpm usr/share/pixmaps
