.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KIVIO 1 "May 9, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
kivio \- a flowcharting program for the KDE Office Suite
.SH SYNOPSIS
.B kivio
[ \fIgeneric-options\fP ]
[ \fB\-\-print\fP ]
[ \fIfile\fP ... ]
.SH DESCRIPTION
\fBKivio\fP is a flowcharting program that offers basic flowcharting
abilities, but with a twist.  Objects are scriptable, and a backend plugin
system offers the ability to make objects do just about anything.
.PP
This application is part of the KDE Office Suite.
.SH OPTIONS
Below are the kivio-specific options.
For a full summary of options, run \fIkivio \-\-help\fP.
.TP
\fB\-\-print\fP
Print the given file(s) and exit.
.SH SEE ALSO
Some documentation from the program author
is available in \fI/usr/share/doc/kivio/\fP.
.SH AUTHOR
Kivio was written by Dave Marotti <lndshark@speakeasy.net>,
Max Judin <max@thekompany.com>, Dmitry Poplavsky <dima@kde.org>,
Peter Simonsson <psn@linux.se>, Ian Reinhart Geiser <geiseri@kde.org>,
Laurent Montel <montel@kde.org> and theKompany.com <info@thekompany.com>.
.br
This manual page was prepared by Ben Burton <bab@debian.org>
for the Debian GNU/Linux system (but may be used by others).
