.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KOCONVERTER 1 "July 5, 2002"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
koconverter \- convert between office suite file formats
.SH SYNOPSIS
.B koconverter
[ \fIgeneric-options\fP ]
[ \fB\-\-mimetype\fP \fImime\fP ]
\fIinput\fP \fIoutput\fP
.SH DESCRIPTION
This manual page documents briefly the
.B koconverter
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
\fBKOConverter\fP is the KOffice file format converter.  It uses the
KOffice import and export filters to convert from any file format
that is understood by KOffice to any other.
.PP
This tool is part of the KDE Office Suite.
.SH OPTIONS
Below are the koconverter-specific options.  For a full summary of options,
run \fIkoconverter \-\-help\fP.
.TP
\fB\-\-mimetype\fP \fImime\fP
Use \fImime\fP as the mime type for the output file.  This option should be
used when the desired type of output file cannot be determined from its
name alone.
.SH EXAMPLES
The following line will convert an Excel spreadsheet to a native KSpread
file.
.PP
.RS
\fIexample$\fP koconverter file.xls file.ksp
.RE
.PP
The following line will convert an Excel spreadsheet to a plain text
file.  Note that this conversion is done interally by first importing
to a KSpread spreadsheet and then exporting as plain text.
.RS
\fIexample$\fP koconverter file.xls file.txt
.RE
.SH AUTHOR
KOConverter was written by David Faure <faure@kde.org>.
.br
This manual page was written by Ben Burton <benb@acm.org>
for the Debian GNU/Linux system (but may be used by others).
