.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KOSHELL 1 "April 30, 2001"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
koshell \- the KDE Office Suite workspace
.SH SYNOPSIS
.B koshell
.RI "[ " generic-options " ]"
.SH DESCRIPTION
This manual page documents briefly the
.B koshell
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
\fBKOShell\fP (the KOffice workspace) is a desktop with easy one-click
launchers for KOffice applications.
.PP
This application is part of the KDE Office Suite.
.SH OPTIONS
For a full summary of options, run \fIkoshell \-\-help\fP.
.SH SEE ALSO
Some documentation from the program author
is available in \fI/usr/share/doc/koshell/\fP.
.SH AUTHOR
KOShell was written by Torben Weis <weis@kde.org>, Simon Hausmann
<hausmann@kde.org> and David Faure <faure@kde.org>.
.br
This manual page was written by Ben Burton <benb@acm.org>
for the Debian GNU/Linux system (but may be used by others).
