usr/bin/kpresenter
usr/bin/kprconverter.pl
usr/lib/kde3/libkpresenterpart.*
usr/lib/kpresenter.*
usr/share/applnk/Office/kpresenter.desktop
usr/share/apps/kpresenter
usr/share/icons/crystalsvg/16x16/apps/kpresenter.png
usr/share/icons/crystalsvg/32x32/apps/kpresenter.png
usr/share/icons/crystalsvg/48x48/apps/kpresenter.png
usr/share/doc/kde/HTML/en/kpresenter/*.bz2
usr/share/doc/kde/HTML/en/kpresenter/*.docbook
usr/share/doc/kde/HTML/en/kpresenter/*.png
usr/share/doc/kde/HTML/en/kpresenter/common
../kpresenter.xpm usr/share/pixmaps
