.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KPRESENTER 1 "April 30, 2001"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
kpresenter \- a presentation program for the KDE Office Suite
.SH SYNOPSIS
.B kpresenter
.RI "[ " generic-options " ] [ " file " ]"
.SH DESCRIPTION
This manual page documents briefly the
.B kpresenter
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
\fBKPresenter\fP is a fully-featured presentation program.  It is
sufficiently developed that it is already being successfully used for
giving talks and presentations.
.PP
This application is part of the KDE Office Suite.
.SH OPTIONS
For a full summary of options, run \fIkpresenter \-\-help\fP.
.SH SEE ALSO
The original documentation from the program author
is available in \fI/usr/share/doc/kpresenter/\fP.
.SH AUTHOR
KPresenter was written by Reginald Stadlbauer <reggie@kde.org>, Werner
Trobin <trobin@kde.org> and David Faure <dfaure@kde.org>.
.br
This manual page was written by Ben Burton <benb@acm.org>
for the Debian GNU/Linux system (but may be used by others).
