.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KSPREAD 1 "May 9, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
kspread \- a spreadsheet for the KDE Office Suite
.SH SYNOPSIS
.B kspread
[ \fIgeneric-options\fP ]
[ \fB\-\-print\fP ]
[ \fIfile\fP ... ]
.SH DESCRIPTION
\fBKSpread\fP is a powerful spreadsheet application.  It is scriptable and
provides both table-oriented sheets and support for complex mathematical
formulae and statistics.
.PP
This application is part of the KDE Office Suite.
.SH OPTIONS
Below are the kspread-specific options.
For a full summary of options, run \fIkspread \-\-help\fP.
.TP
\fB\-\-print\fP
Print the given file(s) and exit.
.SH SEE ALSO
.BR kformula (1).
.PP
Full user documentation is available through the KDE Help Centre.
You can also enter the URL
\fIhelp:/kspread/\fP
directly into konqueror or you can run
`\fIkhelpcenter help:/kspread/\fP'
from the command-line.
.PP
If the KDE Help Centre is not installed then you can install the package
\fIkoffice-doc-html\fP and read this documentation in HTML format from
\fI/usr/share/doc/kde/HTML/en/kspread/\fP.
.SH AUTHOR
KSpread was written by Torben Weis <weis@kde.org>, Laurent Montel
<montell@club-internet.fr>, David Faure <faure@kde.org> and many others.
.br
This manual page was prepared by Ben Burton <bab@debian.org>
for the Debian GNU/Linux system (but may be used by others).
