usr/bin/kspread
usr/lib/kde3/libkspreadcalc.*
usr/lib/kde3/libkspreadhtmlexport.*
usr/lib/kde3/libkspreadpart.*
usr/lib/kspread.*
usr/share/applnk/Office/kspread.desktop
usr/share/apps/kspread
usr/share/icons/crystalsvg/16x16/apps/kspread.png
usr/share/icons/crystalsvg/32x32/apps/kspread.png
usr/share/icons/crystalsvg/48x48/apps/kspread.png
usr/share/icons/locolor/32x32/apps/kspreadcalc.png
usr/share/icons/locolor/22x22/apps/kspreadcalc.png
usr/share/icons/locolor/16x16/apps/kspreadcalc.png
usr/share/doc/kde/HTML/en/kspread/*.bz2
usr/share/doc/kde/HTML/en/kspread/*.docbook
usr/share/doc/kde/HTML/en/kspread/*.png
usr/share/doc/kde/HTML/en/kspread/common
../kspread.xpm usr/share/pixmaps
