.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KTHESAURUS 1 "May 9, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
kthesaurus \- a thesaurus for the KDE Office Suite
.SH SYNOPSIS
.B kthesaurus
[ \fIgeneric-options\fP ] [ \fIterm\fP ]
.SH DESCRIPTION
\fBKThesaurus\fP is a thesaurus tool.  It lists words related to a search
term and offers a user interface to WordNet, an online lexical reference
system.
.PP
Only the English language is supported.
.PP
A term to search for may be optionally specified on the command-line.
.PP
This application is part of the KDE Office Suite.
.SH OPTIONS
For a full summary of options, run \fIkthesaurus \-\-help\fP.
.SH SEE ALSO
.BR kword (1).
.PP
Full user documentation is available through the KDE Help Centre.
You can also enter the URL
\fIhelp:/thesaurus/\fP
directly into konqueror or you can run
`\fIkhelpcenter help:/thesaurus/\fP'
from the command-line.
.PP
If the KDE Help Centre is not installed then you can install the package
\fIkoffice-doc-html\fP and read this documentation in HTML format from
\fI/usr/share/doc/kde/HTML/en/thesaurus/\fP.
.SH AUTHOR
KThesaurus was written by Daniel Naber <daniel.naber@t-online.de>.
.br
This manual page was prepared by Ben Burton <bab@debian.org>
for the Debian GNU/Linux system (but may be used by others).
