.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KUGAR 1 "April 7, 2001"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
kugar \- a business report maker for the KDE Office Suite
.SH SYNOPSIS
.B kugar
-d xml_data_file
[ -r xml_report_template_URL ]
.SH DESCRIPTION
This manual page documents briefly the
.I kugar
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fIKugar\fP is a tool for generating business quality reports which can
be viewed and printed.  It includes a standalone report viewer and a
KPart report viewer.  The latter means that any KDE application can
embed the report viewing functionality and that reports can be viewed
using the Konqueror browser.
.PP
Kugar will create a report for the data stored in the data file xml_data_file.
The data will be displayed according to the layout described in the template
file xml_report_template_URL.
If this template file is omitted then any template specified in the data
file will be used.
.PP
Note that simply clicking on the data file in Konqueror will cause Kugar
to create a report (using a template specified in the data file).
Data files typically end in \fB.kud\fP and template files typically
end in \fB.kut\fP.
.PP
This application is part of the KDE Office Suite.
.PP
Run
.I kugar --help
for more information.
.SH SEE ALSO
The original documentation from the program author
is available in /usr/share/doc/kugar/.
.SH AUTHOR
Kugar was written by Mutiny Bay Software <info@mutinybaysoftware.com>
and Phil Thompson <phil@river-bank.demon.co.uk>.
.br
This manual page was written by Ben Burton <benb@acm.org>
for the Debian GNU/Linux system (but may be used by others).
