#ifndef CALLIGRALIBS_GLOBAL_H
#define CALLIGRALIBS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CALLIGRALIBS_LIBRARY)
#  define CALLIGRALIBSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CALLIGRALIBSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CALLIGRALIBS_GLOBAL_H
