#ifndef __kformula_idl__
#define __kformula_idl__

#include <openparts.idl>
#include <koffice.idl>
#include <openparts_ui.idl>

module KFormula
{
       interface View : KOffice::View
	{
	  slot void newView();
	  slot void addText();
	  slot void addRoot();		
	  slot void addFraction();	
	  slot void addVertSpace();	
	  slot void addBracket();
	  slot void addIntegral();
	  slot void addSymbol();
	  slot void addMatrix();
	  slot void reduce();
	  slot void enlarge();
	  slot void fontSwitch();
	  slot void fractionAlignU();
	  slot void fractionAlignD();
	  slot void fractionAlignM();
	  slot void addTopLeftIndex();
	  slot void addBottomLeftIndex();
	  slot void addTopRightIndex();
	  slot void addBottomRightIndex();
          slot void indexList();
          slot void sizeSelected(in wstring size);
          slot void fontSelected(in wstring font);
          slot void modeSelected(in wstring mode);
          slot void textFont();
          slot void textSplit();
          slot void togglePixmap();
          slot void integralLower();
          slot void integralHigher();
          slot void bracketType();
          slot void matrixSet();
          slot void matrixRemRow();
          slot void matrixRemCol();
          slot void matrixInsRow();
          slot void matrixInsCol();
          slot void fractionHAlign();
          slot void toggleMidline();
          slot void symbolType();
          slot void DecorationType();
          slot void remove();
          slot void elementColor();
          slot void generalColor();
          slot void generalFont();
          slot void fractionAlignL();
          slot void fractionAlignR();
          slot void fractionAlignC();
          slot void fractionDist();
          slot void fractionDistMore();
          slot void fractionDistLess();
          slot void delimiterLeft(in wstring left);
          slot void delimiterRight(in wstring right);    
//	  slot void insertIndex(in unsigned long i);
	};

	interface Document : KOffice::Document
	{
	};

	interface DocumentFactory : KOffice::DocumentFactory
	{
	};
};

#endif

