#ifndef __kformula_idl__
#define __kformula_idl__

#include <parts.idl>

module KFormula
{
       interface View : OPParts::View
	{
	  slot void newView();
	  slot void addText();
	  slot void addRoot();		
	  slot void addFraction();	
	  slot void addVertSpace();	
	  slot void addBracket();
	  slot void addIntegral();
	  slot void addSymbol();
	  slot void reduce();
	  slot void enlarge();
	  slot void reduceRecur();
	  slot void enlargeRecur();
	  slot void enlargeAll();
	  slot void setGreek();
	  slot void addTopLeftIndex();
	  slot void addBottomLeftIndex();
	  slot void addTopRightIndex();
	  slot void addBottomRightIndex();
          slot void indexList();
//	  slot void insertIndex(in unsigned long i);
	};

	interface Document : OPParts::Document
	{
	};

	interface Factory : OPParts::Factory
	{
	};
};

#endif

