#ifndef __kpresenter_idl__
#define __kpresenter_idl__

module KPresenter
{
  interface KPresenterView
    {
       void editUndo();
       void editRedo();
       void editCut();
       void editCopy();
       void editPaste();
       void editDelete();
       void editSelectAll();
       void editCopyPage();
       void editDelPage();
       void editFind();
       void editFindReplace();
       void editHeaderFooter();

       void newView();
	
       void insertPage();
       void insertPicture();
       void insertClipart();

       void toolsMouse();
       void toolsLine();
       void toolsRectangle();
       void toolsCircleOrEllipse();
       void toolsPie();
       void toolsText();
       void toolsAutoform();
       void toolsDiagramm();
       void toolsTable();
       void toolsFormula();
       void toolsObject();

       void extraPenBrush();
       void extraConfigPie();
       void extraConfigRect();
       void extraRaise();
       void extraLower();
       void extraRotate();
       void extraShadow();
       void extraAlignObj();
       void extraBackground();
       void extraLayout();
       void extraOptions();
       void extraLineBegin();
       void extraLineEnd();
       void extraWebPres();

       void extraAlignObjLeftidl();
       void extraAlignObjCenterHidl();
       void extraAlignObjRightidl();
       void extraAlignObjTopidl();
       void extraAlignObjCenterVidl();
       void extraAlignObjBottomidl();

       void screenConfigPages();
       void screenPresStructView();
       void screenAssignEffect();
       void screenStart();
       void screenStop();
       void screenPause();
       void screenFirst();
       void screenPrev();
       void screenNext();
       void screenLast();
       void screenSkip();
       void screenFullScreen();
       void screenPen();
       void presPen1idl();
       void presPen2idl();
       void presPen3idl();
       void presPen4idl();
       void presPen5idl();
       void presPen6idl();
       void presPen7idl();
       void presPen8idl();
       void presPen9idl();
       void presPen10idl();
       void presPenColoridl();

       void helpContents();

       void sizeSelected(in wstring size);
       void fontSelected(in wstring font);
       void textBold();
       void textItalic();
       void textUnderline();
       void textColor();
       void textAlignLeft();
       void textAlignCenter();
       void textAlignRight();
       void mtextAlignLeft();
       void mtextAlignCenter();
       void mtextAlignRight();
       void mtextFont();
       void textEnumList();
       void textUnsortList();
       void textNormalText();
       void textDepthPlus();
       void textDepthMinus();
       void textSpacing();
       void textContentsToHeight();
       void textObjectToContents();

       void setPenColor(in long id);
       void setFillColor(in long id);
    };
};

#endif
