#ifndef __kpresenter_idl__
#define __kpresenter_idl__

#include <parts.idl>

module KPresenter
{
  interface KPresenterView : OPParts::View
    {
      slot void editUndo();
      slot void editRedo();
      slot void editCut();
      slot void editCopy();
      slot void editPaste();
      slot void editDelete();
      slot void editSelectAll();
      
      slot void newView();
      
      oneway void insertPage();
      oneway void insertPicture();
      oneway void insertClipart();
      oneway void insertLine();
      oneway void insertRectangle();
      oneway void insertCircleOrEllipse();
      oneway void insertText();
      oneway void insertAutoform();
      oneway void insertObject();

      oneway void insertLineHidl();
      oneway void insertLineVidl();
      oneway void insertLineD1idl();
      oneway void insertLineD2idl();
      oneway void insertNormRectidl();
      oneway void insertRoundRectidl();

      oneway void extraPenBrush();
      oneway void extraRaise();
      oneway void extraLower();
      oneway void extraRotate();
      oneway void extraBackground();
      oneway void extraLayout();
      oneway void extraOptions();

      oneway void screenConfigPages();
      oneway void screenAssignEffect();
      oneway void screenStart();
      oneway void screenStop();
      oneway void screenPause();
      oneway void screenFirst();
      oneway void screenPrev();
      oneway void screenNext();
      oneway void screenLast();
      oneway void screenSkip();
      oneway void screenFullScreen();
      oneway void screenPen();
      oneway void presPen1idl();
      oneway void presPen2idl();
      oneway void presPen3idl();
      oneway void presPen4idl();
      oneway void presPen5idl();
      oneway void presPen6idl();
      oneway void presPen7idl();
      oneway void presPen8idl();
      oneway void presPen9idl();
      oneway void presPen10idl();
      oneway void presPenColoridl();

      oneway void helpContents();
      oneway void helpAbout();
      oneway void helpAboutKOffice();
      oneway void helpAboutKDE();

      oneway void sizeSelected(in string size);
      oneway void fontSelected(in string font);
      oneway void textBold();
      oneway void textItalic();
      oneway void textUnderline();
      oneway void textColor();
      oneway void textAlignLeft();
      oneway void textAlignCenter();
      oneway void textAlignRight();
      oneway void mtextAlignLeft();
      oneway void mtextAlignCenter();
      oneway void mtextAlignRight();
      oneway void mtextFont();
      oneway void textEnumList();
      oneway void textUnsortList();
      oneway void textNormalText();
    };
  
  interface KPresenterDocument : OPParts::Document, OPParts::Print
    {
    };

  interface Factory : OPParts::Factory
    {
    };
};

#endif
