#line 2 "scanner.cc"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
static yyconst short int yy_accept[271] =
    {   0,
        0,    0,   90,   88,    1,    2,   23,   88,   88,   88,
       31,   35,   88,   16,   17,   29,   27,   19,   28,   40,
       30,   84,   83,   18,   20,   38,   24,   39,   77,   77,
       77,   14,   15,   34,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   12,
       33,   13,   32,   22,    0,   87,    0,    0,    5,    0,
        0,    0,    0,   74,   75,   81,    3,    0,    0,   84,
        0,    0,    0,   85,   83,   76,   26,   36,   21,    0,
       37,   25,    0,    8,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   56,   77,   77,   77,   77,   58,

       77,   49,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,    0,    0,    0,    8,   86,    0,    0,    0,
        3,    0,    0,   80,    0,   79,   85,    0,    0,    0,
        0,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   57,   77,   77,   77,   77,   77,   50,
       77,   77,   77,   77,   77,   77,   71,   66,   77,    0,
        0,    0,    0,    0,    0,   82,    0,    9,    0,   79,
        0,    7,    0,    0,    0,    0,   77,   43,   77,   46,
       77,   77,   77,   77,   77,   59,   64,   48,   77,   77,
       77,   77,   77,   60,   77,   77,   77,   77,   77,   77,

       77,    0,    0,    0,    0,    0,    0,   78,    0,    0,
        0,    0,   11,   42,   77,   72,   52,   41,   77,   77,
       77,   77,   77,   69,   77,   73,   77,   77,   77,   77,
       77,   55,    0,    0,    0,    0,    6,    0,   77,   77,
       54,   77,   77,   65,   77,   70,   77,   62,   63,   44,
       45,    0,    0,   10,    6,   77,   47,   61,   77,   77,
       77,    0,    4,   77,   53,   77,   67,   68,   51,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   30,   30,   30,   31,   32,
       33,   33,   33,   33,   33,   34,   33,   33,   33,   33,
       33,   35,   36,   37,   38,   33,   33,   39,   33,   33,
       40,   41,   42,   43,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   54,   54,   55,   56,   57,
       58,   59,   54,   60,   61,   62,   63,   64,   65,   66,
       67,   54,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[72] =
    {   0,
        1,    2,    3,    1,    4,    5,    1,    6,    1,    1,
        7,    1,    1,    1,    1,    1,    1,    4,    1,    8,
        8,    9,    1,    1,    1,    1,    1,    5,   10,   10,
       10,   10,   11,   11,   11,   11,   11,   11,   12,    1,
        5,    1,    1,   13,    8,    8,    9,    9,    9,    8,
       14,   14,   14,   14,   14,   14,   15,   14,   14,   15,
       14,   15,   14,   15,   14,   15,   14,    1,    1,    1,
        1
    } ;

static yyconst short int yy_base[290] =
    {   0,
        0,    0,  788,  789,  789,  789,  761,   66,   70,    0,
      789,  789,  745,  789,  789,  789,  770,  789,  767,   54,
      764,   72,   77,  759,  789,   53,   54,   57,  134,  752,
      745,  789,  789,  789,    0,  194,  717,   51,   42,   60,
       23,   62,   43,   24,   65,   70,   68,   75,   79,  789,
      789,  789,  789,  789,   95,  789,  137,  775,  789,   86,
      139,  766,  197,  789,  789,  188,    0,  768,  123,  229,
      237,  135,  249,  282,  270,  789,  789,  789,  789,  201,
      789,  789,  128,  218,    0,    0,  713,  740,  735,  710,
       72,  159,  149,  222,  709,   90,  160,  112,  183,  708,

      217,  186,  199,  707,  212,  236,  184,  223,  243,  145,
      233,  244,  301,    0,  279,  295,  789,  288,    0,  318,
        0,  760,  326,  323,  329,  347,    0,  322,  317,  748,
      758,  729,  733,  263,  304,  115,  294,  298,  275,  308,
      312,  701,  315,  313,  318,  320,  301,  324,  232,  700,
      323,  331,  325,  332,  328,  699,  698,  697,  337,  375,
      411,  394,  387,  714,  380,  383,  389,  392,  403,  406,
      403,  789,  721,  410,  715,  426,  668,    0,  368,  636,
      387,  374,  635,  375,  609,  608,  607,  593,  405,  393,
      402,  589,  403,  588,  357,  408,  409,  423,  425,  426,

      427,  468,  469,  451,  637,  639,  457,  460,  464,  465,
      643,  470,  473,    0,  440,  581,  578,  577,  441,  449,
      450,  575,  574,  573,  451,  438,  457,  458,  461,  570,
      456,  558,  501,  606,  509,  502,  562,  609,  462,  540,
      536,  470,  482,  535,  483,  503,  471,  502,  499,  498,
      497,  555,  514,  517,  789,  495,  492,  490,  485,  494,
      486,  548,  789,  493,  488,  500,  248,  191,   40,  789,
      562,  577,  583,  595,  607,  615,  626,  637,  652,  662,
      667,  670,  680,  690,  696,  706,  716,  728,  743
    } ;

static yyconst short int yy_def[290] =
    {   0,
      270,    1,  270,  270,  270,  270,  270,  271,  272,  273,
      270,  270,  274,  270,  270,  270,  270,  270,  270,  270,
      270,  275,  275,  270,  270,  270,  270,  270,  270,   29,
       29,  270,  270,  270,  276,   29,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,  270,
      270,  270,  270,  270,  271,  270,  277,  272,  270,  272,
      273,  270,  278,  270,  270,  270,  279,  280,  270,  275,
      275,  275,  275,  275,  275,  270,  270,  270,  270,  270,
      270,  270,  270,   36,   29,  276,   36,   29,   29,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,

       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,  271,  281,  272,  270,  270,  270,  282,  270,
      279,  280,  280,  270,  270,  275,   74,  270,  283,  270,
      284,   29,   29,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,  271,
      271,  272,  270,  285,  270,  270,  270,  270,  270,  270,
      283,  270,  283,  286,  284,  284,   29,   29,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,

       36,  271,  271,  272,  270,  287,  270,  270,  286,  288,
      286,  270,  270,   29,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,  272,  287,  287,  288,  270,  288,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,  289,  270,  270,  270,   36,   36,   36,   36,   36,
       36,  289,  270,   36,   36,   36,   36,   36,   36,    0,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270
    } ;

static yyconst short int yy_nxt[861] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   23,   24,   25,   26,   27,   28,    4,   29,   29,
       29,   30,   29,   29,   29,   29,   31,   29,   29,   32,
        4,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       37,   37,   42,   37,   37,   43,   37,   44,   37,   45,
       46,   47,   37,   48,   49,   37,   37,   50,   51,   52,
       53,   56,   59,   66,   66,   66,   68,   77,   78,   79,
       99,   68,   81,   82,   87,   87,  104,  103,   59,   69,
       94,   70,   70,   71,   69,   91,   75,   75,   75,   95,

       56,   87,   73,   87,   87,   92,   57,   73,   93,  105,
       74,  100,   87,  106,   96,   97,   98,  101,  102,  111,
       73,   87,  107,   87,   80,   73,   87,  110,   60,   87,
      112,  108,  135,  136,  109,   57,   87,   74,   68,   68,
       87,   83,  124,  124,  124,  115,   83,  116,  116,  116,
      141,   87,  270,   84,   84,   84,  113,  113,  116,  116,
      116,  181,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   87,  143,  114,   87,   86,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,

       87,  270,  114,  137,  128,  138,   87,   66,   66,   66,
       87,  157,  142,   87,   87,   87,  118,  118,  120,  129,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   68,  154,  119,  120,   84,   84,   84,
      131,   68,  144,  147,   87,   87,   69,  148,   70,   70,
       71,  149,   87,   68,   69,   90,   71,   71,   71,   73,
       87,  130,  119,  125,  151,  125,  270,   73,  126,  126,
      126,  139,  145,   87,   68,  146,  140,   73,   87,   87,
      152,   59,  155,   87,   87,   73,   68,   69,  194,   75,
       75,   75,  158,   87,   87,  156,  159,  153,  117,  270,

       73,  127,  127,  127,   87,   87,   56,  163,  163,   87,
      127,  127,  127,  127,  116,  116,  116,  131,   73,  184,
      160,  160,  179,  162,   87,  128,  127,  127,  127,  127,
      127,  127,  165,  167,  165,  172,   87,  166,  166,  166,
      129,   57,  124,  124,  124,  168,  168,  168,  170,  170,
      170,   68,  180,  169,  182,   87,  185,  173,  183,   87,
      186,  189,   87,  192,  270,   87,  126,  126,  126,   87,
      188,  169,  193,   87,   87,  190,   87,  191,  196,   87,
       56,   87,  130,  195,   87,   87,   87,  197,  198,   87,
      199,  201,   87,   87,  202,  202,   59,  117,   87,  166,

      166,  166,  166,  166,  166,  226,   62,   62,  168,  168,
      168,  168,  168,  168,  206,   57,   56,  207,   87,  207,
      215,  172,  208,  208,  208,  170,  170,  170,  210,   87,
      203,  203,  203,  212,  217,   87,   87,  219,  216,  203,
      203,  203,  203,  173,  204,  213,  213,  213,   87,  221,
      211,   57,  222,   59,   87,  203,  203,  203,  203,  203,
      203,  223,  225,   87,   87,  227,   87,  229,  228,   87,
       87,  230,  231,   56,   56,  232,  208,  208,  208,  208,
      208,  208,  210,  237,   87,  239,   87,   87,   87,  213,
      213,  213,  213,  213,  213,  240,  242,  241,  246,   87,

      245,   87,   87,   59,  211,  238,  233,  251,   57,   57,
       87,   87,   87,  247,  248,  249,  253,   87,   87,   87,
      237,  258,   87,   87,  256,  261,  259,  260,  254,  254,
      254,   87,   87,  254,  254,  254,  254,  254,  254,  265,
      266,  268,  238,   87,   87,  252,   87,   87,  269,   87,
      263,   87,  267,   87,   87,   87,  264,  263,   87,   87,
       87,   87,   55,   87,   87,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   61,   61,   61,   62,   87,   87,   62,   62,

       62,  257,   62,   62,   62,   62,   62,   62,   62,   62,
       72,  270,  255,  270,   72,   72,   72,   72,   72,   87,
       72,   72,   86,   86,   86,   86,   86,   86,   86,   86,
       55,  250,   55,   55,   87,  244,  243,   55,   87,   87,
       55,   62,   87,   62,   62,  270,  234,  117,   62,   87,
      224,   62,  121,  121,   87,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  123,   87,   87,
      220,  123,  123,  123,  161,  161,  161,  164,  164,  164,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  176,  218,   87,  214,  176,

      176,  176,  205,  205,  205,  205,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  235,  270,  270,  117,  235,  235,  235,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,   87,   87,
      200,   87,  187,  178,  177,  175,  174,  270,  150,   87,
       87,  134,  133,  132,   87,  122,  117,   59,   87,   89,
       88,   76,   67,   65,   64,   63,   54,  270,    3,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270
    } ;

static yyconst short int yy_chk[861] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    8,    9,   20,   20,   20,   22,   26,   26,   27,
       41,   23,   28,   28,   41,   44,   44,   43,   60,   22,
       39,   22,   22,   22,   23,   38,   23,   23,   23,   39,

       55,  269,   22,   39,   43,   38,    8,   23,   38,   45,
       22,   42,   38,   45,   40,   40,   40,   42,   42,   48,
       22,   40,   46,   42,   27,   23,   45,   47,    9,   47,
       49,   46,   91,   91,   46,   55,   48,   22,   29,   72,
       49,   29,   69,   69,   69,   60,   61,   83,   83,   83,
       96,   96,   72,   29,   29,   29,   57,   57,   61,   61,
       61,  136,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   98,   98,   57,  136,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,

       29,   36,   57,   92,   80,   93,  110,   66,   66,   66,
       93,  110,   97,   36,   36,   36,   63,   63,   66,   80,
       92,   97,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   70,  107,   63,   66,   84,   84,   84,
       84,   71,   99,  102,   99,  107,   70,  102,   70,   70,
       70,  103,  268,   73,   71,   36,   71,   71,   71,   70,
      103,   80,   63,   73,  105,   73,   73,   71,   73,   73,
       73,   94,  101,  105,   75,  101,   94,   70,  101,   84,
      106,  115,  108,   94,  108,   71,   74,   75,  149,   75,
       75,   75,  111,  149,  111,  109,  112,  106,  118,   74,

       75,   74,   74,   74,  109,  112,  113,  118,  118,  267,
       74,   74,   74,   74,  116,  116,  116,  116,   75,  139,
      113,  113,  134,  115,  134,  128,   74,   74,   74,   74,
       74,   74,  120,  123,  120,  129,  139,  120,  120,  120,
      128,  113,  124,  124,  124,  123,  123,  123,  125,  125,
      125,  126,  135,  124,  137,  137,  140,  129,  138,  138,
      141,  144,  147,  147,  126,  135,  126,  126,  126,  140,
      143,  124,  148,  141,  144,  145,  143,  146,  152,  145,
      160,  146,  128,  151,  151,  148,  153,  153,  154,  155,
      155,  159,  152,  154,  160,  160,  162,  163,  159,  165,

      165,  165,  166,  166,  166,  195,  163,  163,  167,  167,
      167,  168,  168,  168,  168,  160,  161,  169,  195,  169,
      179,  171,  169,  169,  169,  170,  170,  170,  174,  179,
      161,  161,  161,  176,  182,  182,  184,  184,  181,  161,
      161,  161,  161,  171,  162,  176,  176,  176,  181,  189,
      174,  161,  190,  204,  190,  161,  161,  161,  161,  161,
      161,  191,  193,  191,  193,  196,  189,  198,  197,  196,
      197,  199,  200,  202,  203,  201,  207,  207,  207,  208,
      208,  208,  209,  210,  198,  215,  199,  200,  201,  212,
      212,  212,  213,  213,  213,  219,  221,  220,  226,  226,

      225,  215,  219,  233,  209,  210,  204,  231,  202,  203,
      220,  221,  225,  227,  228,  229,  235,  231,  227,  228,
      236,  242,  229,  239,  239,  247,  243,  245,  235,  235,
      235,  242,  247,  253,  253,  253,  254,  254,  254,  259,
      260,  264,  236,  243,  245,  233,  259,  261,  266,  265,
      262,  258,  261,  257,  264,  260,  256,  252,  251,  250,
      249,  266,  271,  248,  246,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  273,  273,  273,  274,  244,  241,  274,  274,

      274,  240,  274,  274,  274,  274,  274,  274,  274,  274,
      275,  238,  237,  234,  275,  275,  275,  275,  275,  232,
      275,  275,  276,  276,  276,  276,  276,  276,  276,  276,
      277,  230,  277,  277,  224,  223,  222,  277,  218,  217,
      277,  278,  216,  278,  278,  211,  206,  205,  278,  194,
      192,  278,  279,  279,  188,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  280,  187,  186,
      185,  280,  280,  280,  281,  281,  281,  282,  282,  282,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  284,  183,  180,  177,  284,

      284,  284,  285,  285,  285,  285,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  287,  175,  173,  164,  287,  287,  287,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  158,  157,
      156,  150,  142,  133,  132,  131,  130,  122,  104,  100,
       95,   90,   89,   88,   87,   68,   62,   58,   37,   31,
       30,   24,   21,   19,   17,   13,    7,    3,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.ll"
#define INITIAL 0
#line 2 "scanner.ll"

#define YY_NO_UNPUT
#include <stdlib.h>
#include <ctype.h>

#include "kscript_parsenode.h"
#include "kscript_types.h"

#ifndef KDE_USE_FINAL
#include "yacc.cc.h"
#endif

extern int idl_line_no;

#include <qstring.h>

static KScript::Long ascii_to_longlong( long base, const char *s )
{
  KScript::Long ll = 0;
  while( *s != '\0' ) {
    char c = *s++;
    if( c >= 'a' )
      c -= 'a' - 'A';
    c -= '0';
    if( c > 9 )
      c -= 'A' - '0' - 10;
    ll = ll * base + c;
  }
  return ll;
}

static KScript::Double ascii_to_longdouble (const char *s)
{
  KScript::Double d;
#ifdef HAVE_SCANF_LF
  sscanf (s, "%Lf", &d);
#else
  /*
   * this is only an approximation and will probably break fixed<>
   * parameter calculation on systems where
   * sizeof(double) < sizeof(long double). but fortunately all
   * systems where scanf("%Lf") is known to be broken (Linux/Alpha
   * and HPUX) have sizeof(double) == sizeof(long double).
   */
  d = strtod (s, NULL);
#endif
  return d;
}

static char translate_char( const char *s )
{
  char c = *s++;
  
  if( c != '\\' )
    return c;
  c = *s++;
  switch( c ) {
  case 'n':
    return '\n';
  case 't':
    return '\t';
  case 'v':
    return '\v';
  case 'b':
    return '\b';
  case 'r':
    return '\r';
  case 'f':
    return '\f';
  case 'a':
    return '\a';
  case '\\':
    return '\\';
  case '?':
    return '\?';
  case '\'':
    return '\'';
  case '"':
    return '"';
  case 'x':
  case 'X':
    return (char) ascii_to_longlong( 16, s );
  default:
    // Gotta be an octal
    return (char) ascii_to_longlong( 8, s );
  }
}


/*--------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------*/
#line 741 "scanner.cc"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 124 "scanner.ll"


#line 895 "scanner.cc"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 271 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 270 );
		yy_cp = yy_last_accepting_cpos;
		yy_current_state = yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 126 "scanner.ll"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 127 "scanner.ll"
idl_line_no++;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 128 "scanner.ll"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 129 "scanner.ll"
{
			  yylval._str = new QString( yytext );
                          idl_line_no++;
                          return T_PRAGMA;
                        }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 134 "scanner.ll"
;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 136 "scanner.ll"
{
						  const char *c = yytext + 2;
						  while( isspace( *c ) ) ++c;
			 			  yylval.ident = new QString( c );
						  return T_SUBST;
						}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 142 "scanner.ll"
{
						  const char *c = yytext + 2;
						  while( isspace( *c ) ) ++c;
			 			  yylval.ident = new QString( c );
						  return T_MATCH;
						}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 149 "scanner.ll"
{
                          yylval._str = new QString( yytext );
			  return T_CELL;
		       };
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 154 "scanner.ll"
{
                          yylval._str = new QString( yytext );
			  return T_CELL;
		       };
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 159 "scanner.ll"
{
                          yylval._str = new QString( yytext );
			  return T_RANGE;
		       };
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 164 "scanner.ll"
{
                          yylval._str = new QString( yytext );
			  return T_RANGE;
		       };
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 169 "scanner.ll"
return T_LEFT_CURLY_BRACKET;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 170 "scanner.ll"
return T_RIGHT_CURLY_BRACKET;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 171 "scanner.ll"
return T_LEFT_SQUARE_BRACKET;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 172 "scanner.ll"
return T_RIGHT_SQUARE_BRACKET;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 173 "scanner.ll"
return T_LEFT_PARANTHESIS;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 174 "scanner.ll"
return T_RIGHT_PARANTHESIS;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 175 "scanner.ll"
return T_COLON;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 176 "scanner.ll"
return T_COMMA;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 177 "scanner.ll"
return T_SEMICOLON;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 178 "scanner.ll"
return T_EQUAL;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 179 "scanner.ll"
return T_NOTEQUAL;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 180 "scanner.ll"
return T_NOT;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 181 "scanner.ll"
return T_ASSIGN;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 182 "scanner.ll"
return T_SHIFTRIGHT;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 183 "scanner.ll"
return T_SHIFTLEFT;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 184 "scanner.ll"
return T_PLUS_SIGN;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 185 "scanner.ll"
return T_MINUS_SIGN;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 186 "scanner.ll"
return T_ASTERISK;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 187 "scanner.ll"
return T_SOLIDUS;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 188 "scanner.ll"
return T_PERCENT_SIGN;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 189 "scanner.ll"
return T_TILDE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 190 "scanner.ll"
return T_VERTICAL_LINE;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 191 "scanner.ll"
return T_CIRCUMFLEX;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 192 "scanner.ll"
return T_AMPERSAND;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 193 "scanner.ll"
return T_LESS_OR_EQUAL;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 194 "scanner.ll"
return T_GREATER_OR_EQUAL;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 195 "scanner.ll"
return T_LESS_THAN_SIGN;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 196 "scanner.ll"
return T_GREATER_THAN_SIGN;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 197 "scanner.ll"
return T_MEMBER;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 199 "scanner.ll"
return T_CONST;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 200 "scanner.ll"
return T_FALSE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 201 "scanner.ll"
return T_TRUE;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 202 "scanner.ll"
return T_STRUCT;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 203 "scanner.ll"
return T_SWITCH;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 204 "scanner.ll"
return T_CASE;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 205 "scanner.ll"
return T_DEFAULT;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 206 "scanner.ll"
return T_ENUM;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 207 "scanner.ll"
return T_IN;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 208 "scanner.ll"
return T_OUT;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 209 "scanner.ll"
return T_INTERFACE;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 210 "scanner.ll"
return T_CLASS;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 211 "scanner.ll"
return T_NEW;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 212 "scanner.ll"
return T_DELETE;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 213 "scanner.ll"
return T_WHILE;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 214 "scanner.ll"
return T_DO;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 215 "scanner.ll"
return T_FOR;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 216 "scanner.ll"
return T_IF;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 217 "scanner.ll"
return T_ELSE;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 218 "scanner.ll"
return T_MAIN;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 219 "scanner.ll"
return T_FOREACH;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 220 "scanner.ll"
return T_RETURN;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 221 "scanner.ll"
return T_SIGNAL;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 222 "scanner.ll"
return T_EMIT;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 223 "scanner.ll"
return T_IMPORT;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 224 "scanner.ll"
return T_VAR;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 225 "scanner.ll"
return T_READONLY;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 226 "scanner.ll"
return T_ATTRIBUTE;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 227 "scanner.ll"
return T_INOUT;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 228 "scanner.ll"
return T_RAISES;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 229 "scanner.ll"
return T_TRY;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 230 "scanner.ll"
return T_CATCH;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 231 "scanner.ll"
return T_RAISE;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 233 "scanner.ll"
return T_INCR;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 234 "scanner.ll"
return T_DECR;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 235 "scanner.ll"
return T_SCOPE; 
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 239 "scanner.ll"
{
			  yylval.ident = new QString( yytext );
			  return T_IDENTIFIER;
			}
	YY_BREAK
case 78:
#line 244 "scanner.ll"
case 79:
#line 245 "scanner.ll"
case 80:
#line 246 "scanner.ll"
case 81:
#line 247 "scanner.ll"
case 82:
YY_RULE_SETUP
#line 247 "scanner.ll"
{
			  yylval._float = ascii_to_longdouble( yytext );
			  return T_FLOATING_PT_LITERAL;
			}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 251 "scanner.ll"
{ 
			  yylval._int = ascii_to_longlong( 10, yytext );
			  return T_INTEGER_LITERAL;
			}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 255 "scanner.ll"
{
			  yylval._int = ascii_to_longlong( 8, yytext );
			  return T_INTEGER_LITERAL;
			}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 259 "scanner.ll"
{
			  yylval._int = ascii_to_longlong( 16, yytext + 2 );
			  return T_INTEGER_LITERAL;
			}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 263 "scanner.ll"
{
                          QCString s( yytext );
	                  s = s.mid( 1, s.length() - 2 );
			  yylval._char = translate_char( s );
			  return T_CHARACTER_LITERAL;
			}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 269 "scanner.ll"
{
                          QString s( yytext );
                          yylval._str = new QString( s.mid( 1, s.length() - 2 ) );
			  return T_STRING_LITERAL;
			}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 274 "scanner.ll"
{
                          return T_UNKNOWN;
                        }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 278 "scanner.ll"
ECHO;
	YY_BREAK
#line 1459 "scanner.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_last_accepting_cpos;
				yy_current_state = yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 271 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 271 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 270);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 278 "scanner.ll"


void kscriptInitFlex( const char *_code )
{
   yy_switch_to_buffer( yy_scan_string( _code ) );
}
