#line 2 "scanner.cc"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 91
#define YY_END_OF_BUFFER 92
static yyconst short int yy_accept[257] =
    {   0,
        0,    0,   92,   90,    1,    2,   24,   90,   90,   90,
       32,   37,   90,   17,   18,   30,   28,   20,   29,   43,
       31,   86,   85,   19,   21,   41,   25,   42,   79,   79,
       79,   15,   16,   36,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   13,   35,
       14,   33,   23,    0,   89,    0,    0,    6,    4,    0,
        0,   38,    0,    0,   76,   44,   77,   83,    3,    0,
        0,   86,    0,    0,    0,   87,   85,   78,   27,   39,
       22,    0,   40,   26,    0,    9,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   60,   79,   79,   79,   79,

       79,   79,   62,   79,   55,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   34,    0,    0,    4,    0,
        9,   88,    0,    0,    0,    3,    0,    0,   82,    0,
       81,   87,    0,    0,    0,    0,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   61,   79,
       79,   79,   79,   56,   79,   79,   79,   79,   79,   79,
       72,   70,   79,    0,    0,    0,    0,    0,    0,   84,
        0,   10,    0,   81,    0,    8,    0,    0,    0,    0,
       79,   47,   52,   79,   79,   79,   79,   79,   63,   68,
       54,   79,   79,   75,   79,   79,   64,   79,   79,   79,

       79,   79,   49,   79,    0,    0,    0,    0,    0,    0,
       80,    0,    0,    0,    0,   12,   46,   73,   57,   45,
       79,   79,   79,   79,   79,   71,   74,   79,   79,   79,
       79,   59,    0,    0,    0,    0,    7,    0,   79,   58,
       48,   79,   69,   66,   67,   50,   51,    0,    0,   11,
        7,   53,   65,    0,    5,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   30,   30,   30,   31,   32,
       33,   33,   33,   33,   33,   34,   33,   33,   33,   33,
       33,   35,   36,   37,   38,   33,   33,   39,   33,   33,
       40,   41,   42,   43,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   54,   54,   55,   56,   57,
       58,   59,   54,   60,   61,   62,   63,   64,   65,   66,
       67,   54,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[72] =
    {   0,
        1,    2,    3,    1,    4,    5,    1,    6,    1,    1,
        7,    1,    1,    1,    1,    1,    1,    4,    1,    8,
        8,    9,    1,    1,    1,    1,    1,    5,   10,   10,
       10,   10,   11,   11,   11,   11,   11,   11,   12,    1,
        5,    1,    1,   13,    8,    8,    9,    9,    9,    8,
       14,   14,   14,   14,   14,   14,   15,   14,   14,   15,
       14,   15,   14,   15,   14,   15,   14,    1,    1,    1,
        1
    } ;

static yyconst short int yy_base[277] =
    {   0,
        0,    0,  677,  678,  678,  678,  650,   66,   70,    0,
      678,  665,  633,  678,  678,  678,   59,  678,  656,   56,
      653,   74,   79,  648,  678,   55,   56,   60,  136,  641,
      634,  678,  678,  678,    0,  196,   48,   40,   59,   59,
       52,  623,  604,   73,   59,  606,  620,  612,  678,  594,
      678,  678,  678,   84,  678,  110,  659,  678,  658,   85,
      112,  678,  649,  139,  678,  678,  678,  115,    0,  651,
      130,  218,  232,  121,  240,  277,  254,  678,  678,  678,
      678,  158,  678,  678,  133,  186,    0,    0,    0,  624,
      619,   81,  611,  598,  160,    0,  593,  600,  589,  596,

      590,  591,    0,  589,  589,  593,  583,  591,  581,  591,
      581,  587,  157,  579,  585,  678,  245,    0,  634,  176,
      191,  678,  127,    0,  226,    0,  628,  248,  269,  257,
      299,    0,  269,  203,  616,  626,  597,  601,  582,  583,
      568,  567,  582,  544,  543,  529,  511,  505,  516,  483,
      480,  474,  466,    0,  458,  455,  459,  452,  452,  462,
        0,    0,  438,  290,  326,  261,  272,  481,  293,  313,
      316,  319,  344,  323,  261,  678,  487,  275,  481,  360,
      457,    0,    0,  433,  412,  405,  403,  403,    0,    0,
        0,  408,  406,    0,  390,  356,    0,  368,  354,  368,

      365,  364,    0,  361,  322,  343,  298,  398,  400,  330,
      357,  350,  351,  404,  365,  368,    0,    0,    0,    0,
      351,  356,  355,  347,  300,    0,    0,  303,  298,  267,
      253,    0,  239,  279,  375,  374,  220,  160,   99,    0,
        0,   59,    0,    0,    0,    0,    0,   88,  378,  381,
      678,    0,    0,   80,  678,  678,  415,  430,  436,  448,
      460,  468,  479,  494,  505,  520,  530,  535,  538,  548,
      558,  564,  574,  584,  596,  611
    } ;

static yyconst short int yy_def[277] =
    {   0,
      256,    1,  256,  256,  256,  256,  256,  257,  258,  259,
      256,  256,  260,  256,  256,  256,  256,  256,  256,  256,
      256,  261,  261,  256,  256,  256,  256,  256,  256,   29,
       29,  256,  256,  256,  262,   29,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,  256,  256,
      256,  256,  256,  257,  256,  263,  258,  256,  264,  258,
      259,  256,  256,  265,  256,  256,  256,  256,  266,  267,
      256,  261,  261,  261,  261,  261,  261,  256,  256,  256,
      256,  256,  256,  256,  256,   36,   29,  262,   36,   29,
       29,   36,   36,   36,   36,   36,   36,   36,   36,   36,

       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,  256,  257,  268,  264,  258,
      256,  256,  256,  269,  256,  266,  267,  267,  256,  256,
      261,   76,  256,  270,  256,  271,   29,   29,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,  257,  257,  258,  256,  272,  256,  256,
      256,  256,  256,  256,  270,  256,  270,  273,  271,  271,
       29,   29,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,

       36,   36,   36,   36,  257,  257,  258,  256,  274,  256,
      256,  273,  275,  273,  256,  256,   29,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,  258,  274,  274,  275,  256,  275,   36,   36,
       36,   36,   36,   36,   36,   36,   36,  276,  256,  256,
      256,   36,   36,  276,  256,    0,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256
    } ;

static yyconst short int yy_nxt[750] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   23,   24,   25,   26,   27,   28,    4,   29,   29,
       29,   30,   29,   29,   29,   29,   31,   29,   29,   32,
        4,   33,   34,   35,   36,   36,   37,   38,   39,   40,
       36,   36,   41,   36,   36,   42,   36,   43,   36,   44,
       45,   46,   36,   47,   48,   36,   36,   49,   50,   51,
       52,   55,   58,   65,   59,   68,   68,   68,   70,   79,
       80,   81,  255,   70,   66,   83,   84,   58,   95,   55,
      255,   71,   92,   72,   72,   73,   71,   96,   77,   77,

       77,  103,   93,  100,   75,   94,   56,  104,  105,   75,
      253,  110,   76,   97,   98,   99,  101,  108,  102,   85,
      111,  109,   75,  112,   56,   70,   82,   75,   60,  117,
      117,  121,  121,  121,   68,   68,   68,  122,  256,   76,
       70,  139,  140,   85,  120,  125,  167,  167,  118,  129,
      129,  129,  121,  121,  121,   86,   86,   86,  123,  123,
      252,  133,  256,  125,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,  118,  134,  124,   58,   88,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,

       89,   89,   89,  256,  124,   86,   86,   86,  136,  143,
      121,  121,  121,  136,  144,   89,   89,   89,  135,  160,
      166,  176,   70,  161,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   71,   70,   72,   72,   73,
      169,   58,  169,  177,   70,  170,  170,  170,   75,   71,
       55,   73,   73,   73,  130,  171,  130,  256,   70,  131,
      131,  131,   75,   58,  164,  164,   75,  172,  172,  172,
      251,   71,  133,   77,   77,   77,  174,  174,  174,  176,
       75,   70,  122,  248,   75,   56,  256,  134,  129,  129,
      129,   63,   63,  213,  256,   55,  132,  132,  132,  173,

       58,  177,   75,   70,  247,  132,  132,  132,  132,  205,
      205,  207,  170,  170,  170,  214,  256,  173,  131,  131,
      131,  132,  132,  132,  132,  132,  132,   55,  246,  135,
       56,   55,  170,  170,  170,  172,  172,  172,  172,  172,
      172,  209,  174,  174,  174,  206,  206,  206,   55,  211,
      211,  211,  245,  233,  206,  206,  206,  206,  210,  244,
      210,  243,   56,  211,  211,  211,   56,  215,  213,  237,
      206,  206,  206,  206,  206,  206,  211,  211,  211,  216,
      216,  216,  249,   56,  216,  216,  216,  216,  216,  216,
      214,  238,  237,  242,  250,  250,  250,  250,  250,  250,

      250,  250,  250,  241,  240,  239,  256,  234,  122,  232,
      231,  230,  229,  228,  238,   54,  227,  226,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   61,   61,   61,   63,  225,
      224,   63,   63,   63,  223,   63,   63,   63,   63,   63,
       63,   63,   63,   74,  222,  221,  220,   74,   74,   74,
       74,   74,  219,   74,   74,   88,   88,   88,   88,   88,
       88,   88,   88,   54,  218,   54,   54,  217,  256,  256,
       54,  122,  204,   54,  119,  119,  119,  119,  119,  119,

      119,  119,  119,  119,  119,  119,  119,  119,  119,   63,
      203,   63,   63,  202,  201,  200,   63,  199,  198,   63,
      126,  126,  197,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  128,  196,  195,  194,  128,
      128,  128,  165,  165,  165,  168,  168,  168,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  180,  193,  192,  191,  180,  180,  180,
      208,  208,  208,  208,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  235,
      190,  189,  188,  235,  235,  235,  236,  236,  236,  236,

      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  187,  186,  185,  184,
      183,  182,  181,  179,  178,  256,   58,  163,  162,  159,
      158,  157,  156,  155,  154,  153,  152,  151,  150,  149,
      148,  147,  146,  145,  142,  141,  138,  137,  127,  122,
       58,   58,  116,  115,  114,  113,  107,  106,   91,   90,
       78,   69,   67,   64,   62,   53,  256,    3,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,

      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256
    } ;

static yyconst short int yy_chk[750] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    8,    9,   17,    9,   20,   20,   20,   22,   26,
       26,   27,  254,   23,   17,   28,   28,   60,   38,   54,
      248,   22,   37,   22,   22,   22,   23,   38,   23,   23,

       23,   41,   37,   40,   22,   37,    8,   41,   41,   23,
      242,   45,   22,   39,   39,   39,   40,   44,   40,   61,
       45,   44,   22,   45,   54,   74,   27,   23,    9,   56,
       56,   61,   61,   61,   68,   68,   68,  123,   74,   22,
       29,   92,   92,   29,   60,   68,  123,  123,   56,   71,
       71,   71,   85,   85,   85,   29,   29,   29,   64,   64,
      239,   82,  238,   68,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   56,   82,   64,  120,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,

       29,   29,   29,   36,   64,   86,   86,   86,   86,   95,
      121,  121,  121,  121,   95,   36,   36,   36,   82,  113,
      120,  134,   72,  113,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   72,   73,   72,   72,   72,
      125,  233,  125,  134,   75,  125,  125,  125,   72,   73,
      117,   73,   73,   73,   75,  128,   75,   75,   77,   75,
       75,   75,   73,  166,  117,  117,   72,  128,  128,  128,
      237,   77,  133,   77,   77,   77,  130,  130,  130,  175,
       73,   76,  167,  233,   77,  117,  234,  133,  129,  129,
      129,  167,  167,  178,   76,  164,   76,   76,   76,  129,

      207,  175,   77,  131,  231,   76,   76,   76,   76,  164,
      164,  166,  169,  169,  169,  178,  131,  129,  131,  131,
      131,   76,   76,   76,   76,   76,   76,  205,  230,  133,
      164,  165,  170,  170,  170,  171,  171,  171,  172,  172,
      172,  172,  174,  174,  174,  165,  165,  165,  206,  210,
      210,  210,  229,  207,  165,  165,  165,  165,  173,  228,
      173,  225,  205,  173,  173,  173,  165,  180,  212,  213,
      165,  165,  165,  165,  165,  165,  211,  211,  211,  180,
      180,  180,  235,  206,  215,  215,  215,  216,  216,  216,
      212,  213,  236,  224,  235,  235,  235,  249,  249,  249,

      250,  250,  250,  223,  222,  221,  214,  209,  208,  204,
      202,  201,  200,  199,  236,  257,  198,  196,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  259,  259,  259,  260,  195,
      193,  260,  260,  260,  192,  260,  260,  260,  260,  260,
      260,  260,  260,  261,  188,  187,  186,  261,  261,  261,
      261,  261,  185,  261,  261,  262,  262,  262,  262,  262,
      262,  262,  262,  263,  184,  263,  263,  181,  179,  177,
      263,  168,  163,  263,  264,  264,  264,  264,  264,  264,

      264,  264,  264,  264,  264,  264,  264,  264,  264,  265,
      160,  265,  265,  159,  158,  157,  265,  156,  155,  265,
      266,  266,  153,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  267,  152,  151,  150,  267,
      267,  267,  268,  268,  268,  269,  269,  269,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  271,  149,  148,  147,  271,  271,  271,
      272,  272,  272,  272,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  274,
      146,  145,  144,  274,  274,  274,  275,  275,  275,  275,

      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  143,  142,  141,  140,
      139,  138,  137,  136,  135,  127,  119,  115,  114,  112,
      111,  110,  109,  108,  107,  106,  105,  104,  102,  101,
      100,   99,   98,   97,   94,   93,   91,   90,   70,   63,
       59,   57,   50,   48,   47,   46,   43,   42,   31,   30,
       24,   21,   19,   13,   12,    7,    3,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,

      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.ll"
#define INITIAL 0
#line 2 "scanner.ll"

#define YY_NO_UNPUT
#include <stdlib.h>
#include <ctype.h>

#include "kscript_parsenode.h"
#include "kscript_types.h"
#include "kscript_synext.h"

#ifndef KDE_USE_FINAL
#include "yacc.cc.h"
#endif

extern int idl_line_no;

static bool s_kspread;

#include <qstring.h>

static KScript::Long ascii_to_longlong( long base, const char *s )
{
  KScript::Long ll = 0;
  while( *s != '\0' ) {
    char c = *s++;
    if( c >= 'a' )
      c -= 'a' - 'A';
    c -= '0';
    if( c > 9 )
      c -= 'A' - '0' - 10;
    ll = ll * base + c;
  }
  return ll;
}

static KScript::Double ascii_to_longdouble (const char *s)
{
  KScript::Double d;
#ifdef HAVE_SCANF_LF
  sscanf (s, "%Lf", &d);
#else
  /*
   * this is only an approximation and will probably break fixed<>
   * parameter calculation on systems where
   * sizeof(double) < sizeof(long double). but fortunately all
   * systems where scanf("%Lf") is known to be broken (Linux/Alpha
   * and HPUX) have sizeof(double) == sizeof(long double).
   */
  d = strtod (s, NULL);
#endif
  return d;
}

static char translate_char( const char *s )
{
  char c = *s++;

  if( c != '\\' )
    return c;
  c = *s++;
  switch( c ) {
  case 'n':
    return '\n';
  case 't':
    return '\t';
  case 'v':
    return '\v';
  case 'b':
    return '\b';
  case 'r':
    return '\r';
  case 'f':
    return '\f';
  case 'a':
    return '\a';
  case '\\':
    return '\\';
  case '?':
    return '\?';
  case '\'':
    return '\'';
  case '"':
    return '"';
  case 'x':
  case 'X':
    return (char) ascii_to_longlong( 16, s );
  default:
    // Gotta be an octal
    return (char) ascii_to_longlong( 8, s );
  }
}

static QChar translate_unichar( const QChar *s )
{
  QChar c = *s++;

  if( c != '\\' )
    return c;
  c = *s++;
  switch( c.latin1() ) {
  case 'n':
    return '\n';
  case 't':
    return '\t';
  case 'v':
    return '\v';
  case 'b':
    return '\b';
  case 'r':
    return '\r';
  case 'f':
    return '\f';
  case 'a':
    return '\a';
  case '\\':
    return '\\';
  case '?':
    return '\?';
  case '\'':
    return '\'';
  case '"':
    return '"';
  default:
    return c;
  }
}

static void translate_string( QString& str )
{
	int pos = 0;
	while( ( pos = str.find( '\\', pos ) ) != -1 )
	{
		QChar ch = translate_unichar( str.unicode() + pos );
		str.replace( pos, 2, &ch, 1 );
	}
}

/*--------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------*/
#line 761 "scanner.cc"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 171 "scanner.ll"


#line 915 "scanner.cc"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 257 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 256 );
		yy_cp = yy_last_accepting_cpos;
		yy_current_state = yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 173 "scanner.ll"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 174 "scanner.ll"
idl_line_no++;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 175 "scanner.ll"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 176 "scanner.ll"
;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 177 "scanner.ll"
{
			  yylval._str = new QString( yytext );
                          idl_line_no++;
                          return T_PRAGMA;
                        }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 182 "scanner.ll"
;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 184 "scanner.ll"
{
						  const char *c = yytext + 2;
						  while( isspace( *c ) ) ++c;
			 			  yylval.ident = new QString( c );
						  return T_SUBST;
						}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 190 "scanner.ll"
{
						  const char *c = yytext + 2;
						  while( isspace( *c ) ) ++c;
			 			  yylval.ident = new QString( c );
						  return T_MATCH;
						}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 198 "scanner.ll"
{
			  if ( !s_kspread )
			  {
			  	yylval.ident = new QString( yytext );
			  	return T_IDENTIFIER;
			  }
                          yylval._str = new QString( yytext );
			  return T_CELL;
		       };
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 208 "scanner.ll"
{
			  if ( !s_kspread )
			  {
			  	yylval.ident = new QString( yytext );
			  	return T_IDENTIFIER;
			  }
                          yylval._str = new QString( yytext );
			  return T_CELL;
		       };
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 218 "scanner.ll"
{
			  if ( !s_kspread )
			  {
			  	yylval.ident = new QString( yytext );
			  	return T_IDENTIFIER;
			  }
                          yylval._str = new QString( yytext );
			  return T_RANGE;
		       };
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 228 "scanner.ll"
{
			  if ( !s_kspread )
			  {
			  	yylval.ident = new QString( yytext );
			  	return T_IDENTIFIER;
			  }
                          yylval._str = new QString( yytext );
			  return T_RANGE;
		       };
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 238 "scanner.ll"
return T_LEFT_CURLY_BRACKET;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 239 "scanner.ll"
return T_RIGHT_CURLY_BRACKET;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 240 "scanner.ll"
return T_LEFT_SQUARE_BRACKET;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 241 "scanner.ll"
return T_RIGHT_SQUARE_BRACKET;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 242 "scanner.ll"
return T_LEFT_PARANTHESIS;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 243 "scanner.ll"
return T_RIGHT_PARANTHESIS;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 244 "scanner.ll"
return T_COLON;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 245 "scanner.ll"
return T_COMMA;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 246 "scanner.ll"
return T_SEMICOLON;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 247 "scanner.ll"
return T_EQUAL;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 248 "scanner.ll"
return T_NOTEQUAL;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 249 "scanner.ll"
return T_NOT;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 250 "scanner.ll"
return T_ASSIGN;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 251 "scanner.ll"
return T_SHIFTRIGHT;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 252 "scanner.ll"
return T_SHIFTLEFT;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 253 "scanner.ll"
return T_PLUS_SIGN;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 254 "scanner.ll"
return T_MINUS_SIGN;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 255 "scanner.ll"
return T_ASTERISK;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 256 "scanner.ll"
return T_SOLIDUS;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 257 "scanner.ll"
return T_PERCENT_SIGN;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 258 "scanner.ll"
return T_TILDE;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 259 "scanner.ll"
return T_OR;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 260 "scanner.ll"
return T_VERTICAL_LINE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 261 "scanner.ll"
return T_CIRCUMFLEX;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 262 "scanner.ll"
return T_AMPERSAND;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 263 "scanner.ll"
return T_AND;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 264 "scanner.ll"
return T_LESS_OR_EQUAL;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 265 "scanner.ll"
return T_GREATER_OR_EQUAL;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 266 "scanner.ll"
return T_LESS_THAN_SIGN;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 267 "scanner.ll"
return T_GREATER_THAN_SIGN;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 268 "scanner.ll"
return T_MEMBER;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 269 "scanner.ll"
return T_PLUS_ASSIGN;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 271 "scanner.ll"
return T_CONST;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 272 "scanner.ll"
return T_FALSE;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 273 "scanner.ll"
return T_TRUE;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 274 "scanner.ll"
return T_FALSE;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 275 "scanner.ll"
return T_TRUE;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 276 "scanner.ll"
return T_STRUCT;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 277 "scanner.ll"
return T_SWITCH;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 278 "scanner.ll"
return T_CASE;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 279 "scanner.ll"
return T_DEFAULT;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 280 "scanner.ll"
return T_ENUM;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 281 "scanner.ll"
return T_IN;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 282 "scanner.ll"
return T_OUT;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 283 "scanner.ll"
return T_CLASS;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 284 "scanner.ll"
return T_DELETE;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 285 "scanner.ll"
return T_WHILE;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 286 "scanner.ll"
return T_DO;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 287 "scanner.ll"
return T_FOR;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 288 "scanner.ll"
{
				if ( !s_kspread )
					return T_IF;
			  	yylval.ident = new QString( yytext );
			  	return T_IDENTIFIER;
			}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 294 "scanner.ll"
return T_ELSE;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 295 "scanner.ll"
return T_MAIN;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 296 "scanner.ll"
return T_FOREACH;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 297 "scanner.ll"
return T_RETURN;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 298 "scanner.ll"
return T_SIGNAL;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 299 "scanner.ll"
return T_EMIT;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 300 "scanner.ll"
return T_IMPORT;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 301 "scanner.ll"
return T_VAR;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 302 "scanner.ll"
return T_INOUT;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 303 "scanner.ll"
return T_TRY;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 304 "scanner.ll"
return T_CATCH;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 305 "scanner.ll"
return T_RAISE;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 306 "scanner.ll"
return T_FROM;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 308 "scanner.ll"
return T_INCR;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 309 "scanner.ll"
return T_DECR;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 310 "scanner.ll"
return T_SCOPE;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 314 "scanner.ll"
{
			  yylval.ident = new QString( yytext );
			  return T_IDENTIFIER;
			}
	YY_BREAK
case 80:
#line 319 "scanner.ll"
case 81:
#line 320 "scanner.ll"
case 82:
#line 321 "scanner.ll"
case 83:
#line 322 "scanner.ll"
case 84:
YY_RULE_SETUP
#line 322 "scanner.ll"
{
			  yylval._float = ascii_to_longdouble( yytext );
			  return T_FLOATING_PT_LITERAL;
			}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 326 "scanner.ll"
{
			  yylval._int = ascii_to_longlong( 10, yytext );
			  return T_INTEGER_LITERAL;
			}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 330 "scanner.ll"
{
			  yylval._int = ascii_to_longlong( 8, yytext );
			  return T_INTEGER_LITERAL;
			}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 334 "scanner.ll"
{
			  yylval._int = ascii_to_longlong( 16, yytext + 2 );
			  return T_INTEGER_LITERAL;
			}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 338 "scanner.ll"
{
                          QCString s( yytext );
	                  s = s.mid( 1, s.length() - 2 );
			  yylval._char = translate_char( s );
			  return T_CHARACTER_LITERAL;
			}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 344 "scanner.ll"
{
                          QString s( yytext );
                          yylval._str = new QString( s.mid( 1, s.length() - 2 ) );
			  if ( yylval._str->isNull() )
				*(yylval._str) = "";
			  translate_string( *(yylval._str) );
			  return T_STRING_LITERAL;
			}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 352 "scanner.ll"
{
                          return T_UNKNOWN;
                        }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 356 "scanner.ll"
ECHO;
	YY_BREAK
#line 1517 "scanner.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_last_accepting_cpos;
				yy_current_state = yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 257 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 257 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 256);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 356 "scanner.ll"


void kscriptInitFlex( const char *_code, int extension )
{
   if ( extension == KSCRIPT_EXTENSION_KSPREAD )
	s_kspread = TRUE;
   else
	s_kspread = FALSE;
   yy_switch_to_buffer( yy_scan_string( _code ) );
}
