/***************************************************************************
                          ktablesview.h  -  description                              
                             -------------------                                         
    begin                : Mið Júl  7 17:04:49 CEST 1999
                                           
    copyright            : (C) 1999 by Ørn E. Hansen                         
    email                : hanseno@mail.bip.net                                     
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   * 
 *                                                                         *
 ***************************************************************************/


#ifndef KTABLESVIEW_H
#define KTABLESVIEW_H

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif 

// include files for Qt
#include <qwidget.h>

#include <opView.h>
#include <opDocument.h>

#include <kdbrecordview.h>

class KtablesDoc;
class kdtDataSet;

/** The KtablesView class provides the view widget for the KtablesApp instance.	
	* The View instance inherits QWidget as a base class and represents the view object of a KTMainWindow. As KtablesView is part of the
	* docuement-view model, it needs a reference to the document object connected with it by the KtablesApp class to manipulate and display
	* the document structure provided by the KtablesDoc class.
 	* 	
 	* @author Source Framework Automatically Generated by KDevelop, (c) The KDevelop Team.
	* @version KDevelop version 0.4 code generation
 	*/
class KtablesView : public kdbRecordView, public OPViewIf
{
  Q_OBJECT

public:
  /** Constructor for the main view */
  KtablesView(kdbDataSet *,OPDocumentIf *,QWidget* parent = 0, const char* name=0);
  /** Destructor for the main view */
  ~KtablesView();

  void insertRow();
  void removeRow();
  void commit();
  void reScanTable();

	/** returns a pointer to the document connected to the view instance. Mind that this method requires a KtablesApp instance as a parent
		* widget to get to the window document pointer by calling the KtablesApp::getDocument() method.
		*
		* @see KtablesApp#getDocument
		*/
	KtablesDoc* getDocument() const;
	
  /** contains the implementation for printing functionality */
	void print(QPrinter* m_pPrinter);
	
	void setTable(const QString&);
		
signals:
	void signalMsg(const char *);
	
private:
	OPDocumentIf *_doc;
	
};

#endif // KTABLESVIEW_H
























