/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Thu Jul 8 02:35:04 1999

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/

#include <qtooltip.h>
#include <qwhatsthis.h>

#include <kapp.h>
#include <klocale.h>

#include "tableselect.h"

void  TableSelect::initDialog(){
	this->resize(400,300);
	_available = new QListBox(this,"selection");
	_available->setGeometry(20,30,140,190);
	QWhatsThis* whatsThis = new QWhatsThis( _available );
	whatsThis->add( _available, i18n( "a list of tables, available for a query." ) );
	QToolTip::add(_available,i18n("tables available"));
	connect(_available,SIGNAL(selected(int)),SLOT(acceptItem(int)));

	_selected = new QListBox(this,"queryTables");
	_selected->setGeometry(240,30,140,190);
        whatsThis = new QWhatsThis( _selected);
        whatsThis->add( _selected, i18n( "list of selected tables to query" ) );
	QToolTip::add(_selected,i18n("tables to query"));
	connect(_selected,SIGNAL(selected(int)),SLOT(removeItem(int)));

	QLabel_1 = new QLabel(this,"NoName");
	QLabel_1->setGeometry(20,10,100,20);
	QLabel_1->setText(i18n("Table list"));

	QLabel_2 = new QLabel(this,"NoName");
	QLabel_2->setGeometry(240,10,100,20);
	QLabel_2->setText(i18n("Selected tables"));

	QPushButton_1 = new QPushButton(this,"butSelect");
	QPushButton_1->setGeometry(175,60,50,25);
        whatsThis = new QWhatsThis( QPushButton_1 );
        whatsThis->add( QPushButton_1, i18n( "move table from available to selected" ) );
	QToolTip::add(QPushButton_1,i18n("move to selected"));
	QPushButton_1->setText(i18n(">>"));
	connect(QPushButton_1,SIGNAL(clicked()),SLOT(acceptItem()));

	QPushButton_2 = new QPushButton(this,"butRemove");
	QPushButton_2->setGeometry(175,100,50,25);
        whatsThis = new QWhatsThis( QPushButton_2 );
        whatsThis->add( QPushButton_2, i18n( "Remove table from selected and put back into available." ) );
	QToolTip::add(QPushButton_2,i18n("remove table"));
	QPushButton_2->setText(i18n("<<"));
	connect(QPushButton_1,SIGNAL(clicked()),SLOT(removeItem()));

	QPushButton_3 = new QPushButton(this,"butOk");
	QPushButton_3->setGeometry(20,250,100,25);
        whatsThis = new QWhatsThis( QPushButton_3 );
        whatsThis->add( QPushButton_3, i18n( "Accept the selected table selection" ) );
	QToolTip::add(QPushButton_3,i18n("Accept list"));
	QPushButton_3->setText(i18n("&OK"));
	connect(QPushButton_3,SIGNAL(clicked()),SLOT(accept()));

	QPushButton_4 = new QPushButton(this,"butCancel");
	QPushButton_4->setGeometry(290,250,100,25);
        whatsThis = new QWhatsThis( QPushButton_4 );
        whatsThis->add( QPushButton_4, i18n( "Reject the selected table selection." ) );
	QToolTip::add(QPushButton_4,i18n("Reject selection."));
	QPushButton_4->setText(i18n("&Cancel"));
	connect(QPushButton_4,SIGNAL(clicked()),SLOT(reject()));

}


