#ifndef FAKE_KDECORE_EXPORT_H
#define FAKE_KDECORE_EXPORT_H

#include <kdemacros.h>

#define KDECORE_EXPORT Q_DECL_EXPORT
//#define KARCHIVE_EXPORT

#ifndef KDECORE_EXPORT_DEPRECATED
    #define KDECORE_EXPORT_DEPRECATED KDE_DEPRECATED KDECORE_EXPORT
#endif

#endif
