# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

TEMPLATE = subdirs
CONFIG += release \
warn_on
OBJECTS_DIR = .obj
UI_DIR = .ui
MOC_DIR = .moc
MAKEFILE = Makefile.qt
SUBDIRS += lib \
           kudesigner_qt \
           kudesigner_lib \
           kudesigner_qt2 \
           shell_qt2 
