#ifndef __kformula_idl__
#define __kformula_idl__

#include <parts.idl>

module KFormula
{
       interface View : OPParts::View
	{
	  slot void newView();
	  slot void addB0();
	  slot void addB1();		
	  slot void addB4();	
	  slot void addB4bis();	
	  slot void addB3();
	  slot void addB2();
	  slot void addB5();
	  slot void reduce();
	  slot void enlarge();
	  slot void reduceRecur();
	  slot void enlargeRecur();
	  slot void enlargeAll();
	  slot void setGreek();
	  slot void addCh1();
	  slot void addCh2();
	  slot void addCh3();

	};

	interface Document : OPParts::Document
	{
	};

	interface Factory : OPParts::Factory
	{
	};
};

#endif

