# Generated automatically from Makefile.in by configure.

INCDIR		=	-I$(QTDIR)/include -I$(KDEDIR)/include  -I..
CXXFLAGS	=	$(INCDIR) -g 
LDFLAGS		=	-L$(KDEDIR)/lib -L/usr/X11/lib -L$(QTDIR)/lib -L.. -lkdeui -lkdecore -lX11 -lXext -ldl -lqt -lkofficeui -lkofficecore -lmico2.0.5 -lkfile -lkfm -lkom -lop -lkoml
CXX		=	g++
MOC		=	/usr/bin/moc

####### Files

SOURCES	=	test.cc
HEADERS =	test.h
OBJECTS =	test.o
SRCMETA =	test.moc
TARGET	=	test

####### Implicit rules

.SUFFIXES: .cc

.cc.o:
	$(CXX) -c $(CXXFLAGS) -DSTDC_HEADERS -DHAVE_UNISTD_H $(INCDIR) $<

%.moc: %.h
	$(MOC) $< -o $@      

####### Build rules

all: $(TARGET)

$(TARGET): $(SRCMETA) $(OBJECTS)
	$(CXX) $(OBJECTS) -o $(TARGET) $(LDFLAGS)

depend:
	@makedepend $(INCDIR) $(SOURCES) 2> /dev/null

showfiles:
	@echo $(SOURCES) $(HEADERS) Makefile

clean:
	-rm -f *.o *.bak *~ *% #*
	-rm -f $(SRCMETA) $(TARGET)

####### Meta objects

# DO NOT DELETE THIS LINE -- make depend depends on it.

test.o: test.h ../koPartSelectDia.h /usr/local/kde/include/koScanParts.h
test.o: /usr/lib/qt/include/qstring.h /usr/lib/qt/include/qarray.h
test.o: /usr/lib/qt/include/qgarray.h /usr/lib/qt/include/qshared.h
test.o: /usr/lib/qt/include/qglobal.h /usr/lib/qt/include/qgeneric.h
test.o: /usr/include/string.h /usr/include/features.h
test.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
test.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/stddef.h
test.o: /usr/lib/qt/include/qstrlist.h /usr/lib/qt/include/qlist.h
test.o: /usr/lib/qt/include/qglist.h /usr/lib/qt/include/qcollect.h
test.o: /usr/lib/qt/include/qdstream.h /usr/lib/qt/include/qiodev.h
test.o: /usr/local/kde/include/op_app.h /usr/lib/qt/include/qapp.h
test.o: /usr/lib/qt/include/qwidget.h /usr/lib/qt/include/qwindefs.h
test.o: /usr/lib/qt/include/qobjdefs.h /usr/lib/qt/include/qobject.h
test.o: /usr/lib/qt/include/qevent.h /usr/lib/qt/include/qrect.h
test.o: /usr/lib/qt/include/qsize.h /usr/lib/qt/include/qpoint.h
test.o: /usr/lib/qt/include/qpaintd.h /usr/lib/qt/include/qpalette.h
test.o: /usr/lib/qt/include/qcolor.h /usr/lib/qt/include/qcursor.h
test.o: /usr/lib/qt/include/qfont.h /usr/lib/qt/include/qfontmet.h
test.o: /usr/lib/qt/include/qfontinf.h /usr/local/kde/include/kom.h
test.o: /usr/local/kde/include/kom_app.h /usr/lib/qt/include/qsocknot.h
test.o: /usr/lib/qt/include/qtimer.h /usr/lib/qt/include/qintdict.h
test.o: /usr/lib/qt/include/qgdict.h /usr/local/kde/include/kapp.h
test.o: /usr/local/kde/include/kconfig.h /usr/local/kde/include/kconfigbase.h
test.o: /usr/local/kde/include/kconfigdata.h /usr/lib/qt/include/qdict.h
test.o: /usr/lib/qt/include/qtstream.h /usr/include/stdio.h
test.o: /usr/include/libio.h /usr/include/_G_config.h
test.o: /usr/include/gnu/types.h
test.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/stdarg.h
test.o: /usr/lib/gcc-lib/alpha-redhat-linux/2.7.2.3/include/va-alpha.h
test.o: /usr/include/stdio_lim.h /usr/lib/qt/include/qfile.h
test.o: /usr/local/kde/include/kdebug.h /usr/local/kde/include/klocale.h
test.o: /usr/local/kde/include/drag.h /usr/lib/qt/include/qpixmap.h
test.o: /usr/include/X11/X.h /usr/lib/qt/include/qpopmenu.h
test.o: /usr/lib/qt/include/qtablevw.h /usr/lib/qt/include/qframe.h
test.o: /usr/lib/qt/include/qmenudta.h
test.o: /usr/local/kde/include/topwidget_impl.h
test.o: /usr/local/kde/include/controls.h /opt/kde/idl/kom.h
test.o: /usr/local/kde/include/component_impl.h
test.o: /usr/local/kde/include/base_impl.h /usr/local/kde/include/kom_var.h
test.o: /usr/local/kde/include/control_frame.h
test.o: /usr/local/kde/include/control_impl.h /usr/local/kde/include/kwm.h
test.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h /usr/include/time.h
test.o: /usr/include/endian.h /usr/include/bytesex.h
test.o: /usr/include/sys/select.h /usr/include/selectbits.h
test.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
test.o: /usr/local/kde/include/part_impl.h /usr/local/kde/include/parts.h
test.o: /usr/local/kde/include/kmenubar.h /usr/lib/qt/include/qmenubar.h
test.o: /usr/local/kde/include/ktoolbar.h /usr/lib/qt/include/qbutton.h
test.o: /usr/local/kde/include/kcombo.h /usr/lib/qt/include/qcombo.h
test.o: /usr/local/kde/include/klined.h /usr/lib/qt/include/qlined.h
test.o: ../koPartSelectDia_data.h /usr/lib/qt/include/qdialog.h
test.o: /usr/lib/qt/include/qlistbox.h /usr/lib/qt/include/qpushbt.h
test.o: ../koAboutDia.h /usr/lib/qt/include/qlabel.h
test.o: /usr/lib/qt/include/qmsgbox.h /usr/lib/qt/include/qlayout.h
test.o: /usr/lib/qt/include/qgmanagr.h /usr/local/kde/include/kbuttonbox.h
test.o: ../koPageLayoutDia.h /usr/include/stdlib.h /usr/include/alloca.h
test.o: /usr/lib/qt/include/qtabdlg.h /usr/lib/qt/include/qgrpbox.h
test.o: /usr/lib/qt/include/qpainter.h /usr/lib/qt/include/qregion.h
test.o: /usr/lib/qt/include/qpen.h /usr/lib/qt/include/qbrush.h
test.o: /usr/lib/qt/include/qpntarry.h /usr/lib/qt/include/qwmatrix.h
test.o: /usr/local/kde/include/krestrictedline.h
