#ifndef __img_idl__
#define __img_idl__

#include <parts.idl>

module KSpread
{
	interface View : OPParts::View
	{
		slot void undo();
		slot void redo();
		slot void cutSelection();
		slot void copySelection();
		slot void paste();
		slot void editCell();
		slot void paperLayoutDlg();
		slot void togglePageBorders();
		slot void newView();
		slot void insertNewTable();
		slot void autoFill();
		slot void editGlobalScripts();
		slot void editLocalScripts();
		slot void reloadScripts();
		slot void helpAbout();
		slot void helpUsing();
		slot void deleteRow();
		slot void deleteColumn();
		slot void insertRow();
		slot void insertColumn();
		slot void bold();
		slot void italic();
		slot void moneyFormat();
		slot void percent();
		slot void alignLeft();
		slot void alignCenter();
		slot void alignRight();
		slot void multiRow();
		slot void precisionMinus();
		slot void precisionPlus();
		slot void insertChart();
		slot void insertTable();
		slot void insertImage();
		slot void insertObject();
		slot void fontSizeSelected( in string size );
		slot void fontSelected( in string font );
	};

	interface Document : OPParts::Document
	{
	};
};

#endif