# Generated automatically from Makefile.in by configure.

####### Python

PYTHONDIR =	/usr/local
PYTHONINC =     -I$(PYTHONDIR)/include/python1.5
PYTHONLIB =     -L$(PYTHONDIR)/lib/python1.5/config

# Libraries (must be in this order!)
PYTHONLIBS =    $(PYTHONLIB) -lpython1.5

INCDIR  =	-I$(QTDIR)/include -I$(KDEDIR)/include -I/usr/local/include $(PYTHONINC) -I$(KDEDIR)/idl
CXXFLAGS =	$(INCDIR) -g -fexceptions -O0
LDFLAGS =        -L$(KDEDIR)/lib -L/usr/X11/lib -lqt -lkdecore -lkdeui -lmico2.0.5 -lX11 -lXext -lkom -lop $(PYTHONLIBS) -lkfm -lkfile -lkoml -lkofficecore -lkofficeui
CXX     =       c++
MOC     =       /usr/bin/moc

####### Files

SOURCES =	kmetaedit.cc kspread_emacs.cc kspread_main.cc kspread_shell.cc kspread_doc.cc kspread.cc kspread_undo.cc kspread_view.cc kspread_tabbar.cc kspread_python.cc kspread_autofill.cc kspread_layout.cc kspread_map.cc kspread_dlg_layout.cc kspread_dlg_scripts.cc kspread_cell.cc kspread_table.cc
HEADERS =	kmetaedit.h kspread_emacs.h kspread_main.cc kspread_shell.h kspread_doc.h kspread.h kspread_undo.h kspread_view.h kspread_tabbar.h kspread_python.h kspread_autofill.h kspread_layout.h kspread_map.h kspread_dlg_layout.h kspread_dlg_scripts.h kspread_table.h kspread_cell.h
OBJECTS =	kmetaedit.o kspread_emacs.o kspread_main.o kspread_shell.o kspread_doc.o kspread.o kspread_undo.o kspread_view.o kspread_tabbar.o kspread_python.o kspread_autofill.o kspread_layout.o kspread_map.o kspread_dlg_layout.o kspread_dlg_scripts.o kspread_table.o kspread_cell.o
SRCMETA =	kspread_main.moc kspread_shell.moc kspread_doc.moc kspread_view.moc kspread_tabbar.moc kspread_table.moc kspread_dlg_layout.moc kspread_dlg_scripts.moc kspread_part.moc
IDL	=	kspread.idl
IDLH	=	kspread.h
TARGET	=	kspread

####### Install

INSTALL = install -m 0755 -s
INSTALL_SHELL = install -m 0755
INSTALL_DATA = install -m 0644
INSTALL_DIR = install -d -m 0755
INSTALL_DIR_PRIVATE = install -d -m 0700

####### Implicit rules

.SUFFIXES: .cc

.cc.o:
	$(CXX) -c $(CXXFLAGS) -DSTDC_HEADERS -DHAVE_UNISTD_H $(INCDIR) $<

%.moc: %.h
	$(MOC) $< -o $@      

####### Build rules

all: $(TARGET)

$(TARGET): $(SRCMETA) $(OBJECTS)
	$(CXX) $(OBJECTS) -o $(TARGET) $(LDFLAGS)

depend:
	@makedepend $(INCDIR) $(SOURCES) 2> /dev/null

showfiles:
	@echo $(SOURCES) $(HEADERS) Makefile

clean:
	-rm -f *.o *.bak *~ *% #*
	-rm -f $(SRCMETA) $(TARGET)

idl: kspread.idl
	idl --query-server-for-narrow -I$(KDEDIR)/idl kspread.idl

install:
	$(INSTALL_DIR) $(KDEDIR)/share/apps/koffice
	$(INSTALL_DIR) $(KDEDIR)/share/apps/koffice/partlnk
	$(INSTALL_DATA) kspread_part.kdelnk $(KDEDIR)/share/apps/koffice/partlnk/kspread.kdelnk
	$(INSTALL_DIR) $(KDEDIR)/idl
	$(INSTALL_DATA) kspread.idl $(KDEDIR)/idl
	( cd pics; make install; cd .. )
	( cd scripts; make install; cd .. )

####### Meta objects

# DO NOT DELETE THIS LINE -- make depend depends on it.
