if ( CMPX_INCLUDE_DIR AND CMPX_LIBRARIES )
   # in cache already
   SET( CMPX_FIND_QUIETLY TRUE )
endif ( CMPX_INCLUDE_DIR AND CMPX_LIBRARIES )

FIND_PATH( CMPX_INCLUDE_DIR NAMES cmpx.h PATH_SUFFIXES cmpx
)

FIND_LIBRARY( CMPX_LIBRARIES NAMES cmpx )


include( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( cmpx DEFAULT_MSG CMPX_INCLUDE_DIR CMPX_LIBRARIES )