FIND_PATH(LINK_GRAMMAR_INCLUDE_DIR link-grammar/link-includes.h )

FIND_LIBRARY(LINK_GRAMMAR_LIBRARIES NAMES link-grammar )

IF (LINK_GRAMMAR_INCLUDE_DIR AND LINK_GRAMMAR_LIBRARIES)
    SET(LINK_GRAMMAR_FOUND TRUE)
ENDIF (LINK_GRAMMAR_INCLUDE_DIR AND LINK_GRAMMAR_LIBRARIES)

IF (LINK_GRAMMAR_FOUND)

  IF (NOT link-grammar_FIND_QUIETLY)
    MESSAGE(STATUS "Found link-grammar: ${LINK_GRAMMAR_LIBRARIES}")
  ENDIF (NOT link-grammar_FIND_QUIETLY)

ELSE (LINK_GRAMMAR_FOUND)

  IF (link-grammar_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could NOT find link-grammar")
  ENDIF (link-grammar_FIND_REQUIRED)

ENDIF (LINK_GRAMMAR_FOUND)

MARK_AS_ADVANCED(LINK_GRAMMAR_INCLUDE_DIR LINK_GRAMMAR_LIBRARIES)
