# Generated automatically from Makefile.in by config.pl.
# KDE tags expanded automatically by am_edit - $Revision$ 
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ../../..
VPATH = .
prefix = /d2/opt/kde2
exec_prefix = ${prefix}
#>- 
bindir = ${exec_prefix}/bin
#>+ 3
DEPDIR = .deps

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/koffice
pkglibdir = $(libdir)/koffice
pkgincludedir = $(includedir)/koffice

top_builddir = ../../..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/ginstall -c -p
INSTALL_PROGRAM = ${INSTALL} $(INSTALL_STRIP_FLAG) $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux-gnu
build_triplet = i686-pc-linux-gnu
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_alias = i686-pc-linux-gnu
target_triplet = i686-pc-linux-gnu
ARTSCCONFIG = /d2/opt/kde2/bin/artsc-config
AS = @AS@
AUTODIRS = 
CC = gcc
CONF_FILES =  $(top_srcdir)/./admin/configure.in.min $(top_srcdir)/configure.in.in $(top_srcdir)/./example/configure.in.in $(top_srcdir)/./graphite/configure.in.in $(top_srcdir)/./kformula/configure.in.in $(top_srcdir)/./kimageshop/configure.in.in $(top_srcdir)/./kivio/configure.in.in $(top_srcdir)/./kspread/plugins/calculator/configure.in.in $(top_srcdir)/./lib/configure.in.in $(top_srcdir)/./lib/kformula2/configure.in.in $(top_srcdir)/./plugins/configure.in.in
CPP = gcc -E
CXX = g++
CXXCPP = g++ -E
DCOPIDL = /d2/opt/kde2/bin/dcopidl
DCOPIDL2CPP = /d2/opt/kde2/bin/dcopidl2cpp
DCOP_DEPENDENCIES = $(DCOPIDL)
DLLTOOL = @DLLTOOL@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
EXEEXT = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = /usr/bin/msgfmt
IDL = @IDL@
IDL_DEPENDENCIES = @IDL_DEPENDENCIES@
KDB2HTML = /d2/opt/kde2/bin/kdb2html
KDECONFIG = /d2/opt/kde2/bin/kde-config
KDE_CXXFLAGS = 
KDE_EXTRA_RPATH = 
KDE_INCLUDES = -I/d2/opt/kde2/include
KDE_LDFLAGS = -L/d2/opt/kde2/lib
KDE_PLUGIN = -avoid-version -module -no-undefined
KDE_RPATH = -R $(kde_libraries) -R $(qt_libraries) -R $(x_libraries)
KDE_USE_CLOSURE_FALSE = #
KDE_USE_CLOSURE_TRUE = 
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
KOFFICECORE_INCLUDES = -I$(top_srcdir)/lib/kofficecore -I$(top_builddir)/lib/kofficecore
KOFFICEUI_INCLUDES = -I$(top_srcdir)/lib/kofficeui -I$(top_builddir)/lib/kofficeui
KOFFICE_INCLUDES = $(KOFFICEUI_INCLUDES) $(KOFFICECORE_INCLUDES) $(KOML_INCLUDES) $(KSTORE_INCLUDES)
KOFFICE_LIBS = $(LIB_KOFFICEUI) $(LIB_KOFFICECORE) $(LIB_KSTORE) $(LIB_KOML)
KOML_INCLUDES = -I$(top_srcdir)/lib/koml -I$(top_builddir)/lib/koml
KSTORE_INCLUDES = -I$(top_srcdir)/lib/store -I$(top_builddir)/lib/store
KWMF_INCLUDES = -I$(top_srcdir)/lib/kwmf -I$(top_builddir)/lib/kwmf
LIBCOMPAT = 
LIBCRYPT = -lcrypt
LIBDL = -ldl
LIBJPEG = -ljpeg6b
LIBMICO = @LIBMICO@
LIBOBJS = @LIBOBJS@
LIBPNG = -lpng -lz -lm
LIBPTHREAD = -lpthread
LIBPYTHON = 
LIBQIMGIO = @LIBQIMGIO@
LIBSM = -lSM -lICE
LIBSOCKET = 
LIBTIFF = -ltiff -ljpeg6b -lz
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBUCB = 
LIBZ = -lz
LIB_KAB = -lkab
LIB_KDECORE = -lkdecore
LIB_KDEUI = -lkdeui
LIB_KFILE = -lkfile
LIB_KFM = 
LIB_KFORMULA = -lkformula
LIB_KHTML = -lkhtml
LIB_KIMGIO = -lkimgio
LIB_KIO = -lkio
LIB_KOFFICECORE = $(top_builddir)/lib/kofficecore/libkofficecore.la
LIB_KOFFICEUI = $(top_builddir)/lib/kofficeui/libkofficeui.la
LIB_KOML = $(top_builddir)/lib/koml/libkoml.la
LIB_KPARTS = -lkparts
LIB_KSPELL = -lkspell
LIB_KSTORE = $(top_builddir)/lib/store/libkstore.la
LIB_KSYCOCA = -lksycoca
LIB_KWMF = $(top_builddir)/lib/kwmf/libkwmf.la
LIB_KWRITE = -lkwrite
LIB_QT = -lqt $(LIBPNG) $(LIBJPEG) -lXext $(LIB_X11) $(LIBSM)
LIB_SMB = -lsmb
LIB_X11 = -lX11 $(LIBSOCKET)
LN_S = ln -s
MAKEINFO = makeinfo
MCOPIDL = /d2/opt/kde2/bin/mcopidl
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = /d2/src/gassauer.cvs/kde2/qt-copy/bin/moc
MSGFMT = /usr/bin/msgfmt
NOOPT_CXXFLAGS =  -fno-exceptions -fno-check-new -Wall -pedantic -W -Wpointer-arith -Wmissing-prototypes -Wwrite-strings -Wno-long-long -Wnon-virtual-dtor -fno-builtin
NOREPO = -fno-repo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = koffice
PAMINC = @PAMINC@
PAMLIBPATHS = @PAMLIBPATHS@
PAMLIBS = @PAMLIBS@
PYTHONINC = 
PYTHONLIB = 
PYTHONMODDIR = no
QT_INCLUDES = -I/d2/src/gassauer.cvs/kde2/qt-copy/include
QT_LDFLAGS = -L/d2/src/gassauer.cvs/kde2/qt-copy/lib
RANLIB = ranlib
REPO = -frepo
SCANDIR = scan
STRIP = strip
TOPSUBDIRS =  doc kchart killustrator kimageshop kivio koshell kpresenter kspread kword pics plugins servicetypes templates tools
UIC = /d2/src/gassauer.cvs/kde2/qt-copy/bin/uic
USER_INCLUDES = 
USER_LDFLAGS = 
USE_EXCEPTIONS = -fexceptions
USE_RTTI = -frtti
USE_THREADS = @USE_THREADS@
VERSION = 2.1
XGETTEXT = /usr/bin/xgettext
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS = 
X_INCLUDES = -I/usr/X11R6/include
X_LDFLAGS = -L/usr/X11R6/lib
X_PRE_LIBS = 
all_includes = -I/d2/opt/kde2/include -I/d2/src/gassauer.cvs/kde2/qt-copy/include -I/usr/X11R6/include 
all_libraries = -L/usr/X11R6/lib -L/d2/src/gassauer.cvs/kde2/qt-copy/lib -L/d2/opt/kde2/lib 
idldir = $(includedir)/idl
interfacedir = $(top_srcdir)/lib/interfaces
kde_appsdir = ${prefix}/share/applnk
kde_bindir = ${exec_prefix}/bin
kde_confdir = ${prefix}/share/config
kde_datadir = ${prefix}/share/apps
kde_htmldir = ${prefix}/share/doc/HTML
kde_icondir = ${prefix}/share/icons
kde_includes = /d2/opt/kde2/include
kde_libraries = /d2/opt/kde2/lib
kde_libs_htmldir = /d2/opt/kde2/share/doc/HTML
kde_libs_prefix = /d2/opt/kde2
kde_locale = ${prefix}/share/locale
kde_mimedir = ${prefix}/share/mimelnk
kde_moduledir = ${exec_prefix}/lib/kde2
kde_servicesdir = ${prefix}/share/services
kde_servicetypesdir = ${prefix}/share/servicetypes
kde_sounddir = ${prefix}/share/sounds
kde_templatesdir = ${prefix}/share/templates
kde_wallpaperdir = ${prefix}/share/wallpapers
micodir = @micodir@
qt_includes = /d2/src/gassauer.cvs/kde2/qt-copy/include
qt_libraries = /d2/src/gassauer.cvs/kde2/qt-copy/lib
x_includes = /usr/X11R6/include
x_libraries = /usr/X11R6/lib

template_DATA = .directory  OneColumnLandscape.desktop  OneColumnPortrait.desktop  TitleLandscape.desktop  TitlePortrait.desktop  TwoColumnLandscape.desktop  TwoColumnPortrait.desktop  emptyLandscape.desktop  emptyPortrait.desktop

templatedir = $(kde_datadir)/kpresenter/templates/letter

templatesrc_DATA =   OneColumnLandscape.kpt  OneColumnPortrait.kpt  TitleLandscape.kpt  TitlePortrait.kpt  TwoColumnLandscape.kpt  TwoColumnPortrait.kpt  emptyLandscape.kpt  emptyPortrait.kpt

templatesrcdir = $(kde_datadir)/kpresenter/templates/letter/.source
mkinstalldirs = $(SHELL) $(top_srcdir)/admin/mkinstalldirs
CONFIG_HEADER = ../../../config.h
CONFIG_CLEAN_FILES = 
DATA =  $(template_DATA) $(templatesrc_DATA)

DIST_COMMON =  Makefile.am Makefile.in


#>- DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)
#>+ 4
KDE_DIST=OneColumnLandscape.kpt OneColumnPortrait.desktop TwoColumnLandscape.kpt TitleLandscape.kpt TitlePortrait.desktop OneColumnPortrait.kpt emptyPortrait.desktop emptyLandscape.desktop TwoColumnPortrait.desktop emptyLandscape.kpt TitlePortrait.kpt TwoColumnLandscape.desktop TitleLandscape.desktop OneColumnLandscape.desktop emptyPortrait.kpt TwoColumnPortrait.kpt 

DISTFILES= $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST) $(KDE_DIST)


TAR = tar
GZIP_ENV = --best
#>- all: all-redirect
#>+ 1
all: docs-am  all-redirect
.SUFFIXES:
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
#>- 	cd $(top_srcdir) && $(AUTOMAKE) --gnu kpresenter/templates/letter/Makefile
#>+ 2
	cd $(top_srcdir) && $(AUTOMAKE) --gnu kpresenter/templates/letter/Makefile
	cd $(top_srcdir) && perl admin/am_edit kpresenter/templates/letter/Makefile.in

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


install-templateDATA: $(template_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(templatedir)
	@list='$(template_DATA)'; for p in $$list; do \
	  if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(templatedir)/$$p"; \
	    $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(templatedir)/$$p; \
	  else if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(templatedir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(templatedir)/$$p; \
	  fi; fi; \
	done

uninstall-templateDATA:
	@$(NORMAL_UNINSTALL)
	list='$(template_DATA)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(templatedir)/$$p; \
	done

install-templatesrcDATA: $(templatesrc_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(templatesrcdir)
	@list='$(templatesrc_DATA)'; for p in $$list; do \
	  if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(templatesrcdir)/$$p"; \
	    $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(templatesrcdir)/$$p; \
	  else if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(templatesrcdir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(templatesrcdir)/$$p; \
	  fi; fi; \
	done

uninstall-templatesrcDATA:
	@$(NORMAL_UNINSTALL)
	list='$(templatesrc_DATA)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(templatesrcdir)/$$p; \
	done
tags: TAGS
TAGS:


distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = kpresenter/templates/letter

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu kpresenter/templates/letter/Makefile
#>- 	@for file in $(DISTFILES); do \
#>- 	  d=$(srcdir); \
#>- 	  if test -d $$d/$$file; then \
#>- 	    cp -pr $$/$$file $(distdir)/$$file; \
#>- 	  else \
#>- 	    test -f $(distdir)/$$file \
#>- 	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
#>- 	    || cp -p $$d/$$file $(distdir)/$$file || :; \
#>- 	  fi; \
#>- 	done
#>+ 10
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am: install-templateDATA install-templatesrcDATA
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-templateDATA uninstall-templatesrcDATA
uninstall: uninstall-am
all-am: Makefile $(DATA)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(templatedir) $(DESTDIR)$(templatesrcdir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-generic mostlyclean-am

#>- clean: clean-am
#>+ 1
clean: kde-rpo-clean  clean-am

distclean-am:  distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: uninstall-templateDATA install-templateDATA \
uninstall-templatesrcDATA install-templatesrcDATA tags distdir info-am \
info dvi-am dvi check check-am installcheck-am installcheck \
install-exec-am install-exec install-data-am install-data install-am \
install uninstall-am uninstall all-redirect all-am all installdirs \
mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

#>+ 2
docs-am:

#>+ 5
force-reedit:
		cd $(top_srcdir) && $(AUTOMAKE) --gnu kpresenter/templates/letter/Makefile
	cd $(top_srcdir) && perl admin/am_edit kpresenter/templates/letter/Makefile.in


#>+ 2
final:
	$(MAKE) all-am
#>+ 2
no-final:
	$(MAKE) all-am
#>+ 3
cvs-clean:
	$(MAKE) -f $(top_srcdir)/admin/Makefile.common cvs-clean

#>+ 3
kde-rpo-clean:
	-rm -f *.rpo
