/* Define to 1 if you have the Xlib */
#cmakedefine01 HAVE_X11

#define XMLGUI_DISTRIBUTION_TEXT "${XMLGUI_DISTRIBUTION_TEXT}"
#define XMLGUI_COMPILING_OS "${CMAKE_SYSTEM}"
#define XMLGUI_COMPILER_VERSION "${XMLGUI_COMPILER_VERSION}"

#define CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}"
#define LIBEXEC_INSTALL_DIR "${LIBEXEC_INSTALL_DIR}"
