/*  This file is part of the KDE project
    Copyright (C) 2007 David Faure <faure@kde.org>

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#ifndef SHEETS_COMMON_EXPORT_H_WRAPPER
#define SHEETS_COMMON_EXPORT_H_WRAPPER

/* This is the one which does the actual work, generated by cmake */
#include "sheets_common_generated_export.h"

/* Now the same for CALLIGRA_SHEETS_COMMON_TEST_EXPORT, if compiling with unit tests enabled */
#ifdef COMPILING_TESTS
#   define CALLIGRA_SHEETS_COMMON_TEST_EXPORT CALLIGRA_SHEETS_COMMON_EXPORT
#else /* not compiling tests */
#   define CALLIGRA_SHEETS_COMMON_TEST_EXPORT
#endif

#endif
