####### Install

INSTALL = install -m 0755 -s
INSTALL_SHELL = install -m 0755
INSTALL_DATA = install -m 0644
INSTALL_DIR = install -d -m 0755
INSTALL_DIR_PRIVATE = install -d -m 0700

install:
	$(INSTALL_DIR) $(KDEDIR)/share/apps/kpresenter/pics
	$(INSTALL_DATA) kautoformedit.xpm $(KDEDIR)/share/apps/kpresenter/pics	
	$(INSTALL_DATA) kpresenter.xpm $(KDEDIR)/share/apps/kpresenter/pics	
	$(INSTALL_DIR) $(KDEDIR)/share/icons/mini
	$(INSTALL_DATA) kpresenter-mini.xpm $(KDEDIR)/share/icons/mini/kpresenter.xpm	
