//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.19 at 12:56:12 PM CET 
//


package plan.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "completion-entry")
public class CompletionEntry {

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String date;
    @XmlAttribute(name = "performed-effort")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String performedEffort;
    @XmlAttribute(name = "percent-finished")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String percentFinished;
    @XmlAttribute(name = "remaining-effort")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String remainingEffort;
    @XmlAttribute
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String note;

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the performedEffort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerformedEffort() {
        return performedEffort;
    }

    /**
     * Sets the value of the performedEffort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerformedEffort(String value) {
        this.performedEffort = value;
    }

    /**
     * Gets the value of the percentFinished property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercentFinished() {
        if (percentFinished == null) {
            return "0";
        } else {
            return percentFinished;
        }
    }

    /**
     * Sets the value of the percentFinished property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercentFinished(String value) {
        this.percentFinished = value;
    }

    /**
     * Gets the value of the remainingEffort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemainingEffort() {
        return remainingEffort;
    }

    /**
     * Sets the value of the remainingEffort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemainingEffort(String value) {
        this.remainingEffort = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

}
