//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.19 at 12:56:12 PM CET 
//


package plan.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "costplace")
public class Costplace {

    @XmlAttribute(name = "object-id", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String objectId;
    @XmlAttribute(name = "startup-cost")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String startupCost;
    @XmlAttribute(name = "shutdown-cost")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String shutdownCost;
    @XmlAttribute(name = "running-cost")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String runningCost;

    /**
     * Gets the value of the objectId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * Sets the value of the objectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectId(String value) {
        this.objectId = value;
    }

    /**
     * Gets the value of the startupCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartupCost() {
        if (startupCost == null) {
            return "0";
        } else {
            return startupCost;
        }
    }

    /**
     * Sets the value of the startupCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartupCost(String value) {
        this.startupCost = value;
    }

    /**
     * Gets the value of the shutdownCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShutdownCost() {
        if (shutdownCost == null) {
            return "0";
        } else {
            return shutdownCost;
        }
    }

    /**
     * Sets the value of the shutdownCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShutdownCost(String value) {
        this.shutdownCost = value;
    }

    /**
     * Gets the value of the runningCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunningCost() {
        if (runningCost == null) {
            return "0";
        } else {
            return runningCost;
        }
    }

    /**
     * Sets the value of the runningCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunningCost(String value) {
        this.runningCost = value;
    }

}
